README.md, lua/nvim_lsp/texlab.lua, scripts/docgen.lua
Adds the complete set of texlab settings.
Also makes a small change to the docgen script to declare fenced code as lua (vim colors the `s:` in `Commands:`).
=> Texlab settings

.github/workflows/main.yml, README.md, README_preamble.md, lua/nvim_lsp/bashls.lua, scripts/docgen.lua, scripts/docgen.sh
Improve docgen.
- Automatically generate the `Implemented servers` section.
- Remove dependency on `cat`
- Provide scripts/docgen.sh which actually reports errors.
=> Improve docgen

CONTRIBUTING.md, README.md, autoload/nvim_lsp.vim, lua/nvim_lsp/elmls.lua, lua/nvim_lsp/pyls_ms.lua, lua/nvim_lsp/rls.lua, lua/nvim_lsp/rust_analyzer.lua, lua/nvim_lsp/skeleton.lua, lua/nvim_lsp/util.lua, scripts/README_template.md, scripts/docgen.lua
- Revise docs for brevity/clarity/concision.
- Add section for "custom server" #41
- Remove Vimscript wrapper. Lua is easy to use from Vimscript, there is no reason to have multiple ways to work with nvim-lsp.
- massively clarifies the "story" that users need to comprehend
- reduces surface area, maintenance, tests
- avoids constant "Vim or Lua" dance in the documentation
- simplifies discussions, tutorials, etc.
- avoids confusing situation for users that start with Vimscript but
later need Lua-only features
=> revise docs; remove Vimscript wrapper

lua/nvim_lsp.lua, lua/nvim_lsp/intelephense.lua, lua/nvim_lsp/util.lua
This is just a modified `tsserver` script since `intelephense` is in NPM and is started the same way. 
It works, however at least in my setup I get the following error when opening a PHP file:
```
Error executing vim.schedule lua callback: ...r/neovim/HEAD-b1e4ec1/share/nvim/runtime/lua/vim/lsp.lua:430: RPC InternalError message =  "Request initialize failed with message: Cannot read property 'dataPaths' of undefined"
```
Not sure if this is an issue with neovim or Intelephense. 
Also, Intelephense has a premium mode which can be enabled using the `licenseKey` initialization option. See here: https://github.com/bmewburn/intelephense-docs
Any ideas how that would be configured?
=> Add intelephense (PHP)

README.md, lua/nvim_lsp/skeleton.lua
Nvim built-in lsp client can handle `initializeOptions` as init_options.
But nvim-lsp can't give init_options to lsp.start_client.
Not all language servers implement `workspace/didChangeConfiguration` now .(ex, gopls)
If we use those servers, we get 'not yet implement' error message.
So if config.settings is empty list, we don't request `workspace/didChangeConfiguration`.
=> skeleton.lua: fixup client initialize process

lua/nvim_lsp/metals.lua
Previously the curl to coursier would work, however, it would bring in an old version of coursier where the `latest.version` command to pull in the artifact doesn't work. You can test this by trying to do a `:LspInstall metal`, which will download coursier, but not actually download metals. This change is a small one which will follow the curl instructions found [here on the site](https://get-coursier.io/docs/cli-overview.html#curl) targeting `coursier-cli`, which is what we want, which has the ability to correctly target `latest.version`.
=> Update coursier url

lua/nvim_lsp/clangd.lua
By default, clangd will look in the current directory (and parent paths).
https://github.com/llvm-mirror/clang-tools-extra/blob/5c40544fa40bfb85ec888b6a03421b3905e4a4e7/clangd/tool/ClangdMain.cpp#L75-L81
c.f. #44
=> Default clangd's root_dir to CWD if parental directories do not have compile_commands.json etc

CONTRIBUTING.md, lua/nvim_lsp.lua
fix #80
And we are no longer bothered by conflicting in nvim_lsp.lua.
before
```
234.395   .dein >
222.443   plugin/nvim_lsp.vim
2.056     plugin/fzf.vim
1.992     plugin/abolish.vim
...
```
after
```
14.848    .dein >
2.628     plugin/nvim_lsp.vim
2.140     plugin/abolish.vim
2.043     plugin/fzf.vim
...
```
=>  lazy require language server modules

README.md, lua/nvim_lsp/clangd.lua
- On Windows an error occurred(#113).
- On non-Windows, it was always the directory where the file located.
=> Fix root_dir problem in clangd configuration

.editorconfig, autoload/health/nvim_lsp.vim, lua/nvim_lsp/configs.lua, lua/nvim_lsp/health.lua, lua/nvim_lsp/util.lua
Only check command for now.
This was much harder than expected as it's dynamically typed, the generation of the config and the start of the client is intertwined, and the logic for merging configs is very good but not the easiest to grasp.
It needs https://github.com/neovim/neovim/pull/11832 to work.
And gives this output:
```
health#nvim_lsp#check
========================================================================
- INFO: Checking pyls
- ERROR: The given command "python" is not executable.
- INFO: Checking ccls
- INFO: Checking lua_lsp
- INFO: Checking ghcide
- ERROR: The given command "ghcide" is not executable.
- INFO: Checking texlab
- ERROR: The given command "texlab" is not executable.
```
It's primitive but it's easy to improve. just check the attributes of new_config.
=> [RDY] checkhealth: add checkhealth nvim_lsp command

lua/nvim_lsp/bashls.lua, lua/nvim_lsp/ccls.lua, lua/nvim_lsp/clangd.lua, lua/nvim_lsp/configs.lua, lua/nvim_lsp/dartls.lua, lua/nvim_lsp/dockerls.lua, lua/nvim_lsp/elmls.lua, lua/nvim_lsp/flow.lua, lua/nvim_lsp/ghcide.lua, lua/nvim_lsp/gopls.lua, lua/nvim_lsp/hie.lua, lua/nvim_lsp/jsonls.lua, lua/nvim_lsp/julials.lua, lua/nvim_lsp/leanls.lua, lua/nvim_lsp/metals.lua, lua/nvim_lsp/ocamlls.lua, lua/nvim_lsp/pyls.lua, lua/nvim_lsp/rls.lua, lua/nvim_lsp/rust_analyzer.lua, lua/nvim_lsp/solargraph.lua, lua/nvim_lsp/sumneko_lua.lua, lua/nvim_lsp/terraformls.lua, lua/nvim_lsp/tsserver.lua, lua/nvim_lsp/util.lua, lua/nvim_lsp/vimls.lua, lua/nvim_lsp/yamlls.lua
fix: #94
rust-analyzer parses initializeOptions according to the type definition.
Therefore, an empty dictionary fails because it does not satisfy the type definition.
So, set the default value of ServerConfig type to initializeOptions.
https://github.com/rust-analyzer/rust-analyzer/blob/d8d8c20077702b8537086d49914d02654a46ebc5/crates/ra_lsp_server/src/main.rs#L65-L79
https://github.com/rust-analyzer/rust-analyzer/blob/dc48f89581843248660ceb755bb20469ab6ac0c9/crates/ra_lsp_server/src/config.rs#L18-L49
=> Use vim.empty_dict() instead of {}

lua/nvim_lsp/pyls.lua
[The doc](https://github.com/neovim/nvim-lsp/blob/be0f71585eb3185b214c84c643e43e9647ef67d1/README.md#pyls) says the root_dir of pyls is "vim's starting directory" but actually it is home directory.
I tried to fix #118 and noticed that rope performs rename on [files under home directory](https://github.com/python-rope/rope/blob/0.16.0/rope/refactor/rename.py#L85-L86). This significantly harms performance.
=> Change root_dir of pyls to CWD to prevent pyls from traversing HOME directory

lua/nvim_lsp/hie.lua
hie-wrapper needs the --lsp option to run as a language server https://github.com/haskell/haskell-ide-engine#using-hie-with-vim-or-neovim
=> Run hie-wrapper with --lsp

README.md, lua/nvim_lsp/clangd.lua, lua/nvim_lsp/util.lua
Fixed the following error when editing a non-existent file such as `:e test.c` on Windows after #114.
```
E5108: Error executing lua shared.lua:426: root_dir: expected directory, got test.c
```
Note: However, I feel that `clangd` is not working properly just because no error occurs (If I start editing a file that does not exist, completion will not work).
=> Fix clangd issue on Windows

.github/workflows/docgen.yml, .github/workflows/lint.yml
Hello.
I upgrade for actions/checkout@v2
This speeds up CI / CD execution time.
If you need more imformation, please  see this reference below.
> https://github.com/actions/checkout#whats-new
=> [upgrade] acitons/checkout v1 -> v2

lua/nvim_lsp/gdscript.lua
Recently Godot 3.2 was released with LSP support. But LSP works only through Websocket. [This](https://github.com/godotengine/godot/pull/35864#) PR switches Godot's LSP to TCP and now can be supported for the Vim plugins. This PR adds support for upcoming Godot version via `nc` (works only with mentioned PR above).
=> Add GDScript support

README.md, lua/nvim_lsp/configs.lua, lua/nvim_lsp/util.lua
If users want to change something like log_level for all servers, changing log_level for all servers is a bit tedious.
So we can make this easier by overriding util.default_config.
I will add documentation if we can agree with this policy.
=> default_config: let user specify default_config yourself.

lua/nvim_lsp/bashls.lua
The bash language server (if provided) will try to initialize all shell files it can find in the `root_dir`. The takes forever and probably isn't great from a security perspective.
> If the rootPath is provided it will initialize all shell files it can find anywhere on that path. This non-exhaustive glob is used to preload the parser.
https://github.com/bash-lsp/bash-language-server/blob/790f5a5203af62755d6cec38ef1620e2b2dc0dcd/server/src/analyser.ts#L33-L35
=> Change root_dir for bashls to pwd

lua/nvim_lsp/pyls_ms.lua
Latest release of the "stable" channel is `0.5.31`.
`pyls_ms.lua` has been updated.
**osx**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-osx-x64
**win**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-win-x64
**linux**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-linux-x64
=> Update pyls_ms: 0.5.31

lua/nvim_lsp/configs.lua, lua/nvim_lsp/util.lua
fix: #161. If the buffer is not actual file like the special buffer for the plugin,
it doesn't have root_dir and we should not execute lsp.start_client for that buffer.
=> if root_dir is not directry, we don't execute lsp.start_client

lua/nvim_lsp/configs.lua, lua/nvim_lsp/elmls.lua, lua/nvim_lsp/util.lua
tbl_deep_extend always override extended table properties.
This behavior is not expected. This will fix #155.
ref: https://github.com/neovim/nvim-lsp/pull/98#discussion_r368323527
=> util: add behavior options to tbl_deep_extend function

lua/nvim_lsp/codeqlls.lua
Adds support for CodeQL language server
If you want to try, you will need to install codeql-cli and ql queries. Follow instructions [here](https://help.semmle.com/codeql/codeql-cli/procedures/get-started.html#download-the-codeql-cli-zip-package)
you need to pass a `search_path` argument pointing to your QL repo. eg:
``` lua
require'nvim_lsp'.codeqlls.setup{
settings = {
search_path = {'~/codeql-home/codeql-repo'};
};
}
```
Create a directory and place a `qlpack.yml` file with:
``` yaml
name: test
version: 0.0.0
libraryPathDependencies: codeql-java
```
In the same directory write a java query `test.ql`, set filetype to `codeql` (I will soon publish a plugin for that) and write your query in it:
```
import java
from Method m
select m.getName()
```
You should get lintering and …
=> Add CodeQL support

README.md, lua/nvim_lsp/als.lua
This pull request adds support for the Ada Language Server (https://github.com/AdaCore/ada_language_server). I mostly copied what happened for the scala language server (metals) so if there are issues with this PR, there might also be some with metals :)
One thing that I'm slightly uncomfortable with is the install function, which I only tested on Linux: if it succeeds on OSX, this would be only by accident and I'm quite convinced that it would fail on Windows. Since other installers (pyls and metals) do not seem to try to be multiplatform, I thought this wouldn't be a huge problem.
=> Add Ada Language Server (als)

lua/nvim_lsp/metals.lua
This pr adds in a check to see if cs ([the Coursier native launcher](https://get-coursier.io/docs/cli-installation)) is already installed. Using the native launch is faster than using the jar based launcher. Plus a lot of scala users may have this installed already, so there is no need to install Coursier again. However, if it's not found, it just downloads it as it would have before.
I also updated the config in info to match the actual root patterns that are set in the default config.
=> add in the ability to reuse cs if already installed

lua/nvim_lsp/metals.lua
This pr adds in the ability to specify the server version (mainly so users can use snapshots), changes the message_level, and adds in all of the init_options. I'll include a couple reasonings on the various changes.
=> add in server version, message_level and init_options

lua/nvim_lsp/util.lua
Get rid of missing package.json warnings when installing npm packages.
Also eliminating package-lock.json.
=> LspInstall: --no-package-lock --no-save --production

lua/nvim_lsp/diagnosticls.lua
This adds an LS definition for [diagnostic-languageserver](https://github.com/iamcco/diagnostic-languageserver). By itself, it does nothing, a configuration using `init_options` is needed according to the configuration spec for `diagnostic-languageserver`.
=> Add diagnostic-languageserver

README.md, lua/nvim_lsp/kotlin_language_server.lua
This PR adds support for the kotlin-language-server found at fwcd's [repository](https://github.com/fwcd/kotlin-language-server).
> Please provide guidance about further steps I should consider to make this contribution pass.
// edit:
Unfortunately I did not manage to rebase an fix for recover the lint test of the CI-pipe (trailing whitespaces). Should I rebase (squash all of my commits) from the previous commit (#d16b49e)? I picked #5e5c8b5 of my branch. Result is displayed below..
=> Added support for the kotlin-language-server

lua/nvim_lsp/metals.lua
As of the 0.9.0 release of Metals, a bug was fixed where previously all
of the `InitializationOptions` needed to be specified if you set any in
order to not have a null pointer exception. This is fixed now so all of
the default have been removed, and only the necessary ones remain.
=> Remove unnecessary init_options for Metals.

lua/nvim_lsp/tsserver.lua
After this PR https://github.com/neovim/nvim-lsp/pull/222 was merged I started to get this error when opening nvim:
```
Error detected while processing FileType Autocommands for "javascript":
E5108: Error executing lua ...ovim/HEAD-d13c164/share/nvim/runtime/lua/vim/lsp/rpc.lua:208: The given command "typescript-language-server.cmd" is not execut
able.
```
The problem is that `vim.fn.has` returns `0` or `1`, and those both values are truthy values in Lua. The module needs to explicitly check for `1` in order to pass the `if` condition.
You can check how this works in Lua by running this in nvim:
```
:lua << EOF
if 0 then
print('oh no')
end
EOF
```
You should see immediatly the `oh no` message.
=> Fix: Check that vim.fn.has returns 1 in tsserver module

README.md, lua/nvim_lsp/terraformls.lua
`terraform init` creates .terraform/ and is a better indicator of the root than .git/ in many cases
=> Add .terraform/ as a root dir for terraformls

lua/nvim_lsp/pyls_ms.lua
Btw, running 
```
nvim -R -Es +'set rtp+=$PWD' +'luafile scripts/docgen.lua'
```
doesn't seem to work.
I am on macOS, maybe I should switch to Linux and try it again?
=> Add instrument of install by yourself for pyls_ms

lua/nvim_lsp/bashls.lua, lua/nvim_lsp/ccls.lua, lua/nvim_lsp/clangd.lua, lua/nvim_lsp/cssls.lua, lua/nvim_lsp/elmls.lua, lua/nvim_lsp/fortls.lua, lua/nvim_lsp/intelephense.lua, lua/nvim_lsp/leanls.lua, lua/nvim_lsp/pyls.lua, lua/nvim_lsp/pyls_ms.lua, lua/nvim_lsp/sourcekit.lua, lua/nvim_lsp/texlab.lua, lua/nvim_lsp/tsserver.lua
Remove meaningless code comments because they are increased by copy and paste.
Currently, utf8 options are only supported by clangd, so remove them from unnecessary ones.
=> config: remove unnecessary code comennts and utf8 option

lua/nvim_lsp/elixirls.lua
Add support for Elixir language server.
If you run `:LspInstaller elixirls` it clones the elixir-lsp/elixir-ls repo and builds the binary. It is only tested on Ubuntu 19.10, so should probably be tested on other environments. I'm not completely sure if the Windows install works. 
There is an error when trying to open an elixir-file if the LSP's cmd isn't configured correctly, I think that is caused by the autocmd created by M.setup in configs.lua.
=> Add configuration for elixir-ls

lua/nvim_lsp/flow.lua
Hey!
I noticed the config for the flow language server expects a specific npm script: `npm run flow lsp`. Wouldn't it be better to not rely on this npm script and use npx instead: `npx flow lsp`. This would also mean that flow will be installed if not present in the current project (see https://github.com/npm/npx#description).
Tbh, I'm not familiar with flow and how projects use it. I'm just looking at one project without that npm script and tested it with npx. If there are reason why it's done this way, feel free to close this PR, of course.
=> flow: use npx instead of expecting a npm script

lua/nvim_lsp/gdscript.lua
Some plugins uses `gdscript` as filetype. So, I added it :)
=> Add common gdscript filetype

lua/nvim_lsp/clangd.lua
I added support for [this](https://clangd.llvm.org/extensions.html#switch-between-sourceheader) extension. Very convenient feature to work with C / C++.
Made by analogy with [texlab](https://github.com/neovim/nvim-lsp/blob/master/lua/nvim_lsp/texlab.lua)
=> Improve clangd configuration

lua/nvim_lsp/metals.lua
Fix a couple of problems with the installation. The standard executable is coursier, cs is suggested as alias, which won't be necessarily found depending on the $SHELL, etc. Now we check for both. It also fixes issue where mkdir would fail if parents missing in case coursier wasn't downloaded.
/cc @ckipp01
=> Add coursier candidate, fix folder creation when empty

lua/nvim_lsp/configs.lua
microsoft/vscode-eslint requests configuration with a section of ''.
This change returns the expected settings in that case.
https://github.com/microsoft/vscode-eslint/blob/be30e933c56ea6e8e579808d5f7c7b205c8e16cc/server/src/eslintServer.ts#L668
=> Allow empty section string for configuration request

lua/nvim_lsp/util.lua
not sure about other platform, but in my linux, when I ran 
```
LspInstall bashls
```
it failed to install.
it turned out the repo was not initialized.
so I added one line of code to check if package.json exists or not, if not, then init it.
=> LspInstall not working in linux

lua/nvim_lsp/pyls_ms.lua
By default, the Microsoft Python Language Server already gets an existing Python interpreter and version from $PATH if the setting is an empty string or null.
[src/LanguageServer/Impl/Implementation/Server.cs](https://github.com/microsoft/python-language-server/blob/838ba78e00173d639bd90f54d8610ec16b4ba3a2/src/LanguageServer/Impl/Implementation/Server.cs#L143-L157)
```c#
var interpeterPath = initializationOptions?.interpreter.properties?.InterpreterPath;
Version version = null;
if (!string.IsNullOrWhiteSpace(interpeterPath)) {
Version.TryParse(initializationOptions?.interpreter.properties?.Version, out version);
} else {
var fs = _services.GetService<IFileSystem>();
var exePath = PathUtils.LookPath(fs, "python");
if (exePath != null && TryGetPythonVersion(exePath, out version)) { …
```
=> pyls_ms - Remove call to get Python interpreter and version.

README.md
The [Dart LSP spec](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec) shows that this option is `flutterOutline`, and I believe this was the intent of the original author of this file.
=> Correct "fluttreOutline" typo for `dartls`

lua/nvim_lsp/ccls.lua, lua/nvim_lsp/clangd.lua
This PR adds two identical lines in the README.md for ccls and clangd, giving details on how to easily generate a `compile_commands.txt` file using CMake.
Generating a `compile_commands.txt` file might look a cumbersome task, but CMake actually has an integration to automatically generate one inside the `${CMAKE_BINARY_DIR}` directory.
Having a reference to the CMake documentation when describing the need for a `compile_commands.txt` file might be helpful for someone.
=> Add details to generate a compile_commands.json file for ccls and clangd

lua/nvim_lsp/ocamllsp.lua
This was missing the dot before. See https://github.com/ocaml/merlin/wiki/project-configuration for details on the file.
=> Use .merlin as identifier for ocamllsp, not merlin

lua/nvim_lsp/configs.lua
high level goal is to allow users some way to set filetype for a buffer in cases where they don't want to start up an LSP server, e.g. in a fuzzy finder preview
cc @tjdevries
=> [RFC] don't start up LSP for 'nofile' buffers

lua/nvim_lsp/omnisharp.lua, lua/nvim_lsp/util.lua
Getting inspiration from https://github.com/coc-extensions/coc-omnisharp and other lsp sources here to add omnisharp lsp to the available language servers
=> Add omnisharp language server

lua/nvim_lsp/rust_analyzer.lua
Hi! It took me a while (knowing neither lua not vimscript) to figure out how to pass settings to rust-analyzer, so I thought it would be nice to document it. 
I am not sure if this change will actually be reflected in readme. Running `nvim -R -Es +'set rtp+=$PWD' +'luafile scripts/docgen.lua'` did nothing for me, so I am not sure...
=> Show correct lua syntax for configuring rust-analyzer

lua/nvim_lsp/dartls.lua
Since most of the time user just install the flutter sdk and the dart path is present in `~/flutter/bin/dart` it would be better to check first for the flutter path since even if a user has flutter path set the elseif part will be ignored every time.
=> Check flutter path for dart sdk before checking dart path

lua/nvim_lsp/util.lua
With neovim/neovim#12507 merged, we can get rid of the hacky global VimL callback :tada:
=> Switch to Lua on_exit callback in util.sh

lua/nvim_lsp/util.lua
This pull request will allow to use filename patterns on `root_pattern` function. So will possible to use something like:
```lua
root_dir = util.root_pattern("*.sln");
```
=> Allow to use filename patterns on root_pattern

README.md, lua/nvim_lsp/terraformls.lua
I guess this is potentially controversial and a new config could be created instead (this can be closed in that case). The previous `juliosueiras/terraform-lsp` project has this to say in its readme:
> The aim to have a unified lsp for terraform in the future, but for now there is two concurrent development with collabration to each other, this repo is aim for more experimental features, and the terraform-ls is aim for stableness
Hashicorp's seems to be more actively developed nowadays as well.
https://github.com/hashicorp/terraform-ls
=> Switch to Hashicorp's official Terraform language server

lua/nvim_lsp/terraformls.lua
Fix url.
[Switch to Hashicorp's official Terraform language server by lithammer · Pull Request \#345 · neovim/nvim\-lspconfig](https://github.com/neovim/nvim-lspconfig/pull/345)
=> Fix terraformls link

scripts/docgen.lua
docgen script sometimes fails at downloading language server phase.
But we can't know which language server's docgen phase was failed.
=> docgen: add '-v' option to curl for debugging

lua/lspconfig/kotlin_language_server.lua
Add root pattern files for the popular Kotlin build systems.
=> Kotlin LS: Add more root pattern files

README.md, lua/lspconfig/terraformls.lua
```console
$ terraform-ls
Usage: terraform-ls [--version] [--help] <command> [<args>]
Available commands are:
completion        Lists available completion items
inspect-module    Lists available debug items
serve             Starts the Language Server
```
```console
$ terraform-ls serve
2020/09/14 13:34:28 serve_command.go:137: Starting terraform-ls 0.0.0-dev
2020/09/14 13:34:28 service.go:60: Preparing new session ...
2020/09/14 13:34:28 service.go:77: Worker pool size set to 12
2020/09/14 13:34:28 watcher.go:118: watching for changes ...
2020/09/14 13:34:28 langserver.go:69: Starting server (pid 83736) ...
```
Ref #345
=> Fix missing argument to cmd for terraform-ls

README.md, lua/lspconfig/configs.lua, lua/lspconfig/jdtls.lua, lua/lspconfig/util.lua
The recent changes in Neovim head cause loading this file to create an error. These changes have resolved that on my machine.
Note: https://github.com/neovim/neovim/pull/12655
=> Use handlers instead of callbacks

lua/nvim_lsp/pyright.lua
Closes https://github.com/neovim/nvim-lsp/issues/299
Depends on https://github.com/neovim/neovim/pull/12638
=> Add pyright languageserver

README.md, lua/lspconfig/dartls.lua
This PR is meant to change the default type in the init_options for the dart language server because it seems like passing stringified booleans doesn't affect the behavior. This can be demonstrated if you include a small callback for [dart/textDocument/publishClosingLabels](https://github.com/dart-lang/sdk/blob/61e0098c9241261b73210b869af55577583de287/pkg/analysis_server/tool/lsp_spec/README.md#darttextdocumentpublishclosinglabels-notification).
```lua
local dart_callbacks = {}
dart_callbacks['dart/textDocument/publishClosingLabels'] = function(_, _, result, _, _) print(result) end
nvim_lsp.dartls.setup({
on_attach = dart_attach;
init_options = {
onlyAnalyzeProjectsWithOpenFiles = "true";
suggestFromUnimportedLibraries = "false";
closingLabels = "true";
};
callbacks = dart_callbacks;
}) …
```
=> [dartls] Change init_options to booleans

lua/lspconfig/kotlin_language_server.lua
Using `build.gradle[.kts]` as a root marker is a problem in multi-project setups. The plugin would find the first file relative to the source file, which is would belong to the sub-project. Instead we first have to search for a global `settings.gradle[.kts]` file.
If no global settings file exist, then we have a single project; in that case using `build.gradle[.kts]` is exactly what we want.
A multi-project setup without a global settings file is broken anyway, so no need to check for that scenario.
=> Kotlin: Fix order of root files

lua/lspconfig/leanls.lua
Otherwise, the existing root_dir won't enable leanls for the normal style of lean package.
=> Have leanls use util.find_git_ancestor.

lua/lspconfig/texlab.lua
I made a simple command for supporting Texlab forward search on current cursor position
According to [Position especification](https://microsoft.github.io/language-server-protocol/specification#position) contains a zero-based line and character number, vim.fn.line/col give a one-based number, that's why it is substracting one.
=> Add forward search command for Texlab

lua/lspconfig/tsserver.lua
Since tsserver also supports configuration for a JS project from a [jsconfig file](https://code.visualstudio.com/docs/languages/jsconfig). This will update the root pattern list for tsserver, adding `jsconfig.json` to the list.
=> Update tsserver root pattern, add jsconfig

lua/lspconfig/sumneko_lua.lua
The problem is that if you open a Lua file outside of a git repository, it will use your home directory as root directory. This causes Sumneko to scan your entire home directory for Lua files. Which is bad from both a security and performance point of view.
Fixes GH-446
=> sumneko_lua: Use bufdir instead of homedir when resolving root_dir

CONFIG.md, lua/lspconfig/sorbet.lua
Adds support for [Sorbet](https://sorbet.org), a Ruby type-checker with [LSP support as of 0.5](https://sorbet.org/blog/2019/12/20/announcing-sorbet-0.5).
Most of this I copied from the solargraph integration.
=> feat: Add Sorbet language server

CONFIG.md, lua/lspconfig/rust_analyzer.lua
Closes #479 
Note this only works around the incomplete implementation of 3.16 in core, and is the same workaround used by coc.nvim.
=> Fix rust analyzer nightly

CONFIG.md, lua/lspconfig/rust_analyzer.lua
As of the latest nightly, this seems no longer necessary
=> Remove rust analyzer workaround

CONFIG.md, lua/lspconfig/html.lua
Closes  #490
Can't do anything about this (by default) unless snippets are added to core. 
See also https://github.com/emacs-lsp/lsp-mode/issues/1449
=> vscode-html-languageserver: document reason completion is not on by default 

CONFIG.md, lua/lspconfig/julials.lua
Closes #530 
Julia fans (@coxackie  @martinzh @quantum-booty  @kdheepak ).
Please let me know if this documentation change is ok. It fixes julia "just working" on master, at the cost of a *tiny* bit of overhead on first launch of a julia buffer (100ms on my fairly old laptop)
I had to remove the following from the config to get julia to provide completions for the couple environments I tried it out on (one with flux, one with plots, there was no cross contamination of packages)
```julia
empty!(LOAD_PATH)
push!(LOAD_PATH, "@")
```
=> Update julia cmd and documentation

CONFIG.md, lua/lspconfig/solargraph.lua
Closes #387, I believe the updated README also covers the common pitfalls as to why servers don't start up (mostly root detection woes)
=> solargraph: enable diagnostics by default

README.md
=> README.md: Fix a typo in a suggested help command

lua/lspconfig/rust_analyzer.lua
Closes  #310
This will prefer git directory > rust-project.json > cargo.toml
=> rust-analyzer: fix root pattern for multi-crate projects

lua/lspconfig/clangd.lua, lua/lspconfig/util.lua
Also removes the utf8_config helper function which was only used by
clangd and is a clangd-specific protocol extension.
This was originally part of #513 but the `clangd.fileStatus` extension bit of that has been postponed.
=> clangd: fix capabilities by extending protocol defaults with utf-8 offset encoding

lua/lspconfig/metals.lua
Many of the settings that this link shows are reliant on
specific things like code lenses working. I think it's a better
idea to not show these as there are a handful of them that if a
user would use them, they won't work at all, and in the worst
case they actual may cause errors due to unsupported handlers
or LSP extensions.
=> Remove package_json link from Metals docs.

lua/lspconfig/_lspui.lua
For the non-iTerm apple user(s) out there
=> LspInfo: disable transparency for terminal emulator compatibility

lua/lspconfig.lua
Closes #663
CC: @cloggier
Will now warn you if filetypes not defined for a server.
=> Fix LspInfo when filetypes not defined

lua/lspconfig/util.lua
Closes #106
@teto it has arrived.
I like this solution best, because it allows you to modify your path to fix the issue with the server without restarting neovim.
=> Check if language server is executable before trying to start it

lua/lspconfig.lua
@weilbith
This will make LspInfo work for servers that were not started via the workspace launcher (which requires filetypes to be set).
=> Add handling for nil filetypes

lua/lspconfig/pyright.lua
This is probably the most reported issue on Gitter/IRC/reddit. It's a bad idea to rely on this fallback behavior for a variety of reasons, but I think this will cut the time I spent troubleshooting people's configurations in half 😆 
@lithammer You raised this point before. What do you thing? I also think that falling back to the parent directory of the file is probably more defined than using getcwd.
=> pyright: add current file directory as fallback for root

CONFIG.md, lua/lspconfig/angularls.lua
This is a placeholder until Angular releases a non-rc version of their update `@angular/language-server` package, which includes a `bin` entry for calling directly.
=> use new global bin command

CONFIG.md, lua/lspconfig/bashls.lua
Alternative solution to GH-685. Personally I prefer this approach since it means editing files in `~` will work just fine.
=> bashls: Set GLOB_PATTERN to prevent recursive scanning

README.md, lua/lspconfig.lua
Closes #191
The following example from the readme should now "just work"
```lua
local lspconfig = require'lspconfig'
local configs = require'lspconfig/configs'
-- Check if it's already defined for when I reload this file.
if not lspconfig.foo_lsp then
configs.foo_lsp = {
default_config = {
cmd = {'/home/ashkan/works/3rd/lua-language-server/run.sh'};
filetypes = {'lua'};
root_dir = function(fname)
return lspconfig.util.find_git_ancestor(fname) or vim.loop.os_homedir()
end;
settings = {};
};
}
end
lspconfig.foo_lsp.setup{}
```
=> lspconfig: allow accessing nil config with pcall

lua/lspconfig/rust_analyzer.lua
The shell function was added in #657. Searching google and [the neovim repository](https://github.com/neovim/neovim/search?q=shell_handler&type=commits) yields no reference to a `v:shell_handler` special variable. I believe that `v:shell_error` was intended to be used. [The docs for v:shell_error](https://neovim.io/doc/user/eval.html#v:shell_error) certainly sounds like what we want, and testing it with this change produces the correct results.
=> rust_analyzer: Fix the root_dir shell command

lua/lspconfig/nimls.lua
Added support for .nimble[1] files and replaced the fallback with buffer directory instead of home.
[1] https://github.com/nim-lang/nimble
=> nimls: root_dir improvements

README.md
Without this the `augroup` will be removed from old buffers when a new language server is attached. Found the solution here: https://stackoverflow.com/a/31822230/1862923
=> readme: Fix lsp_document_highlight augroup to work for buffers

lua/lspconfig/util.lua
has been driving me nuts for some time. This way I can use system level notifications and it's less disturbing (to me at least).
=> lspconfig: use vim.notify to warn of absent LSP executable

README.md
It was linking to a wrong page
=> Fix readme link to snippets wiki page

lua/lspconfig/denols.lua
Thank you for the nice plugin.
I added some implementations for denols. https://github.com/denoland/deno/tree/master/cli/lsp#custom-requests
- deno/cache
- deno/virtualTextDocument
`deno/cache`: This command will instruct Deno to attempt to cache a module and all of its dependencies. 
`deno/virtualTextDocument`: Requests a virtual text document from the LSP, which is a read only document that can be displayed in the client. This allows clients to access documents in the Deno cache, like remote modules and TypeScript library files built into Deno. The Deno language server will encode all internal files under the custom schema `deno:`, so clients should route all requests for the `deno:` schema back to the `deno/virtualTextDocument` API.
Furthermore, I added `DenolsDefinition` command. This …
=> Implement some denols functions

lua/lspconfig/lspinfo.lua
I am usually against this type of overengineering but LSP configuration is so complex that it may be a good idea to parse the server commands and look for their logfile as well so we can display it when we see it.
For instance hls has:
```
settings = {
haskell = {
completionSnippetsOn = false,
formattingProvider = "stylish-haskell",
logFile = "/tmp/nvim-hls.log",
hlintOn = false
}
}
```
Or even more generic, a per server debug function.
=> lspinfo: add neovim log path in header

lua/lspconfig/rust_analyzer.lua
Use `cargo metadata --no-deps` to avoid fetching dependencies that haven't been downloaded yet when getting the cargo workspace directory to avoid hangs.
=> rust_analyzer: don't fetch deps in root_dir

lua/lspconfig/denols.lua
This PR aims that we can use LSP methods in `deno://` scheme buffer.
=> denols: attach client to deno scheme buffer

lua/lspconfig/terraformls.lua
The file format that terraformls checks is HCL (Hashicorp Configuration
Language). Tools like `vim-hcl` actually set this `filetype` correctly.
Make the LSP pick up these files correctly too.
=> Set terraformls to also operate on `hcl` files

lua/lspconfig/denols.lua
fix #761 
`lua vim.lsp.buf.definition()` works in normal buffer, but doesn't work in `deno://` buffer.
`lua require('lspconfig').denols.definition()` or `:DenolsDefinition` works in `deno://` buffer.
And, I'd fixed `vim.lsp.buf.references`, too.
=> Fix denols textDocument/definition in deno 1.8

lua/lspconfig/clangd.lua
@runiq Can you test this?
From CI from your last PR:
```
Run :checkhealth for more info
26
Error detected while processing command line:
27
E5113: Error while calling lua chunk: vim/shared.lua:219: after the second argument: expected table, got nil
28
stack traceback:
29
vim/shared.lua:219: in function 'tbl_deep_extend'
30
...k/nvim-lspconfig/nvim-lspconfig/lua/lspconfig/clangd.lua:17: in main chunk
31
[C]: in function 'require'
32
scripts/docgen.lua:81: in function 'require_all_configs'
33
scripts/docgen.lua:230: in main chunk
34
Error: Process completed with exit code 1.
```
=> Fix clangd when default_config not set

lua/lspconfig/_lspui.lua
Now that https://github.com/neovim/neovim/pull/13875, using `vim.fn.nvim_create_buf` throws an error.
=> Use vim.api.nvim_create_buf instead of vim.fn.nvim_create_buf

lua/lspconfig/_lspui.lua
Neovim now requires the api be accessed through vim.api.* [reference](https://github.com/neovim/neovim/commit/e355cc8cc5c131e6df429107f321dd4a80c05065)
=> Use vim.api.* instead of vim.fn.*

lua/lspconfig/haxe_language_server.lua
This adds support for the language server used by the Visual Studio Code Haxe Extension: https://github.com/vshaxe/haxe-language-server
I've found this language server to be tricky to properly attach to, but this config should do the trick.
=> Add support for the Haxe Language Server

lua/lspconfig/pyright.lua
`pyright` allows you to organize imports through `workspace/executeCommand`, so I added a command that does this.
I tried adding a command to generate typestubs but that seems to rely on `window/showMessage`, which is not yet supported (https://github.com/neovim/neovim/issues/11710)
=> Add pyright.organizeimports command

lua/lspconfig/sumneko_lua.lua
By default, sumneko sends telemetry data containing a [randomized but unique identifier](https://github.com/sumneko/lua-language-server/blob/master/script/service/telemetry.lua#L12) to a Chinese IP. The token can be found in `lua-language-server/log/token`.
The string sent looks like this in my case (I X'ed the identifier):
```
$...pulse.XXXXXXXXXXXXXXXX.Neovim 0.5.0.J...platform.XXXXXXXXXXXXXXXX.macOS 64.libc++ libc++ 10000.clang Clang 12.0.0.
```
In case of errors, that log is sent, too. You can visit the IP to get a summary of the collected data: http://119.45.194.183
Telemetry data should always be opt-in, IMHO.
=> sumneko: do not send telemetry data by default

lua/lspconfig/lspinfo.lua
This avoids the `matchadd()` shotgun highlighting.
Before:
After:
I also changed the highlight group for the filetype from `Title` to `Identifier`, but that's totally up to debate. It just felt right to use two different groups for different things.
=> lspinfo: avoid overeager highlighting

lua/lspconfig/pyright.lua
I think we can use the [package.json](https://raw.githubusercontent.com/microsoft/pyright/master/packages/vscode-pyright/package.json) in vscode-pyright for the package.json of pyright, what do you think?
I'd be happy to hear your opinion on this.
=> pyright: add package_json path

lua/lspconfig/vala_ls.lua
take `https://github.com/phw/peek` or `https://github.com/benwaffle/vala-language-server` for example,
```shell
git clone https://github.com/benwaffle/vala-language-server
cd vala-language-server
nvim
```
we opened `src/server.vala` then the lsp will run `meson build` under the wrong dir `src/`
because the `src` dir has a file named `meson.build` which actully is not a real `meson.build`,
it is included by the root `meson.build`, and the lsp server will complain the "ERROR: First statement must be a call to project"
this PR:
1. detect the valid `meson.build` file by detection first line include `project(` detective or not
~~2. prefer cwd if root is a descendant, otherwise fallback to git repo~~
=> refactor(vala): refine vala project root detection

lua/lspconfig/tflint.lua
tflint (https://github.com/terraform-linters/tflint) is a linter for Terraform which can also act as a language server. Would it be okay to include its configuration to the project? Thank you.
=> Add tflint configuration

CONFIG.md, lua/lspconfig/util.lua
This PR fixes `root_pattern` to find directories that are included in wildignore. I think it is pretty common that people have `.git` in their wildignore, but would like to use it as a root directory marker.
I've also fixed `root_pattern` to work correctly with globs so things like `build_*` will work.
=> Fix root_pattern for wildcards and file in wildignore

README.md
The recommended configuration in the `README.md` doesn't setup the keymap for range formatting correctly: this needs to be done independent from the full document formatting and making sure the keymap is set in visual mode as it's meant to work on the selection.
=> Fix conditional keymap in README

lua/lspconfig/ccls.lua
Problem: when root_dir is not found, ccls does not work.
This pull request is using the file path as root_dir when ccls does not find root_dir
=> Use the file path as root_dir when ccls does not find root_dir

lua/lspconfig/stylelint_lsp.lua
I am the maintainer of stylelint-lsp. I recently [had a question](https://github.com/bmatcuk/stylelint-lsp/issues/13) about configuring stylelint-lsp in lspconfig, so I wanted to update the documentation. stylelint-lsp was originally written for [coc.nvim](https://github.com/neoclide/coc.nvim), which already had a stylelint plugin, so I had to use a different name for the project - one that is, sadly, not intuitive for configuring the settings in lspconfig: `stylelintplus`. I also maintain the [coc-stylelintplus](https://github.com/bmatcuk/coc-stylelintplus) project which has all of the settings details in the package.json, so I've included that in the documentation.
Happy to make any additional changes to this PR =) I have _very_ little experience with lua, so I hope I didn't mess that …
=> update stylelint_lsp documentation

lua/lspconfig/ocamlls.lua, lua/lspconfig/ocamllsp.lua
Since .merlin is now being [generated](https://tarides.com/blog/2021-01-26-recent-and-upcoming-changes-to-merlin) by dune build system, it will be less common to see it, so instead of using it as a default value i add a `*.opam` which almost every OCaml projects has it, i also added `esy.json` since it is an alternative to `package.json` in esy projects
=> Update ocaml default settings

lua/lspconfig/java_language_server.lua
I found this to be an easier setup compared to jdtls so I think it should be included here as an alternative.
=> Add configuration for java-language-server

lua/lspconfig/efm.lua
The current settings for EFM make it so that it will only work within a git repository.
This change adds a fallback, so that if the current file is _not_ inside a git repository
then the current directory is used instead.
This is useful, for example, when opening a random python file, so as to get feedback
from the system flake8.
=> Allow EFM to work on non-git repos

lua/lspconfig/pylsp.lua
See https://github.com/neovim/nvim-lspconfig/pull/883#discussion_r628316250
Today docgen made it to finish on my machine :upside_down_face: It now takes the `default_config` from the code.
=> Remove pylsp default_config doc

.github/workflows/docgen.yml
We default to read-only permissions for the "contents" scope:
https://github.com/neovim/nvim-lspconfig/settings/actions
Explicitly allow pushing commits.
https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
=> docgen: explicitly allow pushing commits

lua/lspconfig/texlab.lua
Texlab just released version 3.0.0 (on Github and homebrew; other repos might take a while longer to catch up) with breaking changes to the settings. (Also, docs moved from the website to github.)
=> [doc] update texlab settings to v3.0.0

CONFIG.md, lua/lspconfig/jdtls.lua
Why ?
Not all systems install openjdk in the same path, or even with the same name as the one provided. This replaces the example for one that works across all systems.
=> modify jdtls env var example for one that works on all systems

lua/lspconfig/ocamllsp.lua
Hi, I'm working on splitting the ocaml filetype into several ones.
Historically several file formats have been detected as just "ocaml" filetype. The filetype needs splitting because they need to uses specialized tree-sitter parsers. The plan is to adapt plugins like this one to support the filetypes before the breaking change of splitting the filetype is introduced into (neo)vim: https://github.com/ocaml/vim-ocaml/pull/61
This PR adds support for these filetypes while maintaining current behaviour when all file formats are detected as the ocaml filetype. To further complicate matters the new filetypes and the language_id expected by the server are different, so a map is added and get_language_id is defined. 
I'm new to lua, feel free to point out errors in style, I'll gladly fix them.
=> Add multiple types for ocamllsp

lua/lspconfig/jdtls.lua
I think we can use the [package.json](https://github.com/redhat-developer/vscode-java/blob/master/package.json) in [vscode-java](https://github.com/redhat-developer/vscode-java) for the `package.json` of `jdtls`, what do you think?
Thank you!
=> jdtls: add package_json path

lua/lspconfig/clangd.lua
The `’` character does not display well in non-unicode terminals. Additionally, "cannot" is better formal English, which I think should be preferred in error messages.
=> clangd: "can’t" -> "cannot" in switchSourceHeader failure message

lua/lspconfig/lean3ls.lua
Matches our VSCode's default found here:
https://github.com/leanprover/vscode-lean/blob/ca764c60acbfaeaca55a681bc0be65f84b0cae44/package.json#L32-L41
=> Increase the default memory and timeout limits in lean3ls

lua/lspconfig/terraformls.lua
The HCL format is used by lots of hashicorp tools - and some others - not only terraform: whereas the terraform language server is only meant for terraform and only useful for terraform.
This MR directly contradicts - and undoes - #757, therefore pinging @WhyNotHugo and @lithammer. I see there was some discussion in that issue: I think you simply came to the wrong conclusion.
I am currently considering switching hashivim/vim-terraform to use filetype hcl.terraform for terraform files, it was while investigating the consequences of that change that I spotted this.
hashivim/vim-terraform#168
If we do go that way, I'll likely follow up with an MR to use that filetype as a trigger for tflint and terraform-ls.
(NB this repository doesn't currently try to run tflint for non-terraform HCL files, …
=> terraform-ls is for terraform only

lua/lspconfig/julials.lua
When I start julia I print out bayes formula in startup.jl which looks like this
```
p(x|θ)p(θ)
p(θ|x) = ------------
∫p(x,θ)dθ
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
```
Which makes the executed julia command for finding the location of LanguageServer get part of bayes formula as a path. This fix makes sure that startup.jl is not executed.
=> Fixed a small gotcha where the server_path is set to nonsense if you print stuff in your startup.jl

lua/lspconfig/texlab.lua
Unfortunately, one of the new options is called `texlab.latexindent.local`, which Lua doesn't like. Let's see what CI thinks...
=> Texlab: update options for 3.1.0

README.md
Missed this typo in link in #1023.
=> Fixed link for nightly

lua/lspconfig/rust_analyzer.lua
This is a change I made in my own local nvim-lspconfig configuration but since I believe it makes things more "correct" I figured it was worth upstreaming.
The previous implementation had a couple of flaws, in particular when working with larger repositories containing multiple crates and potentially multiple Cargo workspaces.
- It would pick the current git repository by default.
- The workspace root resolution (via `cargo metadata`) was done based on the current working directory rather than the current buffer. In cases where nvim is launched at the root of the repo but a file deep down into a Cargo workspace is being edited, I would expect the workspace for that file to be chosen rather than the root of the repo.
For these reasons, we make the following changes:
- Identify the current …
=> Better root directory detection when using rust-analyzer

lua/lspconfig/util.lua
=> fix: prevent dirname return '/' if path is empty string

lua/lspconfig/configs.lua
Some language servers lazily build cmd based on a parameter passed to setup, like powershell_es. We should change this eventually, but for now be less strict.
=> fix: be less strict about cmd validation

lua/lspconfig/util.lua
I ran into a problem where language servers weren't starting properly if I edited a new file (e.g. running nvim foo.go inside a git repository or directory with a go.mod file inside, but where foo.go doesn't yet exist), and think I've tracked down the issue.
As part of looking for the root directory, the code uses vim.loop.fs_realpath to resolve symlinks. This doesn't work if the path involved doesn't yet exist (such as when creating a new file). The current behavior is to give up at this point as the returned 'real' path is nil, but we can do better by taking the unresolved path and just allowing the iterate_parents path to get the directory that the file is in (which will likely exist in most cases). This change does just that - if fs_realpath returns nil, then we just proceed with the …
=> Fix starting the LSP server when creating a new file

lua/lspconfig/solargraph.lua
Per this issue: https://github.com/castwide/solargraph/issues/455
Solargraph needs to be told it supports formatting, otherwise it won't return document_formatting as a resolved capability.
=> Add formatting true flag to init_options for solargraph

README.md
Removed the unnecessary colon in the vim-plug installation section in README.
=> Fixed vim-plug installation method

lua/lspconfig/omnisharp.lua
Solution file .sln needs to be prioritized over individual solution project files .csproj on OmniSharp root_dir configuration.
=> fix! Proritize .sln over .csproj on OmniSharp default root_dir config

lua/lspconfig/serve_d.lua
This adds support for the DLang LSP server, [serve-d](https://github.com/Pure-d/serve-d).
I've made a PR to the upstream readme about installation instructions but it doesn't seem right to include them in the docs.
=> Add serve_d.lua

lua/lspconfig/configs.lua, lua/lspconfig/util.lua
For the workspace stuff I'm working on, it would be good to have two ways to hook into lspconfig:
1. global `on_setup`. Every client config will be passed through this global function during setup if it exists.
2. `config.enabled`. When `false`, the client won't start. Use case is to disable certain lsp servers in a workspace, or programmatically based on other conditions in `config.on_new_config` (same as coc)
=> feat: added global_config hooks

lua/lspconfig/ocamllsp.lua
Pairs does not have a guaranteed iteration order, so this litters our config with new changes on each docgen update.
=> chore(ocaml): make ocaml filetype order deterministic

Makefile
it is checked on the CI but tehre is no target to reproduce locally
=> feat: add stylua check to make lint

.codespellignorewords, .github/workflows/codespell.yml, lua/lspconfig/util.lua
I've added two files related to codespell:
- `.codespellignorewords`: if you want to disable a word globally then just add it here.
- `.codespellignorelines`: if you want to stop codespell from warning in one specific instance, but not globally, then add the entire string (aka the full line) to ignore it. I don't know how to explain it well but just check the file and I think you'll get what I mean.
It's also possible to ignore files/directories, but that has to be done with the `--skip` flag to codespell.
=> ci: run codespell on pull requests

lua/lspconfig/jdtls.lua
After the discussion in #1067 this is what came up:
- Improve default root_dir: 
- Some people complaint that projects without package managers didn't work, so I added Makefile and .git
- The multi-file project root was unnecessary, it also included `.kts` files that are for Kottlin projects
- Improve cmd autodetect:
- Removed `cmd_env` property that did nothing
- Made `JAVA_HOME` and `WORKSPACE` env variables optional
- Unified `JAR` and `JDTLS_CONFIG` into `JDTLS_HOME`
- Preserved `JAR` and `JDTLS_CONFIG` with a message to avoid breaking existing configurations
- Added `.exe` for windows support
- Update documentation
- Add links to point in the right direction
- Mention jdtls-launcher as unofficial installer/launcher
- Mention nvim-jdtls as complete client implementation
- Provide …
=> Improve JDTLS defaults and improve documentation

lua/lspconfig/yamlls.lua
Installing yamlls through `npm install -g yaml-language-server` no longer works. The error I ran into is:
```sh
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml-language-server@0.21.1',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '*',
npm WARN EBADENGINE     npm: '\n\nERROR: Please use yarn, npm is not supported in this repository!!!\n\n',
npm WARN EBADENGINE     yarn: '^1.22.5'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
```
Therefore I updated the docs to use yarn.
=> Fix install command for yamlls

lua/lspconfig/sourcekit.lua
With recent versions of macOS + Xcode sourcekit-lsp is now in /usr/bin,
so running it with `xcrun` is no longer necessary. This also enables
this configuration to work on Linux.
=> Remove xcrun from sourcekit-lsp cmd

lua/lspconfig/gopls.lua
> Support go.work files ([proposal](https://go.googlesource.com/proposal/+/master/design/45713-workspace.md)).
>
> In order to better support the new proposal for a multi-module workspace mode (golang/go#45713), gopls has added support for go.work files. Try adding a go.work file to the root of your module (you still need to enable [`experimentalWorkspaceModule` mode](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-modules)) and try out the proposal!
See https://github.com/golang/tools/releases/tag/gopls%2Fv0.7.1
=> feat(gopls): add support for "go.work" files

lua/lspconfig/ccls.lua
CCLS searches for a `.ccls` file to identify the root folder for a project. This patch adds `.ccls` to the root pattern in `ccls.lua`.
=> update ccls root pattern

lua/lspconfig/tsserver.lua
This small change to the default tsserver config allows yarn's Plug'n'Play SDK to identify neovim as the editor and appropriately resolve virtual paths. It mirrors how the SDK handles other editors.
Related work
- https://github.com/theia-ide/typescript-language-server/pull/220
- https://github.com/yarnpkg/berry/pull/3041
- https://github.com/neovim/neovim/pull/14959 / https://github.com/neovim/neovim/pull/15017
- https://github.com/lbrayner/vim-rzip/issues/15
=> Support tsserver in yarn PnP projects

lua/lspconfig/bicep.lua
- Predominately copied from omnisharp as has a lot of similarities
- Added description with script to manually install latest release into
/usr/local/bin/bicep-langserver
- Requires user config to set cmd of path to installation
See https://github.com/Azure/bicep/issues/1141#issuecomment-749372637 for getting this working outside of the nvim-lspconfig repo
=> Adding the bicep language server

lua/lspconfig/configs.lua, lua/lspconfig/lspinfo.lua, lua/lspconfig/util.lua
autostart can explain why a server is not active so I think it deserves a place in `:LspInfo`. Seems like this PR wont work though because the `autostart` setting is not forwarded to the generated client, there is an `autostart()` function in its stead. 
Maybe we can rename the `autostart()` function ?
=> [RDY] show autostart status in LspInfo

test/minimal_init.lua
Besides small cosmetic changes, add
1. setting `runtimepath` to `$VIMRUNTIME` _only_  (skipping user plugins but still sourcing builtin filetype plugins)
2. putting the `packer_compiled.lua` into a temp directory to avoid clobbering the user's own (or, worse, conflicting if they configured a non-standard location themselves)
3. updating installed plugins unconditionally (to prevent stale plugins from earlier tests)
=> chore: make minimal_init.lua more robust

lua/lspconfig/dhall_lsp_server.lua, lua/lspconfig/jsonls.lua, lua/lspconfig/yamlls.lua
Fixes `root_dir` getting set to '/' because of wrong arguments to `utils.root_pattern`.
=> fix: don't pass the cwd to root_pattern

lua/lspconfig/julials.lua
Closes #1106 
The project detection logic duplicates a lot of the root detection logic.
For now, this PR addresses the biggest usability issue, which is that the current project detection logic depends on the cwd of neovim, which is brittle/causes issues like 1106.
@fredrikekre @kdheepak
=> feat(julials): detect correct root when cwd is not valid

lua/lspconfig/diagnosticls.lua
I found this bit of code yanked from `tsserver.lua` necessary to get the diagnostic-languageserver running properly on Windows.
=> feat(diagnosticls): update diagnosticls config to support windows

lua/lspconfig/julials.lua
I think after this patch, no user configuration is necessary unless you want to have LanguageServer.jl installed into a custom package environment.
=> [julia]: Better configurability for LanguageServer.jl install location.

lua/lspconfig/jsonls.lua
Same as css and html, `vscode-json-language-server` also needs snippet support enabled to make completion working.
=> Add description to jsonls

.github/ISSUE_TEMPLATE/bug_report.md
The `<details>` element is very sensitive, code blocks will not render if there is not a newline after `<summary>`.
=> docs: issue template formatting

lua/lspconfig/util.lua
Avoid de-referencing a null `client.config.filetypes` entry.
Fixes #1215
Using `minimal_init.lua` and `efm` which doesn't specify a type by default.
=> fix(ui): gracefully handle null filetypes

lua/lspconfig/bashls.lua
When using bashls with plugins like https://github.com/ahmedkhalf/project.nvim it is very annoying, when the project root suddenly changes, when you are editing a script, which is a part of a bigger project. This change should fix the issue. 
See also: https://github.com/LunarVim/LunarVim/issues/1467
=> fix(bashls): consider .git when selecting root_dir

lua/lspconfig/dartls.lua
On some systems, notably, NixOS, the Flutter SDK does not reside with the executable.
`$FLUTTER_SDK` is used to set a new path for the SDK, so this will search there first.
This solves the workaround of manually setting `cmd` in the config for dartls.
=> Respect the setting of $FLUTTER_SDK

lua/lspconfig/texlab.lua
Update the handlers for `textDocument/build` and `textDocument/forwardSearch` to the upstream breaking signature change.
=> fix(texlab): update to handler signature change

lua/lspconfig/rust_analyzer.lua
Vim's `system` output [includes both STDOUT and STDERR](https://github.com/neovim/neovim/blob/3c497e214f48ee1433d759f5a56c028df5186f24/src/nvim/os/shell.c#L773-L776), which means it may contain all sorts of debug output, especially if the user is using custom rustup toolchains.
To reproduce, set up neovim to use `lsp-config`, and then:
```console
$ cargo new foo
Created binary (application) `foo` package
$ cd foo/
$ mkdir -p toolchain/bin/
$ $EDITOR toolchain/bin/cargo
$ cat toolchain/bin/cargo
#!/bin/bash
echo "X" >&2
"$(env -u RUSTUP_TOOLCHAIN rustup +stable which cargo)" "$@"
exit 0
$ chmod +x toolchain/bin/cargo
$ ln -s "$(rustup +stable which rustc)" toolchain/bin/rustc
$ echo '[toolchain]' > rust-toolchain.toml
$ echo "path = \"$PWD/toolchain\"" >> rust-toolchain.toml
$ cargo check …
```
=> rust-analyzer: Ignore stderr when invoking cargo metadata

lua/lspconfig/clangd.lua, lua/lspconfig/rust_analyzer.lua, lua/lspconfig/texlab.lua, lua/lspconfig/util.lua
Add a compatibility shim to `util.lua` adapting to breaking change
in handler signature and use it where needed.
(Skipped `denols` and ` rust-analyzer` since those requests don't actually use a a handler.)
Closes #1239
=> fix: add compat shim for handler breaking change

lua/lspconfig/csharp_ls.lua
As on the tin
I used fsautocomplete code as a template for csharp-ls.. so I am not 100% if I adhere to project standarts for PRs.
=> feat(csharp_ls): add support for C# using csharp-ls language server

lua/lspconfig/svelte.lua
On Windows the call to the LS fails with the msg: 'E5108: Error executing lua ...ps\neovim\current\share\nvim\runtime\lua\vim\lsp\rpc.lua:384: start `svelteserver` failed: ENOENT: no such file or directory'.
It works quite fine if I use the custom cmd "svelterserver.cmd".
Other LS (e.g. pyright) also use this check.
=> Fix svelteserver on Windows

lua/lspconfig/volar.lua
This package.json does not expose relevant documentation and blocks
docgen.
=> docs: remove volar package.json

lua/lspconfig/dockerls.lua
This is already covered in core:
https://github.com//neovim/neovim/blob/52fa1d26db43664e8aeb856a59a693e9cb6ad44f/runtime/filetype.vim#L396
=> fix(dockerls): remove duplicate filetype

lua/lspconfig/clangd.lua, lua/lspconfig/configs.lua
Some servers (clangd, rust-analyzer) support using byte ranges (utf-8
encodings). Currently this logic is handled in the configuration's
on_init. This is moved into the on_init wrapper to avoid being
overridden accidentally by users.
=> fix: set offset encoding by default

lua/lspconfig/ltex.lua
Initial working code to support [ltex-ls](https://github.com/valentjn/ltex-ls) with suggestion to address #858 
thanks, @mjlbach, @mfussenegger
Looking for help/suggestion about these things:
- How to generalize `dictionary, disabledRules, hiddenFalsePositives`, they currently need to be hardcoded using a valid table entry with an existing file previously created.
- Discover a better way to expose tables with file entries.
=> [WIP] Support ltex-ls

lua/lspconfig/ltex.lua
We should redirect users to grammarguard if they want something more opinionated. This seems to work fine for me.
=> feat(ltexls): simplify configuration

lua/lspconfig/arduino_language_server.lua, lua/lspconfig/dhall_lsp_server.lua, lua/lspconfig/fstar.lua, lua/lspconfig/r_language_server.lua
Screenshot of changes:
<details><summary>arduino_language_server</summary>
</details>
<details><summary>dhall_lsp_server</summary>
</details>
<details><summary>fstar</summary>
</details>
<details><summary>r_language_server</summary>
</details>
=> docs: fix broken codeblocks in CONFIG descriptions

lua/lspconfig/als.lua
It's a no-brainer. The comment saying what to do to fix this was already there.
=> Add .gpr and .adc root marker files for als

lua/lspconfig/solang.lua
Solang needs to specify a target now, can be: ewasm, solana, substrate.
We will default to ewasm.
Ported from https://github.com/williamboman/nvim-lsp-installer/pull/249
=> fix(solang): add --target argument

lua/lspconfig/sumneko_lua.lua
Url of the wiki changed it now redirects to:
Changed it to redirect to the correct url
=> Update lua lsp wiki url

README.md
Several of the links to `server_configurations.md` were broken, as they were missing the `doc/` prefix. Fix all of them, and give them all the same relative URL.
I considered whether to use the absolute URL for all of them, or the relative URL, and it made sense to me to use the relative URL so that a fork could conceivably update the `server_configurations` document and its links would still work. I have no preference there so if you have a preference on what the actual link should be just let me know.
=> Fix all server configuration doc links in README

lua/lspconfig/leanls.lua
It lives [here](https://github.com/leanprover/lake), but is bundled with the LSP, and uses 2 new files ("lakefile.lean" and "lean-toolchain"), which I've added as markers (and prioritized).
Support is left for legacy `leanpkg.toml` files though in theory as Lean 4 gets closer to release, these likely will disappear.
(@gebner @rish987 FYI.)
=> feat(leanls): lean 4 uses a new tool called lake now

.github/workflows/close-config-changes.yml
Also change event trigger pull_request to pull_request_target since
github requires it to make any changes, even if the permission is set to
write.
=> ci: set pull-request permission to write to fix faulty workflow

lua/lspconfig/denols.lua
* deno ls uses ts for typescript, which requires a custom markdown
codefence
=> docs(denlos): mention codefences for hover

lua/lspconfig/yamlls.lua
Closes https://github.com/neovim/nvim-lspconfig/issues/1207
We get a lot of questions about settings schemas, probably worth embedding in the documentation.
cc @longwuyuan @kylo252 
I'm still not sure I understand using the yaml store url instead of the direct url path, as from the documentation I got the impression you need to explicitly associate a document uri with a schema.
=> docs(yammlls): add examples for schemas

lua/lspconfig/vdmj.lua
This PR adds a configuration for the VDMJ language server. Below I highlighted a couple of small issues I would like some help with before merging.
I tested this configuration on Arch Linux and MacOS Catalina, but I have no way to test it on Windows. I expect some minor modification will be needed to make it work on Windows.
Also, for this to work properly https://github.com/neovim/neovim/commit/1dab9357de586b08431175f19a1b44bb294866d6 is needed. What is the appropriate way to mention this in the docstring (if needed at all)?
=> feat: add vdmj language server

lua/lspconfig/graphql.lua
This fixes grapqhl lsp not setting the correct root_dir when using graphql.config.* files
=> Fix(graphql):  root dir not being set when using graphql.config.* files

test/minimal_init.lua
- let `packpath` use the correct temp folder per platform
- use the appropriate path-separator per platform
=> feat: support using `minimal_init.lua` on windows

lua/lspconfig/dockerls.lua
Allow `dockerls` to attach to a dockerfiles regardless if the default `Dockerfile` is found.
This is useful for editing files with custom names, e.g. `Dockerfile.release`
=> fix: add single_file_support for dockerls

lua/lspconfig/powershell_es.lua
1. Now the cmd in "new_config" is only generated with "make_cmd" if
there is no cmd already in "new_config"
2. make_cmd now takes "new_config" as an argument instead of just
"bundle_path"
3. Support support changing the execution shell by setting the
"shell" member in "new_config"
=> fix(powershell_es): don't overwrite cmd when it is present in the new config

.github/workflows/lint.yml, .github/workflows/problem_matchers/selene.json, Makefile, neovim.toml, selene.toml
https://github.com/Kampfkarren/selene
=> Add Selene linter

lua/lspconfig/texlab.lua
For multifile projects, it is common to have a `.latexmkrc` in the project root directory to set default build options. Use that as root marker (but keep `.git` as a fallback).
=> fix(texlab): add language-specific root marker

lua/lspconfig/julials.lua
Proper Julia packages have a `Project.toml` in the root directory. Use that as root marker (but keep `.git` as a fallback).
=> fix(julials): add language-specific root marker

lua/lspconfig/util.lua
* find_git_ancestor previously only checked for `.git ` directories
* git worktrees use a `.git` file with reference to the original git
directory
=> feat: add worktree support to find_git_ancestor

lua/lspconfig/spectral.lua
This adds support for [Spectral](https://github.com/stoplightio/spectral), a flexible JSON/YAML linter for creating automated style guides, with baked in support for OpenAPI v2 & v3.
=> feat: add spectral-language-server support

lua/lspconfig/clojure_lsp.lua
Shadow-cljs is a build tool for cljs with many features such as npm integration and live reloading.
Link: https://github.com/thheller/shadow-cljs
=>  feat(clojure_lsp) add support for shadow-cljs in clojure_lsp 

.github/workflows/docgen.yml, .github/workflows/lint.yml, .github/workflows/test.yml
This will silence the false warning 'Value must be "self-hosted"'
warning from yamlls.
=> ci: remove brackets on the "runs-on" argument

.github/workflows/close-config-changes.yml, .github/workflows/commit_lint.yml, .github/workflows/sanitizer.yml
The official GitHub actions update the vX tags to be the latest.
Workflows automatically benefit from bugfixes/patches without manually
needing to update the workflows.
=> ci: use v2 tag for checkout actions

lua/lspconfig/health.lua
It seems that my last change was not reflected in #1461. Sorry, the first `#configs` was wrong. It seems to be a table without an array part, so it needs to be `not next(configs)`.
=> fix(health): fix problem of always showing warning

lua/lspconfig/typeprof.lua
In Ruby 3.1, TypeProf adds experimental LSP support. This adds a configuration profile for using that LSP in NeoVim.
=> feat: add ruby typeprof support

lua/lspconfig/lean3ls.lua, lua/lspconfig/leanls.lua
I thought this worked previously, but prior to this change, doing
`nvim non/existent/directory/foo.lean` was raising errors like:
```
~/Development/nvim-lspconfig is a git repository on master 
⊙  n foo/bar.lean                                                                                                                                                                   julian@Airm
Error detected while processing BufNewFile Autocommands for "*.lean":                                                                                                                           
E5108: Error executing lua vim/_meta.lua:180: Vim(lua):E5108: Error executing lua ...neovim/HEAD-fd6df74_1/share/nvim/runtime/lua/vim/lsp.lua:245: cmd_cwd: expected directory, got /Users/julia …
```
=> fix(leanls): make opening nonexisting directories work

lua/lspconfig/util.lua
* start_client handles checking if the server is executable, it is
redundant to check this in lspconfig
* vim.fn.executable does not respect cmd_env, which can allow injecting
servers via a local PATH override
cc @williamboman
=> chore: remove executable check

lua/lspconfig/julials.lua, lua/lspconfig/util.lua
#1474 [breaks `lean.nvim`'s CI making the LSP not come up properly](https://github.com/Julian/lean.nvim/runs/4326198672?check_suite_focus=true#step:8:47) and I don't understand why :/ but it'd appear indeed it has different behavior in a relevant way to us.
Re-submitting the fix as I originally had it for this, which seems to pass the tests as well as make the error go away.
=> fix: set the right default cwd for cmds when unset

lua/lspconfig.lua, lua/lspconfig/configs.lua, lua/lspconfig/server_configurations/eslint.lua, lua/lspconfig/server_configurations/rust_analyzer.lua, lua/lspconfig/server_configurations/vdmj.lua, lua/lspconfig/util.lua
I was playing around a bit with some stuff when I suddenly started getting the `Cannot access configuration for %s.` warning message and at first I had no idea where it originated from and had to grep for it in across all plugins. Figured it'd make sense to prepend the messages with a tag. I think this should be part of core, somehow? Maybe making use of the `opts` param, although that'd add a lot of boilerplate
```lua
vim.notify("This is my error message.", vim.log.levels.ERROR, {
tag = "lspconfig"
})
```
=> chore: tag all vim.notify message with lspconfig

lua/lspconfig/server_configurations/yamlls.lua
This is a filetype used by for example:
- https://github.com/ekalinin/Dockerfile.vim
- https://github.com/sheerun/vim-polyglot
=> fix(yamlls): add yaml.docker-compose to filetypes

lua/lspconfig/server_configurations/tailwindcss.lua
Version `0.0.5` of [`@tailwindcss/language-server`](https://www.npmjs.com/package/@tailwindcss/language-server) requires setting `classAttriubtes` during LSP setup.
nvim-lspconfig didn't set any class atributes by default, so the LSP failed to initialize.
This fix adds these default classAttributes to tailwindcss:
- `class`
- `className`
- `classList`
This change passes all tests ran by `make lint` and `make test`.
Fixes neovim/nvim-lspconfig#1504
=> fix(tailwindcss): Add default classAttributes

lua/lspconfig/server_configurations/eslint.lua
Closes #1427
* location mode uses the workspace folder location or
the file location (if no workspace folder is open) as
the working directory
=> fix(eslint): default to location mode for workingDirectory

lua/lspconfig/server_configurations/golangci_lint_ls.lua
Combination of both lint server and client
https://github.com/nametake/golangci-lint-langserver
https://github.com/golangci/golangci-lint
once/if merged I'll create a pull request on nvim-lsp-installer to make it easy to install
=> feat: add golangcilsp support

lua/lspconfig/server_configurations/clangd.lua, lua/lspconfig/server_configurations/texlab.lua, lua/lspconfig/util.lua
This PR only addresses clangd and texlab
It uses client.request inplace of vim.lsp.buf_request to call methods
that are outside the lspSpec such as clangd's "textDocument/switchSourceHeader"
This is done to avoid conflicts when using multiple LSPs over the same
buffer.
=> Use client.request for unique calls (clangd & texlab)

lua/lspconfig/server_configurations/eslint.lua
Now the `open` command is used to execute eslint's `openDoc` function,
but `xdg-open` is the default command in Linux used to open a file or
URL in the user's preferred application.
=> fix(eslint): openDoc function on Linux

CONTRIBUTING.md
Also add a link to each linters repository.
=> docs: add selene to the list of required linters.

lua/lspconfig/server_configurations/sumneko_lua.lua
`lua-language-server` can now be started with a simple call to the
eponymous binary. assume that can be found in `$PATH`.
=> docs(lua): simplify cmd documentation

lua/lspconfig/server_configurations/graphql.lua
It's not uncommon to have GraphQL documents inside `.jsx/.tsx` files, like so:
```tsx
const Component = () => {
const {data} = useMyPageQuery()
}
gql`
query MyPage {
stuff { here }
}
`
```
=> fix(graphql): add typescriptreact, javascriptreact filetypes

lua/lspconfig/configs.lua
Really minor, but I noticed this in https://github.com/williamboman/nvim-lsp-installer/issues/312 🙈
=> chore: fix vim.notify prefix to use the [lspconfig] format

lua/lspconfig/server_configurations/lean3ls.lua
@Julian @gebner this should fix things for us following neovim/neovim#16382.
=> fix(lean3ls): use utf-32 offset encoding

lua/lspconfig/server_configurations/solargraph.lua
I found the bug related with solargraph setting.
`:LspInfo` out is
The error log in .cache/nvim.lsp.log is
`:LspInfo` out is
=> fix: solargraph server setting

lua/lspconfig/server_configurations/ccls.lua
ccls doesn't support compile_flags.txt, see
https://github.com/MaskRay/ccls/wiki/FAQ#does-ccls-support-compile_flagstxt
=> fix(ccls): delete invalid root directory pattern

lua/lspconfig/server_configurations/grammarly.lua
Hello! This pull request adds a tiny config for the [lsp version of grammarly](https://github.com/znck/grammarly). The original is built to work with a custom language client though, so I had to make some modifications to resolve errors that made it crash. The branch of my fork with those modifications is [here](https://github.com/mtoohey31/grammarly/tree/generic-client-compat), and there's instructions for building it in the docs for the configuration. There are still some references to features provided by the custom client in my fork, but the basic functionality of displaying diagnostics and applying simple text edit code actions works without errors. The use of some code actions might result in errors though, I haven't run into any yet but I have not done extensive testing. The …
=> feat: add grammarly support

doc/lspconfig.txt, lua/lspconfig/configs.lua, lua/lspconfig/util.lua
Closes https://github.com/neovim/nvim-lspconfig/issues/1168
Closes https://github.com/neovim/nvim-lspconfig/issues/1170
Closes https://github.com/neovim/nvim-lspconfig/issues/1266
Closes https://github.com/neovim/nvim-lspconfig/issues/1543
Closes https://github.com/neovim/nvim-lspconfig/issues/1588
Closes https://github.com/neovim/nvim-lspconfig/issues/1590
I have not yet tested this.
=> fix: internally use forward delineated paths cross-platform

lua/lspconfig/configs.lua
Closes https://github.com/neovim/nvim-lspconfig/issues/1524
I want to refactor `launch()` at some point, as in retrospect it's a hacky bolt-on.
I'm going to follow-up this PR with a more generic utility function which also handles #1540
=> fix: do not attach server to buffers with nil or missing name

README.md
The URLs to the example config do not point to the right locations anymore.
=> docs: fix URLS to example configurations

lua/lspconfig/server_configurations/remark_ls.lua
This registers the new [remark-language-server](https://github.com/remarkjs/remark-language-server) for linting and formatting markdown files.
/cc @wooorm @ChristianMurphy @Murderlon
=> feat(remark): add remark-language-server

lua/lspconfig/configs.lua
Closes https://github.com/neovim/nvim-lspconfig/issues/1607
=> fix: properly handle sanitizing bufname in .launch()

lua/lspconfig/server_configurations/lean3ls.lua, lua/lspconfig/server_configurations/leanls.lua
Looks like util.path.sep is gone.
Refs: bba61ed
=> fix: use forward delineated paths in leanlsps

lua/lspconfig/server_configurations/gopls.lua
gopls introduced support for templates:
https://github.com/golang/tools/blob/master/gopls/doc/features.md#template-files
They look for 'tmpl' and 'gotmpl' extensions.
tmpl may be a tad too unspecific but adding gotmpl shouldn't hurt.
=> feat: add gotmpl to gopls

lua/lspconfig/server_configurations/nimls.lua
They aren't really the same server, so I really don't believe these settings are valid. Also, https://github.com/williamboman/nvim-lsp-installer/issues/326#issuecomment-996065450 seems to confirm this.
- https://github.com/PMunch/nimlsp (this server)
- https://github.com/pragmagic/vscode-nim
=> fix(nimls): remove erroneous package_json entry

lua/lspconfig/server_configurations/clangd.lua
Clangd background index is enabled by default for a very long while.
In the vast majority of modern versions, the flag is redundant, hence
I think it is better to remove it for clarity.
=> refactor(clangd): Remove obsolete --background-index flag

lua/lspconfig/server_configurations/leanls.lua
The argument is ignored by the server, but it is useful because it is shown by `htop`, `ps ax`, etc., so you can figure out which Lean servers are running.
The lean3ls doesn't require a corresponding change: we use the `lean-language-server` wrapper, which appends the root directory itself to the wrapped `lean --server` command.
=> feat(leanls): add root dir as command-line arg

lua/lspconfig/server_configurations/taplo.lua
Current instructions give an error (MacOS 12.1); Suggestion is to add `--locked` to the install command: https://github.com/tamasfe/taplo/issues/197#issuecomment-997160846
=> Install --locked taplo

lua/lspconfig/configs.lua
In `configs.lua`, the `autocmd` at [L93](https://github.com/neovim/nvim-lspconfig/blob/ca734985e8d0c7d7ab8722f523dccb393593b2ad/lua/lspconfig/configs.lua#L93) fails because `manager.try_add_wrapper` does not handle being supplied `nil` for `bufnr`. This PR uses the same method from `manager.try_add` at [L216](https://github.com/neovim/nvim-lspconfig/blob/ca734985e8d0c7d7ab8722f523dccb393593b2ad/lua/lspconfig/configs.lua#L216) to replace nil with `api.nvim_get_current_buf()`.
=> fix: try_add_wrapper errors if passed nil for bufnr

lua/lspconfig/server_configurations/ccls.lua
ccls use codepoint as offset_encoding
check this https://github.com/MaskRay/ccls/commit/66e9cbd9a6fbbc239af1c1014a11bea4ed25ce33
=> fix(ccls): offset_encoding = utf-32

lua/lspconfig/server_configurations/tailwindcss.lua
Last year the [Elixir team introduced](https://github.com/phoenixframework/phoenix_live_view/pull/1440) the HEEx templating engine, along with `.heex` files.
They're a superset of EEx/html-eex
=> include heex in tailwind filetypes

lua/lspconfig/server_configurations/psalm.lua
The `psalm-language-server` that gets installed via `composer require` is a shebang executable. For Windows, there's a `.bat` version.
=> fix(psalm): use .bat on Windows

lua/lspconfig/server_configurations/jsonls.lua
I've verified that the language server also supports jsonc
=> feat(jsonls): jsonc filetype support

lua/lspconfig/configs.lua
When it reloads a server configured without "filetypes", it needs to call try_add without comparison with "filetypes".
fix: #1672
=> Call try_add when the config.filetypes is nil

README.md, doc/lspconfig.txt
This shortens the readme a bit, removes the vimscript first configuration (it doesn't reflect 90% of users), switches to packer from vim-plug, moves the diagnostic keymaps out of on_attach as the API is no longer specific to language servers, generally cleans up some redundancy.
I also removed the suggestion to port things from coc/lsp-mode as we now have more servers than they do.
Also many of the debugging suggestions around "root_dir" are no longer valid. Servers mostly "just work" now.
=> docs: update readme

lua/lspconfig/server_configurations/ansiblels.lua
The [`ansible-language-server`](https://www.npmjs.com/package/ansible-language-server) package is 6 months old and deprecated, because it has been moved to [`@ansible/ansible-language-server`](https://www.npmjs.com/package/@ansible/ansible-language-server), so this fixes the installation instructions to use the new package name. Also, while I was at it I switched the installation instructions to use npm, becuase yarn isn't required as of [ansible/ansible-language-server#22](https://github.com/ansible/ansible-language-server/pull/22), and npm is installed with node by default so we should prefer that when possible.
=> docs(ansible): fix install link and switch to npm

README.md, doc/lspconfig.txt
Shouldn't the `vim.lsp.buf.formatting()` keymap be in the `on_attach` function as it should only do something when a lsp server is attached?
=> docs: update suggested configuration readme

lua/lspconfig/server_configurations/leanls.lua
Enables workspace symbols for the Lean 4 LSP.
Older versions of Lake (and Lean 4) lack a serve command,
so on those we fallback to the old behavior by directly starting
the LSP.
Closes: Julian/lean.nvim#229
Refs: leanprover/lake#46
CC @gebner
=> feat(leanls): start the LSP via lake serve

lua/lspconfig/configs.lua
This message is harmless, but for some reason a decent chunk of users are extremely bothered by its presence, so let's just remove it.
=> feat: remove warning when server fails to start

lua/lspconfig/server_configurations/gopls.lua
gopls has supported single file mode as of [https://go-review.googlesource.com/c/tools/+/240099/](https://go-review.googlesource.com/c/tools/+/240099/)
I tested it locally and it works for me. The only weirdness I noticed was that it takes 10-20 seconds for the server to start returning information for single files. Startup is slow in vscode as well, so I assume it is a problem with gopls.
=> feat(gopls): added single_file_support config

lua/lspconfig/server_configurations/leanls.lua
This makes the Lean 4 LSP work again on the core lean4 project (which doesn't have a lakefile).
See comments on #1698. cc @Julian
=> fix(leanls): only use lake serve if lakefile.lean exists

lua/lspconfig/server_configurations/ansiblels.lua
to avoid ansible-lint to pop error on no ansible file (by example kubernetes deploiement)
=> fix(ansiblels): remove Yaml from ansiblels Filetype

lua/lspconfig/server_configurations/slint_lsp.lua
We are in the process of renaming our project, so I would love to be able to get the sixtyfps lsp in under its new name.
We will unfortunately need to support both the old and the new one for a while longer, so I would like to get the new one added and will only send a PR to remove the "old" one once no users are left -- if that is OK on your side of course.
I used slint_lsp and not the plain slint since this would be too close to the existing eslint for my taste:-)
=> feat: Add slint_lsp

flake.lock, flake.nix
Selene was added as a required lint, but not part of the `nix develop` shell, so I added it.
I also had to update `flake.lock`, because nixpkgs was pinned on a commit (from 2021-07-18) that didn't have selene yet.
=> fix: add selene to the nix develop shell

lua/lspconfig/server_configurations/graphql.lua
Hi there! Thank you for all of your work helping make neovim a powerful tool for developers.
I'm proposing an update to the GraphQL section of the docs. My experience was that the GraphQL language server would exit with an error when I opened a GraphQL file until I made two changes:
1. Globally installed the `graphql` package
2. Created a GraphQL config file in my project's root folder
Adding a note about these needs might help others who run into the same thing.
If it's helpful context, below are the errors I was receiving.
---
Missing module:
```
[ERROR][2022-02-26 17:20:55] .../vim/lsp/rpc.lua:420    "rpc"   "graphql-lsp"   "stderr"        "node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module 'graphql'
Require stack:
- …
```
=> docs: update GraphQL instructions

lua/lspconfig/server_configurations/sourcery.lua
Add support for https://github.com/sourcery-ai/sourcery
Related discussions: https://github.com/LunarVim/LunarVim/issues/850 and https://github.com/sourcery-ai/sourcery/issues/43
---
=> feat: add support for sourcery

lua/lspconfig/util.lua
This bug was introduced in #1324.
When calling `:LspStop <args>`, the current code tries to match a string with the format "123 (blablabla)", which will result in terminating the server with ID 123. This is fine when using autocompletion, but if doing this programmatically (or just following the docs) something like `:LspStop 1` will not match anything, resulting in terminating *all* managed servers.
This should be enough to fix the bug, allow terminating multiple servers at once and keeping the nice UX provided by the autocompletion.
=> fix(lspstop): make LspStop behave as described in the docs

lua/lspconfig/server_configurations/volar.lua
See https://github.com/johnsoncodehk/volar/issues/876
See https://github.com/johnsoncodehk/volar/blob/master/packages/vue-language-server/package.json#L2
<s>**The renamed @volar/vue-language-server package has not been released yet**. Just pre-emptively submitting the PR</s> it's released on NPM now
=> chore(volar): @volar/server -> @volar/vue-language-server

lua/lspconfig/server_configurations/volar.lua
The [`@volar/server`](https://www.npmjs.com/package/@volar/server) NPM package has been renamed to [`@volar/vue-language-server`](https://www.npmjs.com/package/@volar/vue-language-server).
The change to the server config was already made in https://github.com/neovim/nvim-lspconfig/pull/1770 so this is just updating the docs.
=> Update Volar package name in docs

lua/lspconfig/server_configurations/beancount.lua
The Beancount language server requires the `--stdio` flag to work with Neovim. This should be the default, requiring less configuration by the user.
Fixes https://github.com/polarmutex/beancount-language-server/issues/49
=> fix(beancount-langserver): add stdio flag to cmd

scripts/docgen.lua
Closes (in perhaps a trivial way) https://github.com/neovim/nvim-lspconfig/issues/1742
=> docs: remove use of debug module for automatically extracting root pattern

lua/lspconfig/server_configurations/hoon_ls.lua
Example of how to use the 'cmd' setting is not needed.
Also the name of the language server in this example is wrong.
=> fix(hoon-language-server): remove example

lua/lspconfig/server_configurations/hoon_ls.lua
Remove CMD parameters for which the language server provides defaults.
Make docs simpler.
Remove markdown code fences.
=> fix(hoon-language-server): update cmd and docs

lua/lspconfig/configs.lua, lua/lspconfig/util.lua
This was seemingly added in v0.26.0 (released 4 days ago) of luacheck: https://github.com/lunarmodules/luacheck/releases/tag/v0.26.0
lua/lspconfig/util.lua:225:40: used variable _make_config
lua/lspconfig/configs.lua:207:63: used variable _root_dir
=> ci: fix new v0.26.0 luacheck errors

lua/lspconfig/server_configurations/taplo.lua
taplo was refactored and taplo-lsp was merge into taplo-cli.
see https://github.com/tamasfe/taplo/pull/211
=> fix(taplo): update for taplo 0.6.0

lua/lspconfig/server_configurations/sumneko_lua.lua
Update root-markers for lua-language-server
- `.luarc.json`: https://github.com/sumneko/lua-language-server/wiki/Setting#sources
- [optional] `.luarcheckrc`: https://luacheck.readthedocs.io/en/stable/config.html
- [optional] `.stylua.toml`: https://github.com/JohnnyMorganz/StyLua#finding-the-configuration
- [optional] `selene.toml`: https://kampfkarren.github.io/selene/cli/usage.html
=> fix(lua-server): update root-markers

lua/lspconfig/server_configurations/clarity_lsp.lua
The prebuilt executables distributed via GitHub releases (https://github.com/hirosystems/clarity-lsp/releases) are binaries - with the Windows variant being `clarity-lsp.exe`. If building from source (Rust), it will also produce a `clarity-lsp.exe` binary.
=> fix(clarity_lsp): remove .cmd suffix for Windows

lua/lspconfig/server_configurations/ccls.lua
CCLS does not use .git to identify the root of a project. In addition, it
causes issues with projects that are based on the repo tool (e.g. AOSP),
which generates `.git` symlinks in many places in the source tree. In
such cases, CCLS incorrectly identifies subdirectories as the root.
=> fix(ccls): remove .git from root_dir

lua/lspconfig/server_configurations/ccls.lua
Use `.git` as fallback for detecting the project root in ccls, while preferring folders with `compile_commands.json` or `.ccls`. Behavior is identical to that from `clangd.lua`.
=> fix(ccls): .git as fallback when detecting project root

lua/lspconfig/server_configurations/vls.lua
I think the comment regarding lspconfig not making assumptions about path is moot for `vls`, I feel like it'd make more sense to actually provide a `cmd` for vls. There are servers where I think this does make sense, for example `omnisharp, bicep, rescriptls, elixirls, perlnavigator` (found by grepping `assumptions about your path`).
=> fix(vls): add cmd

lua/lspconfig/server_configurations/reason_ls.lua
This server config does in fact provide a default `cmd`!
=> docs(reason_ls): remove invalid comment regarding cmd

lua/lspconfig/server_configurations/eslint.lua
Even though this file name was removed from the official docs
https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-file-formats
Eslint still supports the older `.eslintrc` and it is used in tests
https://github.com/eslint/eslint/blob/9ecd42f36462331a0d697e74323a4d24f0cf02fc/tests/fixtures/.eslintrc
The loading is done by the legacy package `@eslint/eslintrc` that is
still used by eslint itself
```
~/Documents/repositories/eslint
$ npm instll && rg '".eslintrc"' ./node_modules/@eslint/eslintrc/lib -B 6
./node_modules/@eslint/eslintrc/lib/config-array-factory.js
66-const configFilenames = [
67-    ".eslintrc.js",
68-    ".eslintrc.cjs",
69-    ".eslintrc.yaml",
70-    ".eslintrc.yml",
71-    ".eslintrc.json",
72:    ".eslintrc",
```
=> fix(eslint): add missing root_pattern

lua/lspconfig/server_configurations/ocamllsp.lua
https://github.com/ocaml/ocaml-lsp/blob/master/CHANGES.md#fixes-1 ocaml-lsp-server 1.11.3 supports the `dune` filetype.
One has to run `dune build --watch` in order to take advantage of it (and then you get diagnostics  about wrong syntax when you save the file, as usual for a language server) : the language server relies on an RPC with the build system for `dune` file support.
Also improve the dune filetype detection.
cc @undu
=> ocamllsp: add support for the dune filetype

lua/lspconfig/configs.lua, lua/lspconfig/server_configurations/clangd.lua, lua/lspconfig/server_configurations/ocamllsp.lua, lua/lspconfig/util.lua, test/lspconfig_spec.lua
Previously, vim.lsp.protocol.make_client_capabilities() was used if no
capabilities were specified in either the user-provided config or the
default config (base or server).
Now, the base default config table has a capabilities key with the value
of make_client_capabilities(). When creating the finalized configuration
for a server, it simply uses the finalized config which is the
user-provided config deep extended by the default config (which now
contains the default capabilities).
This means that users will no longer have to create their own customized
capabilities tables seeded from
vim.lsp.protocol.make_client_capabilities(). They simply need to create
the parts that are new or different from the defaults and pass that as
the capabilities. The rest of the defaults are filled in …
=> feat(configs): use client capabilities in default config and deep extend user-provided capabilities

lua/lspconfig/server_configurations/glint.lua
I've tried to implement glint-language-server support. It's a little tricky, because the glint documentation advises _against_ installing glint globally, so I had to come up with a different way to find the binary.
=> feat: add glint-language-server support

lua/lspconfig/server_configurations/glint.lua, lua/lspconfig/util.lua
This changes the configuration to detect the project's `node_modules` dir every time lspconfig detects a new workspace directory (so in short, allows the server to attach to multiple projects in one session).
Not sure if setting the `PATH` like this is desirable. I did it to get a normalized `cmd`, I think it makes it easier for users to customize the cmd should they want to.
Also updates the root_dir pattern according to https://github.com/typed-ember/glint/blob/main/packages/config/README.md#config-specification
=> fix(glint): detect project dir inside `on_new_config` hook rather than at module import

lua/lspconfig/server_configurations/dartls.lua
Dart supports a much simpler way of invoking the language server: `dart language-server`. See https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec#running-the-server
=> fix(dartls): use a more concise command

lua/lspconfig/server_configurations/fortls.lua
`settings` and `init_options` are not currently supported in fortls, so the arguments to the server have to be passed via the `cmd` option or through our own config files.
=> fix(fortls): update server and default cmd args

lua/lspconfig/server_configurations/beancount.lua
The start up command and default config has changed a lot since the owner has refactored the code using rust. This pr will cover the change below.
Start up command change, should be beancount-language-server now.
Some config is not used anymore. And the only config used is journal_file(Previously it's camel case).
=> fix(beancount): fix beancount start command and config

lua/lspconfig/server_configurations/sumneko_lua.lua
There are two ways for sumneko to search for files, namely:
1. Lua.runtime.path
When using `require`, how to find the file based on the input name.
Setting this config to `?/init.lua` means that when you enter `require
'myfile'`, `${workspace}/myfile/init.lua` will be searched from the
loaded files.  if `runtime.pathStrict` is `false`,
`${workspace}/**/myfile/init.lua` will also be searched.  If you want to
load files outside the workspace, you need to set
`Lua.workspace.library` first.
2. Lua.workspace.library
In addition to the current workspace, which directories will load files
from. The files in these directories will be treated as externally
provided code libraries, and some features (such as renaming fields)
will not modify these files.
The crucial point is that `Lua.runtime.path` …
=> docs(sumneko_lua): fix usage of runtime_path

lua/lspconfig/server_configurations/volar.lua
For monorepos there can be several `node_modules` dirs. So this traverses the parents until `tsserverlibrary.js` is found in any of them instead of only checking the first `node_modules` directory.
=> docs(volar): Improve config script for monorepos

README.md, doc/lspconfig.txt, lua/lspconfig.lua
I haven't seen any previous discussions about a command like this, so
figured I'd start one by opening this PR.
From having done user support in nvim-lsp-installer for a while now, I
feel like this log file is not being reviewed by users to the extent it
should be. Although it is mentioned in the README & `:h lspconfig`, as
well as being visible in the `:LspInfo` window, I feel like a large
portion of users don't consider reviewing it while troubleshooting
issues.
I figured by providing a user command to open the log would help make it
more accessible & discoverable.
=> feat: add :LspLog command

lua/lspconfig/server_configurations/denols.lua
- Linting is now enabled by default https://deno.com/blog/v1.22#linting-enabled-by-default-in-the-lsp so it should not be turned off in these settings
- `tsconfig` is an outdated way to make any config changes in Deno and should not be used:
https://deno.land/manual/typescript/configuration#configuring-typescript-in-deno
> ⚠️ Deno v1.14 started supporting a more general configuration file that is no longer confined to specifying TypeScript compiler settings. Using tsconfig.json as a file name will still work, but we recommend to use deno.json or deno.jsonc
@jason0x43 agreed in the previous thread: https://github.com/neovim/nvim-lspconfig/pull/1321#issuecomment-1024191242
> Currently, deno only looks for deno.json, deno.jsonc, tsconfig.json, or .git to determine the root. I think dropping …
=> fix(denols):update settings for lint and tsconfig

lua/lspconfig/configs.lua, lua/lspconfig/util.lua
The no-argument versions of `:LspStop` and `:LspRestart` currently only apply to buffers that have a valid root directory. It seems that these commands should stop/restart all clients, including those associated with standalone files.
Closes #1784.
=> fix: fix for using no-argument `:LspStop` and `:LspRestart` with standalone files

lua/lspconfig/server_configurations/dartls.lua
Fixes https://github.com/neovim/nvim-lspconfig/issues/1942
Works around upstream issue https://github.com/dart-lang/sdk/issues/49157
=> fix(dartls): explicitly pass the protocol to dartls

README.md, doc/lspconfig.txt
There doesn't appear to actually be a function called `format`.
Instead, I believe what we actually want here is a call `formatting`.
=> fix(docs) vim.lsp.buf.format -> vim.lsp.buf.formatting

lua/lspconfig/server_configurations/svlangserver.lua
@henry-hsieh 👋 It seems like the server configuration for `svlangserver` included some custom `exrc`-as-json-style project settings loader, which I don't think should be part of the stock configuration provided by lspconfig, but instead provided by users themselves.
=> fix(svlangserver): don't use custom project setting resolution

lua/lspconfig/server_configurations/purescriptls.lua
As seen in the [source code](https://github.com/nwolverson/purescript-language-server/blob/db5584d79e698b02e3df12a1299d5f93262bd5ee/src/LanguageServer/IdePurescript/Main.purs#L391), Nix-related files were added to the Language server to establish the root. This commit looks to mimic that behavior. The PureScript community has a lot of Nix-positive users and tooling.
Additionally the docs were updated:
* Reflect the new `root_dir` + `root_pattern` list
* Include a list of ways to install the language server to your project
* Remove the specific, problematic npm install command because
* Globally installing these tools is a bad practice as teams should maintain consistent versions in their projects and users are less likely to remember to upgrade global packages; new documentation suggests …
=> fix(purescript-language-server): update root directory pattern for Nix-related files + doc cleanup

lua/lspconfig/server_configurations/clangd.lua
Usually the `compile_commands.json` is generated by CMake and lives in the build directory, I guess the previous author put the wrong order of `TARGET` and `LINK_NAME` of `ln(1)`.
=> fix(docs): fix the usage of ln to make symbolic links of compile_commands.json

lua/lspconfig/ui/lspinfo.lua
There are server configurations whose docs for root_dir include newlines, for example [clangd](https://github.com/williamboman/nvim-lspconfig/blob/6bffdbc3ce4b1ff31ac714f5ee3b43ab38870223/lua/lspconfig/server_configurations/clangd.lua#L69-L79). This causes the `:LspInfo` window to error during initial render (due to passing `\n` to `nvim_buf_set_lines`).
=> fix(lspinfo): trim newlines in root_dir pattern

lua/lspconfig/server_configurations/arduino_language_server.lua
Since [1] it is now mandatory to provide the '-cli' and '-clangd' flags
as their default values were removed. It is no longer possible to start
the server without these.
The '-fqbn' flag was also missing from the lspconfig docs, and per my
own testing and previous investigations [2] it is also a mandatory flag.
[1] https://github.com/arduino/arduino-language-server/commit/387a275a243e205ffe3da8400f5cbf5ecc6fa167
[2] https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/arduino_language_server/README.md#necessary-extra-configuration
=> fix(arduino_language_server): update docs with new setup instructions

lua/lspconfig/server_configurations/ocamllsp.lua
There are stable releases of OCaml-LSP in the the Opam package manager now, it no longer has to be pinned from Git.
=> fix(ocamllsp): update install instructions

lua/lspconfig/server_configurations/cmake.lua
I made a mistake in #1826, it should be fine for a project to have another
`CMakeLists.txt`, e.g. (`CMakeLists.txt` and `src/nvim/CMakeLists.txt`)
=> fix(cmake-ls): root pattern should allow nesting

README.md
Text was updated in https://github.com/neovim/nvim-lspconfig/commit/4f94bf5ba90e97a9718e5a2eb57b0737e1bdd176#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R13 but the link remains unchanged.
=> Fix wrong Neovim release link

lua/lspconfig/server_configurations/eslint.lua
In a yarn monorepo, one eslint client is opened by yarn workspace/microservice.
Currently, the ESLintFixAll had no effect except on the first eslint client that was opened. This PR uses the common util function to fetch the proper client.
This is my first time diving into lua, so let me know if it makes no sense. Cheers !
=> Fix ESLintFixAll command not working when multiple eslint clients are open

lua/lspconfig/ui/lspinfo.lua
The `vim.fn.expand '%:p:h'` used to acquire the directory of the opened buffer would actually be executed in the context of the floating `:LspInfo` - causing it to return the current working directory instead of the actual buffer directory (the one that was active when opening the `:LspInfo` window).
=> fix(lspinfo): use the active buffer when opening the window for diagnostics

lua/lspconfig/server_configurations/eslint.lua
https://yarnpkg.com/features/pnp
Yarn's PnP feature changes the way packages are installed. Instead of building on the `node_modules` resolution, it introduces a single `.pnp.*js` file in the project. This file is responsible for orchestrating and resolving dependencies. The eslint LSP server will assume that regular `node_modules` resolution applies when locating the `eslint` package - which will not work in Yarn PnP projects.
To work around this, Yarn provides the ability to run Node programs in "PnP-compat" mode via `yarn exec` and `yarn node`. My understanding is that this simply hooks into the `require()` function to resolve modules via PnP instead Node's builtin module resolution.
=> feat(eslint): support yarn2 PnP projects

lua/lspconfig/server_configurations/gradle_ls.lua
gradle-language-server doesn't work well without some kind of `init_options.settings` parameters. There's some important stuff in
https://github.com/microsoft/vscode-gradle/blob/a0151761aa2a6a07b64ced0dda5f6e9f01e77fd9/gradle-language-server/src/main/java/com/microsoft/gradle/GradleServices.java#L162-L169
that won't get called unless `init_options.settings` is at least defined. In particular if `settings == null`, gradleWrapperEnabled will be `null` as well and
https://github.com/microsoft/vscode-gradle/blob/a0151761aa2a6a07b64ced0dda5f6e9f01e77fd9/gradle-language-server/src/main/java/com/microsoft/gradle/resolver/GradleLibraryResolver.java#L106
`libFolder` won't be resolved.
I propose `init_options.settings.gradleWrapperEnabled=true` because it's a sensible default and so …
=> fix(gradle-language-server): set init_options.settings.gradleWrapperEnabled=true

lua/lspconfig/ui/lspinfo.lua
```console
$ selene .
warning[unused_variable]: buf_client_names is assigned a value, but never used
┌─ lua/lspconfig/ui/lspinfo.lua:160:9
│
160 │   local buf_client_names = {}
│         ^^^^^^^^^^^^^^^^
161 │   for _, client in pairs(buf_clients) do
162 │     table.insert(buf_client_names, client.name)
│                  ---------------- `table.insert` only writes to `buf_client_names`
warning[unused_variable]: client_names is assigned a value, but never used
┌─ lua/lspconfig/ui/lspinfo.lua:171:9
│
171 │   local client_names = {}
│         ^^^^^^^^^^^^
·
176 │     table.insert(client_names, client.name)
│                  ------------ `table.insert` only writes to `client_names`
```
=> fix: remove unused variables in `lspinfo.lua`

lua/lspconfig/server_configurations/sumneko_lua.lua
https://github.com/JohnnyMorganz/StyLua#finding-the-configuration
> The CLI looks for stylua.toml or .stylua.toml in the directory where the tool was executed. If not found, the default configuration is used.
It should be included in the default option. Many plugins use `stylua.toml` such as [packer.nvim](https://github.com/wbthomason/packer.nvim) or [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)
=> fix(sumneko_lua): Add stylua.toml

lua/lspconfig/server_configurations/antlersls.lua
Add [antlersls](https://www.npmjs.com/package/antlers-language-server) server config for [Statamic's Antlers templating language](https://statamic.dev/antlers) 🦌
Looks like the docs auto-generate off this; Not sure if I should be adding anything else to this PR ❓
PS. Special thank you to @JohnathonKoster for his work on the parser and language server implementation! 🔥
=> Add `antlersls` server config for Statamic's Antlers templating language

lua/lspconfig/server_configurations/denols.lua
If you open a file and immediately try to go to definition this error happens:
It seems to be related to some race condition where the virtual text handling is not ready yet
The exact error is 
```
{["error"]={["message"]="Method not found: deno/virtualTextDocument",["code"]="-32601"}}{["error"]={["message"]="Method not found: deno/virtualTextDocument",["code"]="-32601"}}{["error"]={["code"]="-32601",["message"]="Method not found: deno/virtualTextDocument"}}{["error"]={["code"]="-32601",["message"]="Method not found: deno/virtualTextDocument"}}⏎  
```
Because this error is unhelpful and the gotodefinition works normally after a couple of seconds, this pr propose to just ignore it.
=> fix(denols): ignore virtual text error

lua/lspconfig/server_configurations/ccls.lua, lua/lspconfig/server_configurations/denols.lua
Pretty sure only strings are allowed here. Currently the :LspInfo
window crashes if the `ccls` server has been set up but no root
directory was found (it tries to parse, and display, it as a string).
The docgen script doesn't seem too happy about it either:
=> fix(ccls): provide a string in docs.default_config.root_dir

lua/lspconfig/server_configurations/denols.lua
Caching actually works but it throws an error, vscode-deno also doesn't seem to care about errors https://github.com/denoland/vscode_deno/blob/196a11cead2d95c324cb772dd568ba7c2801b68a/client/src/commands.ts#L60
=> Ignore caching error

lua/lspconfig/server_configurations/denols.lua
fix https://github.com/neovim/nvim-lspconfig/issues/1998
I don't have a good idea *how* does this fixes the issue, but so far in my testing with this pr it seems to work perfectly.
=> fix(denols): remove unneeded lsp attach

lua/lspconfig/server_configurations/omnisharp.lua
As I was reviewing the Omnisharp LSP I found these configuration items that I
figured could be ported to lspconfig as well.
I've tested this new config in some sample projects (while comparing to
VSCode's C# plugin behaviour), seems to work fine!
I don't do any C# so I'm not sure if I'm missing something, but I believe this
should be fully backwards compatible.
These have primarily been sourced from the VSCode extension [1].
[1] https://github.com/OmniSharp/omnisharp-vscode/blob/88ad237e1e904ad0f91d2de39c30132198a02dcb/src/omnisharp/server.ts#L345-L434
=> feat(omnisharp): add more settings

lua/lspconfig/server_configurations/emmet_ls.lua
Hello, the emmet-ls config was missing filetypes supported by the language server.
=> fix: emmet-ls missing supported filetypes

lua/lspconfig/server_configurations/texlab.lua
Sometimes simple LaTeX documents are detected as plaintex rather than tex, meaning texlab will not be applied without a manual change of filetype.
=> feat(texlab): support plaintex in texlab LSP

lua/lspconfig/server_configurations/sourcery.lua
sourcery configuration requires 'lspconfig/util', where everything else uses 'lspconfig.util'.
=> fix: lspconfig.util is required with different names

lua/lspconfig/server_configurations/taplo.lua
The current link is 404, so replaced with a relevant and existing page.
=> Update the URL of taplo homepage

lua/lspconfig/server_configurations/lemminx.lua
We no longer publish the lemminx binaries to download.jboss.org as a part of our release process for vscode-xml, so the binaries for the latest releases of lemminx are not there. However, they are available on the [vscode-xml GitHub](https://github.com/redhat-developer/vscode-xml), under releases.
Signed-off-by: David Thompson <davthomp@redhat.com>
=> fix(lemminx): Change documented binary download location

lua/lspconfig/server_configurations/sumneko_lua.lua
mason bin using all cmd file so need to update check for one using mason
( not affect old nvim-lsp-installer )
=> feat(lua-language-server): add cmd for window when using mason

flake.lock
Current locked one is too old to support our `neovim.yml` format.
=> fix: update `selene` in nix develop shell

README.md
I think we should use the 
```lua
vim.lsp.buf.format { async = true }
```
=> the funtion formatting is deprecated

lua/lspconfig/server_configurations/nil_ls.lua
https://github.com/oxalica/nil
A new language server for Nix Expression Language.
~The name `nil` needs special handling since it's a keyword in Lua.~ Field name is now `nil_ls`.
=> feat: add nil support

lua/lspconfig/server_configurations/csharp_ls.lua
Full disclaimer: I have not done any F# development myself.
This is based on the project file configuration found in the LSP server
implementation itself [1].
[1]: https://github.com/razzmatazz/csharp-language-server/blob/d887595f29af334aa2900381f5336644d9ce5e61/src/CSharpLanguageServer/RoslynHelpers.fs#L550-L554
=> feat(csharp_ls): add '*.fsproj' to root_dir

lua/lspconfig/server_configurations/pasls.lua
Hello,
Pascal projects using [lazbuild](https://wiki.freepascal.org/lazbuild) use [lpi/lpk](https://wiki.freepascal.org/File_extensions) file extensions.
This PR adds them to detect the project root for pasls.
=> feat(pasls): add lpi and lpk to root dir detection

doc/lspconfig.txt
The `on_setup` hook is currently undocumented, and it should gain some attention after https://github.com/williamboman/nvim-lsp-installer/pull/631
=> docs: add an entry about the setup-hook

lua/lspconfig.lua, test/lspconfig_spec.lua
Currently, as soon as a server configuration is indexed it will be considered
"available". I'm not entirely sure if this is indeed intended behavior, all I
know is that it creates some confusion.
I figured I'd open a PR with a suggested solution immediately, to get the ball
rolling. Another solution would be to keep "available servers" as-is, and
instead introduce a new function `.configured_servers()`, and replace usage of
`.available_servers()` where appropriate (e.g., the server list at the bottom
of the `:LspInfo` window).
=> fix: only consider servers that have been set up as available

lua/lspconfig/server_configurations/glslls.lua
Works, but it looks like the server and/or vim lsp are doing something wrong for the unsupported methods. From what I understand, this isn't something that would be handled here, but correct me if I'm wrong:
```log
[ERROR][2022-07-14 13:55:11] .../lua/vim/lsp.lua:824    "LSP[glslls]"   "on_error"  {  code = "INVALID_SERVER_MESSAGE",  err = {    error = {      code = -32601,      message = "Method 'textDocument/completion' not supported."    },    jsonrpc = "2.0"  }}
[ERROR][2022-07-14 13:56:31] .../lua/vim/lsp.lua:824    "LSP[glslls]"   "on_error"  {  code = "INVALID_SERVER_MESSAGE",  err = {    error = {      code = -32601,      message = "Method 'textDocument/didSave' not supported."    },    jsonrpc = "2.0"  }}
[ERROR][2022-07-14 13:56:44] .../lua/vim/lsp.lua:824    "LSP[glslls]" …
```
=> feat: add glsl-language-server support

lua/lspconfig/util.lua, test/lspconfig_spec.lua
This change allows attaching to buffers with `zipfile:` or `tarfile:` virtual paths.
A function `util.strip_archive_subpath(path)` was added to extract the archive path from such a virtual path, and `root_dir` for `tsserver` is configured to use it by default. This means the `root_dir` search for TypeScript starts at the archive, instead of doing a real traversal starting from the file *inside* the archive. This is a compromise, because otherwise we'd have to provide a whole bunch of support functionality (currently provided by `vim.loop`) to do the necessary checks inside archives.
I targeted TypeScript for Yarn PnP support, which keeps project dependencies in zip files instead of `node_modules`. I imagine this may also be useful for other languages, like Java with JARs, but I'm really …
=> feat: allow attaching to paths inside archives

README.md
Reverts neovim/nvim-lspconfig#2074
`vim.lsp.buf.format()` is not in Nvim stable release yet.
=> Revert "the function formatting is deprecated"

lua/lspconfig/server_configurations/denols.lua
This mainly changes `lsp.buf_request` to `client.request` that way we don't send needless requests for other active unrelated servers.
=> chore(denols): Only send lsp requests to deno server

lua/lspconfig.lua
not remove deprecate function . add vim.deprecate in it.
cc @justinmk
=> fix: add vim.deprecate in old function

lua/lspconfig/server_configurations/solc.lua
Hardhat users will experience a better root dir detection if the `hardhat.config.ts` (or `.js`) file takes precedence over the git repo dir, especially in monorepos, where this could lead to faulty import statements. Note that most Solidity projects are using hardhat.
=> solc: Add hardhat.config.* to solc root detection

lua/lspconfig.lua, plugin/lspconfig.lua
`LspStart` should be work without client name args. when there is no arg passed , it should start the client which the filetypes match current buffer filetype
=> fix: lspstart should be work without arg

doc/lspconfig.txt, lua/lspconfig/configs.lua, lua/lspconfig/util.lua, test/lspconfig_spec.lua
now we can use `vim.api.nvim_create_user_command` in `on_attach` field to create commands just work for this server. so 
there is no need this field `config.commands` .
Example:
```lua
local function organize_imports()
local params = {
command = 'pyright.organizeimports',
arguments = { vim.uri_from_bufnr(0) },
}
vim.lsp.buf.execute_command(params)
end
local on_attach = function(client, bufnr)
if client.name == "pyright" then
vim.api.nvim_create_user_command("PyrightOrganizeImports", organize_imports, {desc = 'Organize Imports'})
end
end
require("lspconfig")['pyright'].setup({
on_attach = on_attach
})
```
Fix #1750
=> fix: remove the config.commands

lua/lspconfig/server_configurations/angularls.lua
Having `.git` as a pattern also enables `angularls` for non-angular projects which is not desired. Checking for only `angular.json` should be enough as every angular project must have a `angular.json`.
=> fix(angularls): remove `.git` from `root_dir`

lua/lspconfig/server_configurations/metals.lua
The newest version of metals 0.11.8 does not work with the old metals config, because now metals sends the 'workspace/configuration' call to the client, which returns null and that crashes metals with not-a-valid-json error. I traced the error to the following commit https://github.com/scalameta/metals/commit/3e0b812095e48fe6e64fbafadaa46e7ea8b9533e
As I could not guess which configuration metals would actually accept, the easiest fix was to disable capabilities.workspace.configuration, which then prevents metals from sending the fatal request. As we don't have any configuration options anyway (at least by default) this seems like a ok solution for both new and old versions of metals. I tried this locally and it seems to work.
=> fix(metals): disable capabilities.workspace.configuration

plugin/lspconfig.lua
`LspStop` should be work when pass client from cmdline. if no args stop the all the clients which filetypes match current buffer filetype
@kabouzeid  can you test this patch ?
=> fix: lspstop should close the client by given client

lua/lspconfig/server_configurations/tailwindcss.lua
I've came across problem while working on Phoenix + Surface UI + TailwindCSS. Tailwindcss is not working for elixir filetypes.
=> Added elixir filetype for tailwindcss server configuration.

lua/lspconfig/server_configurations/sumneko_lua.lua
There have been cases reported where the absence of this check causes the home directory to be set as the workspace, resulting in an error message. 
```
LSP[sumneko_lua] Your workspace is set to '/home/uga'. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/Why-scanning-home-folder)
```
=> fix(lua-language-server): check if root dir is home directory

lua/lspconfig/configs.lua, test/lspconfig_spec.lua
This is to allow 3rd party plugins to discern between what is
lspconfig's vendored server config and what the user provided.
Currently, these are merged into a single table which is passed to the
on_setup hook. Passing user_config as a 2nd argument would allow 3rd
party plugins to apply a more sensible precedence of configs.
=> feat: pass user config to the on_setup hook

lua/lspconfig/server_configurations/clangd.lua
clangd supports formatting and some basic linting for protobuf files. Here is an example .clang-format file with a section for protobuf files:
```
---
Language: Proto
BasedOnStyle: Google
ColumnLimit: 100
AllowShortFunctionsOnASingleLine: Empty
```
=> Add proto to filetypes for clangd

lua/lspconfig/ui/lspinfo.lua
This is currently causing an error when opening the :LspInfo window
while having a server configuration that doesn't provide a root_dir.
awk_ls is an example of such a config (it only supports single file
mode).
=> fix(lspinfo): nil-check config.get_root_dir

lua/lspconfig/ui/lspinfo.lua
with the upstream change `cmd` can be a function value.
Fix #2141
=> fix: check cmd type equals function

lua/lspconfig/server_configurations/elixirls.lua
I've came across problem while working on Phoenix + Surface UI + TailwindCSS. Without Elixirls I'm not able to format `.sface` file.
=> fix(elixirls): added surface filetype for elixirls server configuration

lua/lspconfig/server_configurations/sumneko_lua.lua
Neovim plugins always have a `lua/` directory where all the source code is. This PR adds this directory to the root pattern.
=> fix: added `lua/` to sumenko root patterns

lua/lspconfig/server_configurations/sumneko_lua.lua
As discussed with @zeertzjq , I've changed the root detection to how it was originally. 
But when no root file could be found, we fall back to finding a rootpattern with `lua/`
=> Sumenko lua rootpattern

lua/lspconfig/server_configurations/grammarly.lua
Base on the discussion in [znck/grammarly/](https://github.com/znck/grammarly/discussions/285)
Add clientId to init_options for fixing "Request initialize failed with message: clientId is required"
=> fix: grammarly "clientId is required"

README.md, doc/lspconfig.txt
I think it's time to apply the changes in #2074 again as [Nvim v0.8.0](
https://github.com/neovim/neovim/releases/tag/v0.8.0) has released
```
vim.lsp.buf.formatting is deprecated. Use vim.lsp.buf.format { async = true } instead
```
=> docs: `vim.lsp.buf.formatting()` is deprecated

lua/lspconfig/server_configurations/erg_language_server.lua
Repost from #2164 
[Erg Programming Language](https://erg-lang.org/)
A generic statically typed language that can deeply improve the Python ecosystem.
Please add support for the Erg language with its language server [erg-language-server](https://github.com/erg-lang/erg-language-server).
Thanks in advance,
@pysan3
=> feat: add erg-language-server support

lua/lspconfig/server_configurations/ruby_ls.lua
Without providing these the server will effectively do nothing.
The VSCode client uses these defaults:
https://github.com/Shopify/vscode-ruby-lsp/blob/4bf768d436cccce2aace8d4d738d8d15bd658759/package.json#L103.L115.
Some of these are excluded in this PR due to lack of native support.
=> feat(ruby_ls): add enabledFeatures to initialization options

lua/lspconfig/server_configurations/gdscript.lua
`vim.lsp.rpc.connect()` is unable to find a valid IP address with `localhost` changing it to `127.0.0.1` resolve the below error.
=> fix: gdscript use ip address instead of localhost

README.md
Now readme says `:h lspconfig` to show the help, but it seems typo (:h lsp-config works in my environment).
FWIW
=> fix: lspconfig help command typo

lua/lspconfig/server_configurations/volar.lua
Volar has updated the options for the language server. see https://github.com/johnsoncodehk/volar/pull/1916 
In order to support this I have update the configuration.
this also has been reported to neovim https://github.com/neovim/neovim/issues/20010 but is more related to the config not the core.
Thanks in advance.
=> feat: support volar 1.0

lua/lspconfig/server_configurations/eslint.lua
add `astro` filetype in eslint server.
Fix #2187
=> feat: eslint support astro file

lua/lspconfig/server_configurations/qmlls.lua
Now In qt6.4, the lsp is useable, so I add it
but qmlls is not always in the path, Like in archlinux, it is in the
/usr/lib/qt6/bin/qmlls, so the config maybe always needed edited by user
=> feat: add qmlls which is the lsp from qt

lua/lspconfig/server_configurations/fsautocomplete.lua
@glepnir Thanks for the revision. I have opened a new PR.
This pull request removes the `--background-service-enabled` parameter, based on https://github.com/fsharp/FsAutoComplete/pull/952
This also change handle loading of projects and type checking in an adaptive way (https://github.com/fsharp/FsAutoComplete/pull/1007 and https://github.com/ionide/ionide-vscode-fsharp/pull/1781), adding the `--adaptive-lsp-server-enabled` parameter.
Depends on [fsautocomplete 0.58.0](https://www.nuget.org/packages/fsautocomplete/0.58.0) or greater.
=> fix: remove --background-service-enabled and add  --adaptive-lsp-server-enabled for F#

lua/lspconfig/configs.lua
when user what to set cmd to vim.rpc.connect, but it is a function
nvim has already support vim.lsp.rpc.connect, but it is a function , and in the default config, it can be just set as a function, so I think lsp-config should also handle such kind of action
=> fix: cmd support vim.lsp.rpc.connect function

lua/lspconfig/server_configurations/anakin_language_server.lua
Adds support for [Anakin language server](https://pypi.org/project/anakin-language-server/), another (minimal but useful and reasonably fast) language server for Python.
I tried to run the command from the contributing doc:
```bash
nvim -R -Es +'set rtp+=$PWD' +'luafile scripts/docgen.lua'
```
It ran without errors, but I didn't see any section for the new language server config in the generated file. I'm not sure if I did something wrong.
The language server config does seem to work fine, I've been using it all day.
=> feat: add anakin language server (Python)

lua/lspconfig/server_configurations/volar.lua
Addition to #2181: 
Update the examples for extended configuration to work with Volar 1.0
=> fix(volar): update example for volar 1.0

lua/lspconfig/server_configurations/texlab.lua
`texlab` changed where they store their documentation. Since https://github.com/latex-lsp/texlab/commit/d03e350679dfdbbd0d25e3c28131c4b2677789cf they store that information in their GitHub wiki.
=> Fix dead link in `texlab` description

lua/lspconfig/server_configurations/vls.lua
`v ls` tool is used for installing, updating, and launching VLS (V Language Server).
Reference: https://github.com/vlang/v/releases/tag/0.3.1
=> fix: use `v ls` instead of `vls`

lua/lspconfig/server_configurations/eslint.lua
Eslint have a new config scheme called flat config. Will become the only supported config in v9. https://eslint.org/blog/2022/08/new-config-system-part-2/#the-new-config-file%3A-eslint.config.js
=> fix(eslint): support flat config

lua/lspconfig/server_configurations/rome.lua
Command (see https://docs.rome.tools/cli/#rome-lspproxy) was introduced for better stdin support in rome v10.0.0.
Original PR introducing this change: https://github.com/rome/tools/pull/3442
This is a breaking PR and requires users to update rome to version v10.0.0.
=> fix(rome): use lsp-proxy cmd

lua/lspconfig/server_configurations/eslint.lua
First time contributor here 🙋‍♂️
ESLint server would not find root directory when config is set in `package.json`. I created a couple of examples here:
https://github.com/gomezhyuuga/nvim-lspconfig-test-eslint
`project-eslint-packagejson` should start properly the ESLint server but it shows this error:
Seems like this was introduced in #2208. (latest working version: `3592f769f2d6b07ce3083744cd0a13442f5d4f43`) 
```
make lint
...
Total: 0 warnings / 0 errors in 189 files
Running selene
selene --display-style=quiet .
Results:
0 errors
0 warnings
0 parse errors
Running stylua
stylua --check .
```
=> fix(eslint): root dir not found if using package.json config

lua/lspconfig/server_configurations/sumneko_lua.lua
Currently when a lua file is under `..path/lua/..path` its detected by `root_pattern 'lua'` but instead of returning the expected path `..path/lua` it returns the parent path `..path/lua`
This PR fixes that
=> fix(lua-lsp): Append 'lua/' to root_patern if the pattern is under lua

lua/lspconfig/server_configurations/dolmenls.lua
This PR adds configuration for [dolmenls](https://github.com/Gbury/dolmen/blob/master/doc/lsp.md).
I didn't test the configuration on Windows.
Besides, the filetypes aren't known by neovim. We can add them as is explained in the above link.
=> feat: support dolmenls

lua/lspconfig/server_configurations/fennel-ls.lua
=> feat: add fennel-ls support

lua/lspconfig/server_configurations/jdtls.lua
Due to non-compliant message from jdtls, users may encounter issues like https://github.com/mfussenegger/nvim-jdtls/issues/327
LMK if there is a better way to do it but it seems to be the easiest temporary fix
=> fix: override another progress handler for jdtls

lua/lspconfig/server_configurations/sourcery.lua
The current documentation of `sourcery` is incorrectly formatted due to configurations not being inside code block:
=> docs(sourcery): put setup inside code block

lua/lspconfig/server_configurations/sourcery.lua
Sourcery-cli creates `auth.yaml` file to users config folder, which contains the login token. 
This PR adds check for login token in auth file. Logic shouldn't be breaking, since we're getting the token from file only if it's not defined already in lsp config.
=> Try to get sourcery auth token from config file

lua/lspconfig/server_configurations/prolog_ls.lua
Adds support for [prolog_ls](https://github.com/jamesnvc/lsp_server)
=> feat: add prolog lsp (lsp_server) support

lua/lspconfig/server_configurations/smarty_ls.lua
This PR adds support for the Smarty language server.
[https://github.com/landeaux/vscode-smarty-langserver-extracted](https://github.com/landeaux/vscode-smarty-langserver-extracted)
[https://www.smarty.net/](https://www.smarty.net/)
=> feat: support smarty

lua/lspconfig/ui/lspinfo.lua
when we override the root pattern it still show the patterns from document config.  see #2273
=> fix: remove searched for message in lspinfo

lua/lspconfig/server_configurations/emmet_ls.lua
Adds `eruby` support to the `emmet_ls` server configuration so that `*.html.erb` can get completions.
=> feat: add eruby to emmet_ls

lua/lspconfig/util.lua
fix https://github.com/neovim/nvim-lspconfig/issues/2285
=> fix(lsp): use the same lsp server for filetype if it exists

plugin/lspconfig.lua
Problem: `client.stop` is an async function we should not use `defer_fn` with a hardcode time number 500.
Solution: use uv timer to check the client is stopped or not, after all clients are stopped then launch them.
Fix #2289
=> fix: restart client after client is stopped after LspRestart

lua/lspconfig/server_configurations/starlark-rust.lua
This uses the github name and not the cargo name as it is not so official and may be replaced by a better LSP. So the name is not already taken by this linter.
=> feat: add 'starlark-rust' LSP for starlark and BUILD files

plugin/lspconfig.lua
Problem:  currently check logic a little stupid
Solution: we can check the current buffer in client attached_buffers field or not
=> fix: improve client stop logic in LspStop

lua/lspconfig/ui/lspinfo.lua
Problem: neovim master had remove the `workspaceFolders` field ref https://github.com/neovim/neovim/commit/50ffb8d7f4d9e1b080efbf5eb04595f0399db9e5
Solution: check the neovim version
Fix #2299
=> fix: check workspae folders follow nvim version

lua/lspconfig/util.lua
Problem: the clients cache the client id with root dir.
Solution: get the client id from value and valid the client.
Fix #2302
=> fix: check client is available and get client id from cache

lua/lspconfig/ui/lspinfo.lua, lua/lspconfig/util.lua
if client already in `single_file_clients`, when open a new file in project . we should check the client in `single_file_clients`. then don't spawn a new server instance.  with `single_file` mode the client not initialize the `workspace_folders` field , so 
initialize this field.  then insert the project to `workspace_folders ` . 
now we don't spawn multiple clients , just use one client instance with muliple workspace folders. check the current buffer file in the project or not. and show the correct project dir in `LspInfo`, 
remove pid in `LspInfo` . the `client.rpc.pid` had removed
=> feat: support multiple workspaceFolders and show correct root in Lspinfo

lua/lspconfig/util.lua, plugin/lspconfig.lua
Problem:   when `LspStart` without any argument it will launch the server which not in active even the filetypes match the 
current buffer .
Solution:  currently we support client with multiples workspaceFolders , it don't spawn another server instance . so no need 
use `get_other_matching_config` function .just get all matched config then launch them. 
Fix #2312
=> fix: run all matched client in LspStart

nvim_lspconfig-scm-1.rockspec
nvim-lspconfig is a common dependency across Neovim plugins. Using luarocks may alleviate the need for users to specify their plugins' dependencies in their plugin manager.
(e.g., vim-plug or packer).
See also:
https://teto.github.io/posts/2021-09-17-neovim-plugin-luarocks.html
=> feat: add rockspec

lua/lspconfig/ui/lspinfo.lua
The filename of a buffer may point to a node on the file system that
does not yet exist. `uv.fs_realpath()` will return nil in these cases,
causing a nil exception later on. The builtin `resolve()` function will
return the provided filename as-is if it does not yet exist.
Alternatively we could stick to libuv APIs.
=> fix(lspinfo): safely expand filenames that don't exist on fs

lua/lspconfig/server_configurations/gdscript.lua
support get the port number from env variable `GDSript_Port`
Fix #2311
=> fix(gdscript): support get the port from env variable

lua/lspconfig/server_configurations/volar.lua
`languageFeatures` and `documentFeatures` options have been deprecated since @volar/vue-langauge-server v1.0.0, you can check released information at:
- https://github.com/johnsoncodehk/volar/pull/1916
- https://github.com/johnsoncodehk/volar/issues/2046#issuecomment-1287825923
=> refactor: simplify init options for @volar/vue-langauge-server v1.0

lua/lspconfig/server_configurations/tsserver.lua
=> fix: correct link of typescript-language-server

lua/lspconfig/util.lua
The design here is a bit wired. It stores clients in categories. It is possible to reuse the language server through the workspace. There is no need for classified storage. And the logic here is a bit long-winded. You only need to judge whether root_dir is in the clients table. If in we return the existing client. If not find all stored clients. If there is a client that needs it and supports workspace. Then return directly to this client. Then insert root into the workspace field. Trigger `didChangeWorkspaceFolders`. For non-existent we start new client.
=> refactor: remove single_clients and improve clients reuse

lua/lspconfig/util.lua
I got an error like below (this error seems to be introduced by this PR: https://github.com/neovim/nvim-lspconfig/pull/2334):
```
Error executing lua callback: ...path/to/nvim-lspconfig/lua/lspconfig/util.lua:246: attempt to index field 'server_capabilities' (a nil value)
```
This PR fixes this error by adding `nil` check for `client.server_capabilities`.
=> fix: check server_capabilities field exist

lua/lspconfig/util.lua
we should not use  field in `server_capabilities` to check the server support workspace folders or not
use `client.support_method` to check
Fix #2349
=> fix: check client support workspaceFolders

lua/lspconfig/util.lua
not all the clients have the field `supports_method`
add a field check
=> fix: check client exist supports_method

lua/lspconfig/util.lua
when there has another server request the before server may not have the `server_capabiliese` and `supports_method`. 
maybe we can use client capabilties.
Fix #2353
=> fix: use client config capabilities to check server support workspace

lua/lspconfig/util.lua
1. the `removed` should be an empty table not table which have an empty list element.
2. some server support `workspaceFolders` but the it not show in server_capabilities. 
1. remake params
2. currently assuming the server supports workspaces. no judgment
Fix #2360
Fix #2357
=> fix: generate correct workspace didchange request params

plugin/lspconfig.lua
`get_active_clients` function params is bufnr not buffer
change buffer to bufnr
=> fix: wrong param in get_active_clients

lua/lspconfig/util.lua
currently `clients` table store client for each  root dir.
add iterator for client ids for each root dir
=> fix: get all client from clients cache in manager.clients

lua/lspconfig/configs.lua, lua/lspconfig/util.lua
if file in single file mode after client initialized not register into the workspace
=> fix: not register workspace when in single file mode

lua/lspconfig/server_configurations/ruff_lsp.lua
`ruff-lsp` currently uses `init_options` and doesn't support settings. (I'll probably fix this, but for now the docs are incorrect.)
=> fix(ruff-lsp): update docs to reflect init_options

lua/lspconfig/server_configurations/arduino_language_server.lua
Currently the `arduino_language_server` doesn't run without passing custom configuration options to `setup`.
If an Arduino project is contains `sketch.json` file all but the `cmd` option can be omitted. As this stays the same it would be nice to move it into this repository. This also has the advantage of keeping project specific settings inside the project and not in the nvim config.
I've done the above and updated the docs with a minimal guide to setting up an Arduino project.
This is working on my machine `require("lspconfig").arduino_language_server.setup()` but it would be good if others could test it.
=> feat: include cmd option for arduino_language_server

lua/lspconfig/server_configurations/tsserver.lua
Set `single_file_support` for tsserver to true by default, as typescript-language-server supports single-file mode.
=> feat(tsserver): set `single_file_support` to true

.github/workflows/release.yml, Makefile, scripts/luarocks-upload.sh, scripts/test-luarocks-install.sh
The recently added rockspec (see #2307) has to be prepared and uploaded to luarocks for each release.
This adds an automated workflow for it, which has been tested with plenary.nvim.
To be able to upload to luarocks, the owner of the luarocks account will have to add an API key named `LUAROCKS_API_KEY` to this repo's GitHub Actions secrets.
=> ci: add luarocks upload release workflow

lua/lspconfig/server_configurations/openscad_lsp.lua
This server is a fork of sorts of the `openscad_ls` server that is
already supported by nvim-lspconfig. I have no insight into either
projects, but the `openscad-lsp` Cargo package seems to be more
actively maintained, see:
- `openscad_ls`: https://github.com/dzhu/openscad-language-server
- `openscad_lsp (this pr)`: https://github.com/Leathong/openscad-LSP
=> feat: add openscad_lsp

lua/lspconfig/ui/lspinfo.lua, plugin/lspconfig.lua
this is useful  for user to check the server doc in neovim when there is something wrong in server .
=> feat: support show server doc description in LspInfo

lua/lspconfig/server_configurations/drools_lsp.lua
This PR adds support for Red Hat's [Drools Rule Language](https://docs.drools.org/latest/drools-docs/docs-website/drools/language-reference/index.html#con-drl_drl-rules) (ft=`drools`, ext=`.drl`). The [drools-lsp](https://github.com/kiegroup/drools-lsp/) server is still under development, but it does have basic working capabilities, and I have successfully tested it (with this PR) in a minimal/vanilla neovim init config. Having this server configuration in nvim-lspconfig would enable developers to more easily develope DRL, **and** furthering the development and testing of the drools-lsp server itself.
Note: As soon as this PR gets merged, I will be submitting PRs to the mason.nvim repo ([diff](https://github.com/williamboman/mason.nvim/compare/main...errantepiphany:mason.nvim:DROOLS_LSP)) …
=> feat: add drools-lsp support

lua/lspconfig/util.lua
rewrite the spawn the server instance logic. 
`clients`  cache the server instance id with root , key is root dir value is all clients id which attached this root dir .
1.  find the client from `clients `
2. if find exist client check this client support `workspaceFolders` by 
`vim.tbl_get(client, 'server_capabilities', 'workspace', 'workspaceFolders', 'supported')` if true mean client support 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders
3.  otherwise spawn a new one.
notice there has a timer for some situation .like load from session .
=> fix: check server supported workspaceFolders

lua/lspconfig/ui/lspinfo.lua
set the lspinfo buffer `bufhidden` to `wipe`. close window will remove this buffer.
Fix #2423
=> fix: lspinfo buffer in use when use quit command close

lua/lspconfig/server_configurations/omnisharp.lua
cc @williamboman since you seem to be familiar with omnisharp, just making sure this is a correct info
I just tried omnisharp and go to definition doesn't work without the linked extension
=> Add go_to_definiton information for omnisharp

lua/lspconfig/server_configurations/ltex.lua
latex does not recognise `pandoc` as file format. This PR handles it as markdown.
=> Pass 'pandoc' as 'markdown' to ltex-ls

.github/workflows/release.yml
@teto this version escapes quotes in the description: (https://github.com/neovim/nvim-lspconfig/pull/2430#issuecomment-1418286733)
I also added a license field, because GitHub doesn't seem to recognize it.
=> fix: update luarocks-tag-release action + set license

lua/lspconfig/server_configurations/cadence.lua
Add the Cadence Language Server.
If `cdc` file detection isn't working the following config fixes that:
```lua
vim.filetype.add({
extension = {
cdc = "cdc",
}
})
```
Or switch to a neovim version which includes https://github.com/vim/vim/pull/11951.
=> Add Cadence Language Server

lua/lspconfig/server_configurations/powershell_es.lua
The current configuration for powershell-editor-services does not allow for a whitespace in any of the paths.
=> fix(powershell_es): Support whitespace in paths

LICENSE.md, README.md
I noticed that GitHub can't parse the license SPDX ID form the license file. So I moved the copyright notice above the license text to the bottom of the readme.
=> chore(license): move copyright notice to readme

lua/lspconfig/server_configurations/eslint.lua
Creating a buflocal autocmd on attach is more useful, IMO, cause it guarantees the command will only be executed on buffers that support it. I found myself many times editing js or ts files outside of a project using eslint and would get an error on save because of the autocmd on the documentation.
Hopefully it helps others!
=> docs(eslint): fix on save example creates a buflocal autocmd

lua/lspconfig/server_configurations/eslint.lua, lua/lspconfig/server_configurations/stylelint_lsp.lua, lua/lspconfig/util.lua
Hi! dear maintainers - this little contribution is to extend the `root_pattern` lookup by supporting all [StyleLint config files](https://stylelint.io/user-guide/configure/) and based on the [eslint.lua](https://github.com/neovim/nvim-lspconfig/blob/aeb76066212b09c7c01a3abb42fe82f0130ef402/lua/lspconfig/server_configurations/eslint.lua) method.
Signed-off-by: Wuelner Martínez <wuelner.martinez@outlook.com>
=> fix(stylelint_lsp): update root directory pattern

lua/lspconfig/util.lua
Looks like there was a subtle change in logic in the `insert_package_json` util that was causing the function to return `nil` (introduced here https://github.com/neovim/nvim-lspconfig/commit/6669f2d8ebc38cfb9e639145569f94be5556d916). I'm not sure if it's something specific to my neovim version:
```
➜ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
Features: +acl +iconv +tui
```
Reverting to previous logic fixes it for me.
=> fix: eslint errors on start

lua/lspconfig/ui/lspinfo.lua
replace \k with \S
support e.g., null-ls
=> feat: extend the syntax for LspInfo(Title|List)

lua/lspconfig.lua
this function mark as deprecate in 0.1.4
use util.available_servers instead of
=> fix: remove deprecate function config.available_servers

lua/lspconfig/ui/lspinfo.lua
`vim.fn.fnamemodify` and `vim.fn.resolve` doesn't normalize slashes in Windows paths, which can cause `:LspInfo` to falsely report that the current attached client is in single file mode.
As far as I know `uv.fs_realpath` does everything that `vim.fn.fnamemodify(..., ":p")` and `vim.fn.resolve` can do and more, so I removed them.
=> fix(lspinfo): normalize `fname` path correctly

scripts/docgen.lua
The documents previously contained `runner`, the username of GitHub Actions runners, which would be overwritten by the user's name when run locally and generate unwanted diff.
=> docs: make sure username doesn't leak into generated document

plugin/lspconfig.lua
`LspStop` only working like:
```
:LspStop (1)
```
putting `id` between parenthesis.
=> fix(commands): Strange `LspStop` arguments, not matching doc

lua/lspconfig/server_configurations/tailwindcss.lua
Clojurescript is another filetype that can use tailwindcss lsp completion, given the following lsp configuration:
```
tailwindcss = {
settings = {
tailwindCSS = {
experimental = {
classRegex = {
":class\\s+\"([^\"]*)\"",
":[\\w-.#>]+\\.([\\w-]*)"
},
},
includeLanguages = {
clojure = "html"
},
},
},
},
```
=> fix: add clojure to tailwindcss lsp filetypes

lua/lspconfig/server_configurations/azure_pipelines_language_server.lua, lua/lspconfig/server_configurations/azure_pipelines_ls.lua
This adds [microsoft's fork of yamlls](https://github.com/microsoft/azure-pipelines-language-server) which supports their custom parsing of some data values in their json specs providing better support for azure pipelines.
- Added `azure-pipelines-language-server`
- Ensured lint style followed via running `stylua **/*.lua && luacheck **/*.lua` in the repository
This accompanies a PR to mason.nvim: [williamboman/mason.nvim#1604](https://github.com/williamboman/mason.nvim/pull/1064)
The full name of the lsp server is quite bulky, being `azure_pipelines_language_server`, and may need a renaming for users, maybe `azure_pipelines_lsp`?
I have tested and verified the server works on Linux with Neovim nightly, `NVIM v0.9.0 dev-1135+g419819b62`.
Config as passed to `lspconfig`:
```lua
local …
```
=> feat: add azure pipelines lsp

lua/lspconfig/server_configurations/gdscript.lua
Godot 4 changed its default port. Since Godot 4 reached stable a few days ago, we should propose the stable version's port by default.
=> feat: support Godot 4 port by default

lua/lspconfig/server_configurations/arduino_language_server.lua
=> docs(arduino): mention upstream keywords bug

lua/lspconfig/ui/lspinfo.lua
api `nvim_set_option_value` not works on low neovim version.
close #2499
=> fix(lspinfo): set the lspinfo bufhidden to wipe

lua/lspconfig/server_configurations/ecsact.lua
Hi! I've developed and maintain a project called Ecsact. We've made an LSP server for our language and I'd love to include it in nvim-lspconfig as I am a big neovim user myself!
=> feat: add ecsact support

lua/lspconfig/server_configurations/rust_analyzer.lua
Non-empty default settings trigger a workspace/didChangeConfiguration, potentially overwriting the initial settings.
Move this example content into the description instead.
=> fix(rust_analyzer): remove stub settings from default

lua/lspconfig/server_configurations/vls.lua
Currently, there is a little conflict when working with `.v` filetypes between treesitter and nvim-lsp.
Treesitter will highlight files of file-type `v` while vls is requires filetype `vlang`. Instead of working around this issue i thought adding `v` as filetype is a proper solution.
I'll extend this request to related repos like mason if this is going to be merged.
=> fix(vls): add `v` as filetype

lua/lspconfig/server_configurations/graphql.lua
The GraphQL language server needs a configuration file to initialise and the `graphql` package from NPM. Rooting on `.git` alone causes this server to repeatedly try opening and then close for each matching file type when it cannot find the config it is looking for.
See: https://the-guild.dev/graphql/codegen/docs/getting-started/installation#global-installation
=> fix(graphql): fix crash on projects without graphql

lua/lspconfig/server_configurations/clojure_lsp.lua
This adds supports for clojure lsp correctly setting the project root for Babashka only projects.
[Babashka](https://babashka.org/) is a widely used, fully featured, native clojure runtime intended for fast start up and scripting. Clojure LSP has full support for it and this should make it a easier for people using the [project setup](https://book.babashka.org/#project-setup).
=> fix(clojure_lsp): add support for babashka only projects

lua/lspconfig/server_configurations/bashls.lua
As suggested by upstream, see bash-lsp/bash-language-server#599
> Environment variable configuration is being deprecated, please use workspace configuration.
=> refactor(bashls): migrate to a workspace config

doc/server_configurations.md, doc/server_configurations.txt, lua/lspconfig/server_configurations/pyright.lua
The new command accepts a single path for a python executable that will be used to reconfigure the pyright language server. This is useful to change which python will be used by pyright without having to activate the python environment beforehand. The act of finding which python executable to use isn't handled here.
=> feat: add PyrightSetPythonPath command to pyright config

lua/lspconfig/util.lua
Problem: workspace settings aren't shared until the buffer is refreshed
Solution: register/update workspace folders _before_ attaching to the buffer
- open `lua/lspconfig/configs.lua`
- open another lua file in a different directory/workspace
- see how the workspace settings, e.g. `require` is a global keyword, are shared immediately without
the need to refresh/re-enter the buffer (`:e`)
=> fix: register workspace before attaching to buffer

lua/lspconfig/server_configurations/pyright.lua
According to the official setting document, the default value of `python.analysis.useLibraryCodeForTypes` should be `false`. See [pyright/docs/settings.md](https://github.com/microsoft/pyright/blob/main/docs/settings.md)
When this option's value is true, it will significantly affect the completion speed of the code, and I hope to merge it as soon as possible.
=> fix(pyright): set `useLibraryCodeForTypes` to false

lua/lspconfig/server_configurations/pyright.lua
Reverts neovim/nvim-lspconfig#2522
=> Revert "fix(pyright): set `useLibraryCodeForTypes` to false"

.github/workflows/release.yml
It should no longer be needed as per
https://github.com/neovim/nvim-lspconfig/pull/2527#issuecomment-1484563558.
=> ci: remove copy_directories input from luarocks-tag-release action

lua/lspconfig/server_configurations/nil_ls.lua
Unlike `rnix` that configure to use `nixpkgs-fmt` by default `nil` doesn't set it up by default which requires explicit setting which would be helpful to see the example config to set it correctly, hence the link.
```lua
-- ...
settings = {
['nil'] = {
formatting = {
command = { 'nixpkgs-fmt' }, -- default is nil
},
},
},
-- ...
```
=> docs(nil_ls): add a link to an example

lua/lspconfig/server_configurations/dafny.lua
Dafny now ships with the language server, so a default `cmd` can be provided that will work out of the box if you have the latest version.
=> fix(dafny): add default cmd for Dafny 4

lua/lspconfig.lua, lua/lspconfig/configs.lua, lua/lspconfig/server_configurations/sqls.lua
[sqls](https://github.com/lighttiger2505/sqls) has been archived. 
add `deprecate` field in sqls config and show a notify when register this server to lspconfig and suggest use sqlls instead of.
Fix #2530
=> fix(sqls): deprecate sqls suggest sqlls instead

lua/lspconfig/server_configurations/arduino_language_server.lua
arduino_language_server crash after the merge of [#21100](https://github.com/neovim/neovim/pull/21100) in neovim.
Disabling semantic tokens capabilities fix this issue.
I tested this changes on v0.8.4 release branch and  v0.9.0-dev-1295 master branch.
=> fix(arduino_language_server): disable semantic tokens for arduino_language_server

lua/lspconfig/server_configurations/emmet_ls.lua
Adds `astro`, `svelte` and `vue` support to the `emmet_ls` server configuration so that `*.astro`, `*.svelte` and `*.vue` can get completions.
(also I've sorted the filetypes)
=> feat: add astro,svelte and vue to emmet_ls

lua/lspconfig/configs.lua
currently add on_attach function inside the `vim.schedule` function this may break the `semantic_token` request 
remove `vim.schedule` wrap 
Fix #2542
=> fix: remove vim.schedule for on_attach

README.md
Problem: code_action support in visual more , this is missing in readme example config
Solution: add visual mode in example config.
=> docs: add visual mode in vim.lsp.buf.code_action section

lua/lspconfig/server_configurations/eslint.lua, lua/lspconfig/util.lua
Problem: currently root patterns `package.json` file only check once. 
Solution: should check by given path when try to start server.
Fix #2554
=> fix(eslint): get root patterns by given path

lua/lspconfig/server_configurations/helm_ls.lua
Loading helm files currently fails with this error:
```
Error executing lua callback: /usr/share/nvim/runtime/lua/vim/lsp.lua:239: cmd argument: expected string, got table
```
This is caused by `cmd` being set to `{ { 'helm_ls' }, 'serve' } }` instead of `{ 'helm_ls', 'serve' }`.
=> fix: bad helm_ls cmd

README.md
we should not add any third-part plugin in doc. because they are always replaced over time.
=> docs: remove plugin manager
