lua/lspconfig/ui/lspinfo.lua
sub `fname` from 1 to root_dir len then do match. this is simple than before match check.
=> fix(lspinfo): sub fname to check root

lua/lspconfig/server_configurations/custom_elements_ls.lua
Heya!
I've authored and released a Custom Elements Language Server into it's Alpha stage yesterday (https://github.com/Matsuuu/custom-elements-language-server) .
I've been making it support Neovim and VSCode and have run both in my dev environments and testing. 
It'd be great to have this supported on nvim-lspconfig level to increase ease of adoption.
Base of the config taken from the tsserver setup, modified to support this approach
=> feat: add custom elements language server support

lua/lspconfig/server_configurations/golangci_lint_ls.lua
I think it would be good if root_pattern looked for all supported [config files](https://golangci-lint.run/usage/configuration/#config-file)
=> fix(golangci_lint): root_pattern should look for all supported cfg files

lua/lspconfig/server_configurations/sourcery.lua
Sourcery [released support for Javascript and Typescript](https://sourcery.ai/changelog/2023-04-14-2023-04-14/). So it makes sense to add those languages to the filetypes.
=> feat: allow sourcery for JS filetypes

lua/lspconfig/server_configurations/nim_langserver.lua, lua/lspconfig/server_configurations/nimls.lua
=> feat: Add support for the other nim language server

lua/lspconfig/server_configurations/remark_ls.lua
- Make `root_dir` more restrictive
The problem currently is that every time I type a _single character_, this message pops up aggressively and it switches focus to the pop-up: https://github.com/unifiedjs/unified-language-server/blob/4380a0ffbab401d42e679d2c620aa5b042cfc319/lib/index.js#L201-L210
There is no way to stop this. I have to run `:LspStop remarkls` manually in projects that have markdown but don't use remark (which is most projects).
Instead, we look for actual configuration files and only start the LS if they are present. The downside is that remark can also be configured in `package.json`, which wouldn't work with this change (would have to be documented)
- Remove the warning in `unified-language-server`.
- Only show the warning once. As this warning is triggered in the …
=> remarkls: make `root_dir` more restrictive

lua/lspconfig/configs.lua
I think only table need to expand
only allow table to expand. this will still allow `vim.lsp.rpc.connection`  to work
=> fix: vim.lsp.rpc.connect is not allowed in cmd

lua/lspconfig/server_configurations/rust_analyzer.lua
Updated the link to the `rust-analyzer` repo to the current location. Also, updated the link to the settings reference. The current link only takes us to the folder and not to any specific file.
=> Docs: Update links in `rust_analyzer`

lua/lspconfig/configs.lua
`exepath` just work with `cmd[1]` so should check cmd not empty.
Fix #2601
=> fix: check cmd not empty

lua/lspconfig/server_configurations/eslint.lua
https://github.com/eslint/eslint/commit/7162d34df9a66c817c3bd4aafd3a03d226b58dd5
ESLint's new config system is complete, this PR offers auto-detecting of the new config file in the project root, then set the `experimental.useFlatConfig = true` to enable it automatedly.
=> feat: auto detect the `eslint.config.js` file to enable flat config support

lua/lspconfig/server_configurations/texlab.lua
Since Texlab v5.5.0, `textDocument/build` accepts `position` argument, which is going to be used if forwardSearchAfter is enabled. Using Texlab <5.5.0 it's not an issue, the argument gets skipped and no error is thrown. Same happens if forwardSearchAfter is not enabled.
=> feat(texlab): send position when building

lua/lspconfig/server_configurations/sourcekit.lua
=> fix(sourcekit): add buildserver.json and compile_commands as root pattern

lua/lspconfig/server_configurations/ruby_ls.lua
Without the `enabledFeatures` init option, ruby lsp would enable all the supported features. This change was introduced in https://github.com/Shopify/ruby-lsp/pull/562
=> fix: ruby lsp features should be opt-out

lua/lspconfig/server_configurations/unocss.lua
:wave: A simple fix, UnoCSS last month decided to change the config filename from `unocss.config.js`/`unocss.config.ts` to `uno.config.js`/`uno.config.ts` so I added them to the root pattern matches.
I am trying to understand why this change has been made, [the commit](https://github.com/unocss/unocss/commit/174381f73cb56943f7343fb2392c484edec32d1e) itself doesn't explain why this change has been made and according to [the docs](https://unocss.dev/guide/config-file) both files are supported by default so I think that supporting both is the right call.
=> fix(unocss): detect also uno.config

lua/lspconfig/server_configurations/zk.lua
Commands description for all servers allways start with the name of the server. Keep it consistent in zk.
See <https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md> and `<ctrl-f>Commands:` to verfied that all commands start with server name.
=> docs(zk): consistent commands description

lua/lspconfig/server_configurations/pest_ls.lua
Adds support for [pest-language-server](https://github.com/pest-parser/pest-ide-tools). Towards https://github.com/pest-parser/pest-ide-tools/issues/10
=> feat: add pest_ls support

lua/lspconfig/server_configurations/blueprint_ls.lua
The blueprint-compiler doesn't have a "start" subcommand. And the condition in the cmd was incorrect as in lua any number, including 0, is truthy meaning it was always executing `blueprint-compiler start`, which is incorrect and thus blueprint_ls was unusable.
=> fix(blueprint_ls): remove non-existent subcommand

lua/lspconfig/server_configurations/astro.lua
`@astrojs/language-server@2.0.0` utilizes Volar language server under the hood. The LSP's init_options are located [here][1]. `typescript.serverPath` has been renamed to `typescript.tsdk`. There is no `configuration`; that option is for the VSCode extension, located in the `astro-vscode` package [here][2].
[1]: https://github.com/volarjs/volar.js/blob/dfc8ccefb6c3aa53bd0eb9755259538a11127edd/packages/language-server/src/types.ts#L50
[2]: https://github.com/withastro/language-tools/blob/eb2ce0b3effd00e49294be57ef0f3d1cb5f8f454/packages/vscode/package.json#L126
=> fix(astro): update astro config for @astrojs/language-server v2.0.0

lua/lspconfig/server_configurations/astro.lua
It's supposed to be a path to the TypeScript server folder, not a file.
Astro LSP should work now. Tested it this time.
Fixes https://github.com/withastro/language-tools/issues/559
=> fix(astro): correct the typescript.tsdk path

lua/lspconfig/server_configurations/rust_analyzer.lua
register `serverStatusNotification` capability . `rust analyzer` custom notify method called `experimental/serverStatus`. useful to show rust_analyzer status on statusline. usage  on config . need create a lsp handler for this method like this 
```lua
vim.lsp.handlers['experimental/serverStatus'] = function(_, result)
print('Received serverStatus notification:', vim.inspect(result))
end
```
output of this method will be like
```
Received serverStatus notification: nil
Received serverStatus notification: {
health = "ok",
quiescent = false
}
Received serverStatus notification: nil
Received serverStatus notification: {
health = "ok",
quiescent = true
}
```
Ref doc https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#server-status
=> feat(rust_analyzer): register serverStatus capability

lua/lspconfig/server_configurations/vtsls.lua
Extra backticks in the description cause the `server_configurations.md` to look like this
After the fix
=> fix(vtsls): remove extra backticks in description

lua/lspconfig/server_configurations/tailwindcss.lua
Also consider `.mjs` and `.cjs` extensions in Tailwind CSS language server's `root_pattern`.
=> feat: consider .mjs and .cjs in tailwindcss root_pattern

plugin/lspconfig.lua
problem:  `LspRestart` recoard all active clients then restart them. 
solution:  restart client which `attached_buffers`  is empty 
Fix #2668
=> fix: lsprestart only restart client which have attached buffer

lua/lspconfig/configs.lua, plugin/lspconfig.lua
Problem:  Now LspRestart call `launch` it use current buffer 
Solution: make it receive buffer param then new client attached before buffers
Fix #2670
=> fix(command): LspRestart should attached before buffers

lua/lspconfig/server_configurations/rust_analyzer.lua
When checking if file is part of a library, use `RUSTUP_HOME` env variable if it is set, in the same way as `CARGO_HOME`.
=> fix(rust_analyzer): use RUSTUP_HOME in library check

lua/lspconfig/server_configurations/ember.lua
As an aside, I need to add a second root_dir pattern -- is there a way to have two root_patterns?
or is that what the args are in util.root_pattern? if first not found, use second?
=> Add support for gjs and gts files for the ember language server

lua/lspconfig/server_configurations/rubcop.lua
=> feat: add rubocop support

lua/lspconfig/server_configurations/volar.lua
A URL pointing to specific configuration necessary for older Vue.js versions got moved (see ) updated the link here to reflect the change
=> docs: update broken link volar (vue.js)

lua/lspconfig/server_configurations/rubocop.lua
The  existing rubocop lsp configuration uses the 'bundle exec' command as a prefix to run rubocop.
This is the correct way to do it for projects using the bundler gem (including all rails projects.)
However that configuration is broken for ruby projects not using bundler.  The LSP fails to start and an error message is shown on startup.  
This PR makes the default configuration work for either case, by detecting whether bundler is in use and using the correct command.
=> fix(rubocop) support projects that do not use bundler

lua/lspconfig/server_configurations/rubocop.lua
My earlier PR #2706 added an on_new_config handler which auto-detects whether bundler is used in a project, and calls rubocop through bundler or not based on the result.
This had some issues:
* may override the user's custom configuration due to the use of on_new_config
* has surprising side effect when overridden because the `on_new_config` handler runs twice
* incorrectly configures 'bundle exec rubocop --lsp' command if the project has a Gemfile that does not include rubocop
After some [discussion](https://github.com/neovim/nvim-lspconfig/pull/2706#issuecomment-1627767073)  it seems that this simpler configuration is best.
This PR deletes the `on_new_config` handler, leaving the lsp command to be `rubocop --lsp`.
This will also match the behaviour of the solargraph and ruby_ls …
=> fix(rubocop): don't auto-detect bundler, to avoid surprising configuration behavior

lua/lspconfig/server_configurations/pyright.lua
This behavior is more natural and the default in VS Code: https://github.com/microsoft/pyright/issues/5407#issuecomment-1619132310.
=> Update pyright.lua to use `cwd()` if no python config files are present.

lua/lspconfig/server_configurations/emmet_ls.lua
Adds  `javascript` support to emmet_ls as it was missing and emmet_ls implemented support for it (as seen in https://github.com/aca/emmet-ls#supported-filetypes)
=> feat: add `javascript` to emmet_ls

lua/lspconfig/server_configurations/pyright.lua
Notice this sensible default is missing from pyright when creating new python project.
=> fix(pyright): add `.git` to list of root file

plugin/lspconfig.lua
Problem: `attached_buffers` not list-like table should not use `#` for length check
Solution: use `vim.tbl_count`
Fix #2707
=> fix(LspRestart): check client attched_buffers count by using tbl_count

lua/lspconfig/server_configurations/pyright.lua
fname was missing from arguments, leading to always using cwd.
=> fix(pyright): Fix root_dir detection

README.md, doc/lspconfig.txt
Add changes from #2514 to vimdoc. Better late than never. Also fix `lsp-config` links, it's `lspconfig`
=> docs: make vimdocs consistent with readme

lua/lspconfig/server_configurations/rust_analyzer.lua
Problme: when open a library file directly there is no active clients will cause an error
Solution: check clients is empty or not 
Fix #2681
=> fix(rust_analyzer): check active clients is empty

doc/lspconfig.txt
According to https://github.com/neovim/neovim/commit/c618b314c6a266806edf692122b16ba9ff7a8e10
=> docs: rename deprecated `resolved_capabilities` -> `server_capabilities`

lua/lspconfig/server_configurations/lua_ls.lua
See: https://github.com/neovim/neovim/pull/24592
- Only override settings if there is no `.luarc.json(c)` file present.
- Prefer setting workspace to `VIMRUNTIME` over `'runtimepath'`
=> feat(lua_ls): update recommended settings

lua/lspconfig/server_configurations/volar.lua
The npm package `@volar/vue-language-server` has been renamed to `@vue/language-server`.
Therefore, I have corrected the NPM package name for volar in the documentation.
The source code is not changed by this pull request.
Ref: https://www.npmjs.com/package/@volar/vue-language-server
=> chore(volar): rename npm package name `@volar/vue-language-server` to `@vue/language-server`

lua/lspconfig/server_configurations/omnisharp.lua
There was a regression in `root_dir` for omnisharp caused by https://github.com/neovim/nvim-lspconfig/pull/2715
See https://github.com/neovim/nvim-lspconfig/pull/2715#issuecomment-1652774935 for a good problem explanation.
This MR implements pattern priority left-to-right which fixes the issue.
=> fix(omnisharp): root_dir again uses proper pattern priority

lua/lspconfig/server_configurations/lua_ls.lua
Small PR that updates links for the [lua language server](https://github.com/luals/lua-language-server) to point to the new wiki that is replacing the old GitHub wiki.
=> lua_ls: Update links to refer to new wiki

lua/lspconfig/server_configurations/emmet_ls.lua
Reverts neovim/nvim-lspconfig#2720
As pointed out by @TheBlckbird in #2720 , the original PR was more annoying than helpful to the majority of users, so including `javascript` 
in `emmet_ls` should remain optional.
=> Revert "feat: add `javascript` to emmet_ls"

lua/lspconfig/server_configurations/rust_analyzer.lua
The configuration for `rust_analyzer` in this plugin sets up a command `CargoReload` that calls an internal function `reload_workspace`. This function had the same problem as the function of the same name in `rust-tools.nvim` (see simrat39/rust-tools.nvim#267 and simrat39/rust-tools.nvim#410). I've applied the same fix I did here as I did there.
=> Fix `CargoReload` sending RPC requests to unrelated LSP clients

lua/lspconfig/util.lua
=> fix: lsprestart command faild

lua/lspconfig/server_configurations/biome.lua
`rome` is unmaintained, and `biome` is the new fork/successor: https://biomejs.dev/blog/annoucing-biome
Since `biome` is mostly a clone of rome at this point, not much changed other than the name. The announcement also confirms that for now, it's basically just a package name change which I adopted.
I tested the branch, and the config works just fine for `biome`.
I also ran `make lint`, and added a short notice that `rome` is unmaintained.
=> feat: add `biome` (`rome` successor)

lua/lspconfig/server_configurations/jedi_language_server.lua
Similar to #2722 . Detect .git as project root.
=> fix(jedi): add .git to jedi_language_server root_dir

lua/lspconfig/server_configurations/pyright.lua
When you go to definition of a library function, pyright will analyze the entire packages to report diagnostic information. This is extremely slow and heavy https://www.reddit.com/r/neovim/comments/135fqp9/why_is_pyright_constantly_analyzing_files_it/ Switch to the default value, similar to in VSCode.
Changing this setting does not affect the type inference from library code, does not affect the diagnostic of the opened files from user or library code.
As far as I know, "openFilesOnly" only report diagnostic information for the file you have opened, i.e workspace diagnostics won't report for files you have not opened in this session.
This seems like an acceptable tradeoff for me.
P/s: Or considering delete everything analysis setting to use the default value. This will keep it in sync …
=> fix(pyright): set diagnosticMode = openFilesOnly

lua/lspconfig/server_configurations/ccls.lua
I used to use clangd as my language server, and today I changed to ccls. However, I found that ccls did not offer support to cuda.
In the configuration of clangd, the cuda filetype is added by default. So maybe it is better for ccls to support cuda by default?
=> fix(ccls): add cuda filetype support

lua/lspconfig/server_configurations/denols.lua
same as the vscode extension https://github.com/denoland/vscode_deno/blob/abd33d2edcf752d69e0c53f244ee549a04a6eba5/package.json#L247
`init_options` fails, it needs to be `settings = {deno`
Also I removed the `unstable = false`, since that is the default
=> feat(denols): enable import completion from registries

lua/lspconfig/ui/lspinfo.lua
Functions prefixed with _ should not be used, as they have no stability
guarantees from Nvim and can be removed at anytime with no warning or
replacement. _trim was such a function that was recently removed.
=> fix: remove usages of private (now deprecated) functions

lua/lspconfig/server_configurations/solidity_ls_nomicfoundation.lua
All are supported according to the LSP's documentation.
`single_file_support`: https://github.com/NomicFoundation/hardhat-vscode/blob/development/server/README.md#neovim-lsp
`root_dir`: https://github.com/NomicFoundation/hardhat-vscode/blob/development/server/README.md#project-support
Have also tested by setting my [lazy](https://github.com/folke/lazy.nvim) config to:
```
{
"llllvvuu/nvim-lspconfig",
branch = "feat/solidity_ls_nomicfoundation_singlefile",
}
```
=> feat(solidity_ls_nomicfoundation): add single_file_support and supported frameworks

lua/lspconfig/server_configurations/robotframework_ls.lua
When using the default configuration with robots created using templates available in [`rcc`](https://robocorp.com/docs/rcc/overview), I realized that the root directory was not identified. As a quick fix, I created an empty `pyproject.toml` file in the project root. However, that file must be manually created for (at least many) new projects, so updating the default configuration seems reasonable.
I believe `robot.yaml` and `conda.yaml` can be added to the filename list when looking for the project root directory.
I used `rcc create` with all of the available templates:
```
Templates:
1: Python - Assistant AI Chat
2: Python - Browser automation with Playwright
3: Python - Minimal
4: Python - Producer-Consumer
5: Robot Framework - Assistant (attended automation)
6: Robot Framework - …
```
=> fix(robotframework_ls): update root directory pattern

lua/lspconfig/server_configurations/texlab.lua
$HOME/.latexmkrc is per-user config, so it shouldn't be prioritized over closer directory containing .git.
=> fix(texlab): don't overly prioritize .latexmkrc

lua/lspconfig/server_configurations/perlls.lua
Current version is 2.6.1. It is not needed at all to run the server, and most people have only one version installed at a time. Also updating this argument is tedious every time richterger/Perl-LanguageServer publishes a release.
=> fix(perlls): remove --version argument

lua/lspconfig/server_configurations/ltex.lua
Since `ltex-ls` release 16.0 Quarto and R Markdown are now officially supported: https://github.com/valentjn/ltex-ls/releases/tag/16.0.0
=> Add quarto and rmd filetype to ltex.lua

lua/lspconfig/server_configurations/marksman.lua
`marksman` works for MDX files. We don't want to `set ft=markdown`, since there exist tools that don't work for MDX, so we want to keep .md and .mdx as separate filetypes.
=> feat(marksman): enable for `markdown.mdx`

lua/lspconfig/configs.lua
I'm using the plugin, that manages sessions using builtin `:mksession` and race lead to error on line 118, where 
`api.nvim_buf_get_name(bufnr)` called on not existing buffer. 
This PR adds check `api.nvim_buf_is_valid` to fix this error.
This fix works on this line, but sometimes I see also an error message from [neovim](https://github.com/neovim/neovim/blob/1e7e9ee91f73c62b8c5ba9dbdabba3a3b6dc0130/runtime/lua/vim/lsp/semantic_tokens.lua#L582) itself:
`[LSP] No client with id: `
it should be fixed too. But this is not related to nvim-lspconfig
=> fix(launch): check buffer is valid before get_name

lua/lspconfig/server_configurations/nginx_language_server.lua
Add missing argument `fname` as loading the nginx server configuration  generates the following error:
```
[lspconfig] unhandled error: ...w/Cellar/neovim/0.9.4/share/nvim/runtime/lua/vim/uri.lua:64: attempt to index local 'path' (a function value)
```
=> fix(nginx-language-server): update root directory pattern

lua/lspconfig/server_configurations/ruby_ls.lua
Self explanatory, this PR enables single file support for ruby-lsp.
=> feat: enable single file support for ruby-lsp

lua/lspconfig/server_configurations/tailwindcss.lua
Adding `gohtmltmpl` to the default filetypes for tailwindcss. This is a filetype added by [vim-go](https://github.com/fatih/vim-go).
This was added to tailwindcss-intellisense in https://github.com/tailwindlabs/tailwindcss-intellisense/pull/473.
=> feat(tailwindcss): add `gohtmltmpl` to filetypes

lua/lspconfig/server_configurations/elixirls.lua
In Elixir, it's usual to work with umbrella apps, which works as like a monorepo:
```
blog/
├── .git/
├── config/
├── apps/
│   ├── blog_web/
│   │   ├── mix.exs
│   │   ├── lib/
│   │   └── test/
│   └── blog/
│       ├── mix.exs
│       ├── lib/
│       └── test/
└── mix.exs
```
With the current config, neovim would create a new elixirls server for each directory inside apps/. Unfortunately, there's no good way to know if we're dealing with a umbrella structure or a single-app structure without checking the contents of `mix.exs`.
So, I propose to give a higher priority to detecting `.git` in the root folder and using that as the root for lsp. I'm already using this config in my neovim config.
=> feat(elixirls): Update elixirls.lua to work better with umbrella apps

lua/lspconfig/server_configurations/solidity_ls_nomicfoundation.lua
The package name has changed, as seen in https://github.com/NomicFoundation/hardhat-vscode/blob/development/server/README.md#install
=>  fix(solidity_ls_nomicfoundation): update installation instructions 

lua/lspconfig/server_configurations/rescriptls.lua
- The ReScript language server is available on NPM.
- `rescript.json` is supported by ReScript Compiler
https://forum.rescript-lang.org/t/ann-rescript-language-server-and-rescript-tools-released/4819#the-rescript-language-server-as-an-npm-package-1
=> feat(rescriptls): install from npm

lua/lspconfig/server_configurations/ast_grep.lua
Hi, ast-grep author here 👋 
Thank you for accepting the tool in nvim-lspconfig!
I noticed that the root_dir pattern can be improved by including the `yml` file extension. 
I also added a short message about the requirement of using `sg lsp` in projects, in order to avoid potential confusion if users didn't configure their projects correctly.
Thanks
=> feat: improve root_dir pattern for ast-grep

lua/lspconfig/server_configurations/nushell.lua
Fixes #2592 (Originally closed due to no language server being available)
This adds support for the built-in language server that was [added to nushell a week ago](https://github.com/nushell/nushell/pull/10723), which will be available in an upcoming release.
Seems like currently it only supports function hover
=> Add nushell built-in language server support

lua/lspconfig/server_configurations/contextive.lua
Contextive language server provides domain terminology directly in the IDE by reading a terminology file.
> By defining terms in a central definitions file, Contextive can surface definitions and usage examples in auto-complete suggestions & hover panels wherever the terms are used - in code (of any language across the stack), comments, config, and documentation (e.g. markdown).
https://github.com/dev-cycles/contextive
How it looks:
=> feat: add contextive-language-server support

flake.lock, flake.nix
Updates `flake.lock`, adds explicit url for `nixpkgs` and adds `vusted` to dependencies.
Closes #2890
=> fix: add `vusted` to `flake.nix`

lua/lspconfig/async.lua
I ran into an error like #2733 when opening a project where `go` was unable to start, and noticed `async.run_command` didn't report an error at all.
This adds a check for the exit code of the command, reporting that back to the user with stderr output, and changes the existing error check:  jobid -1 is returned when the command _can't start at all_, and there shouldn't be any stderr output at that point either.  Normally, you could get further detail "errno" style, but i don't see that this is exposed by the job api.
Example after fix:
It's possible merging this will add some insight into the ways people are still running into #2733 - though it doesn't mess with the actual place where mod_cache is nil and emitting _that_ message.
=> fix: async.run_command: report error exit code and stderr

lua/lspconfig/server_configurations/nushell.lua
This allows the nushell LSP to kick in when opening the current shell command in neovim (using CTRL+O by default)
=> feat: enable single file mode for nushell lsp

doc/server_configurations.md, doc/server_configurations.txt, lua/lspconfig/server_configurations/jdtls.lua
progress message
**before**
**After**
=> fix: remove outdated jdtls progress message handler (#2897)

doc/lspconfig.txt, lua/lspconfig/util.lua, test/lspconfig_spec.lua
Because of the way `util.root_dir` is defined, `.csproj` files are found before `.sln` files and the incorrect root directory is set. This prevents go-to-definition between multiple projects in a single solution and causes a few other issues. See #2612 for a more in-depth explanation.
This updates the default configuration to avoid this footgun.
EDIT:
The changes now cover the above issue, but does so in a more general way by updating the `util.root_pattern` function.
closes #2612 
related to razzmatazz/csharp-language-server#57
=> fix: util.root_pattern prioritises pattern order

lua/lspconfig/server_configurations/rust_analyzer.lua
After commit https://github.com/neovim/nvim-lspconfig/commit/d5d7412ff267b92a11a94e6559d5507c43670a52 I started getting the message
```
[lspconfig] cmd failed with code 101: table: 0x0104f90fe0
error: could not find `Cargo.toml` in `<path>` or any parent directory
Press ENTER or type command to continue
```
every time I open a rust file in a project that doesn't use cargo. For some reason `cargo` is launched even if `Cargo.toml` is not found which seems wrong, so I moved all the cargo logic inside `if cargo_crate_dir ~= nil`.
rust-analyzer supports non-cargo projects via `rust-project.json` that nvim-lspconfig also supports, and it's what I use.
=> fix(rust-analyzer): don't run cargo if Cargo.toml is not found

lua/lspconfig/server_configurations/slangd.lua
`slangd` is the language server for [slang](https://github.com/shader-slang/slang), a shader language that extends HLSL with additional features.
The filetype `shaderslang` is a invention of myself, but I plan to also use it for a tree-sitter parser https://github.com/nvim-treesitter/nvim-treesitter/pull/5659 and a TBD PR to vim for filetype detection. `shaderslang` is used because Vim/Neovim already has support for a filetype called `slang` which I assume is for https://en.wikipedia.org/wiki/S-Lang with extension `*.sl` while `shaderslang` uses `*.slang`. The language server also works with regular `hlsl` https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl / https://de.wikipedia.org/wiki/High_Level_Shading_Language (which would also require a PR to be detected …
=> feat: add support for slangd

lua/lspconfig/server_configurations/cairo_ls.lua, lua/lspconfig/server_configurations/custom_elements_ls.lua, lua/lspconfig/server_configurations/gopls.lua, lua/lspconfig/server_configurations/gradle_ls.lua, lua/lspconfig/server_configurations/hls.lua, lua/lspconfig/server_configurations/kotlin_language_server.lua, lua/lspconfig/server_configurations/omnisharp.lua, lua/lspconfig/server_configurations/syntax_tree.lua, lua/lspconfig/server_configurations/tailwindcss.lua, lua/lspconfig/server_configurations/tsserver.lua, lua/lspconfig/server_configurations/vtsls.lua
Simplify `root_dir` in multiple language server configurations where root patterns needed to be prioritised. `util.root_pattern` now prioritises root patterns provided first - see #2885.
Closes #2904
=> fix: cleanup root patterns

lua/lspconfig/server_configurations/elixirls.lua
If we're in a subdirectory of a git repo, and that subdirectory contains a mix.exs file, it makes sense to assume the subdirectory is the project root, rather than the git repo root.
=> fix(elixirls): root_dir priority: mix.exs > .git

plugin/lspconfig.lua
The `local version_info = vim.version()` is currently only used in the `if vim.fn.has 'nvim-0.7' ~= 1 then` case.
This function call is useless. I have reduced it.
=> perf: reduce an unnecessary function call

lua/lspconfig/server_configurations/emmet_language_server.lua
This PR removes `vue`, `astro`, and `svelte` from the list of filetypes since the language server used by those languages already bundle emmet in their implementation.
https://github.com/olrtg/emmet-language-server/pull/25
=> chore(emmet_language_server): emove languages with emmet bundled by their language server

lua/lspconfig/server_configurations/typos_lsp.lua
I'm not sure why the root detection for this language server was based on `pyproject.toml` since it has nothing to do with python projects. This updates the root detection to detect the root using the typos configuration file instead.
=> fix(typos_lsp): use configuration file for root detection

lua/lspconfig/server_configurations/cssls.lua
For some reason not entirely clear to me, simply adding `css.settings.format.enable = true` does not work to enable the formatting capabilities of the LSP.
the css-lsp's documentation isn't great, but [in the repo of the sublime-client for cssls](https://github.com/sublimelsp/LSP-css/blob/be5f00bc7f64fa8dc6b74a214b82486209fef0e6/language-server/css-language-features/server/out/cssServer.js#L102), I found that apparently you need add `provideFormatter = true` as an initialization option. not sure where exactly that options comes from though, as it does not seem to be included [in the code of the vscode language server](https://github.com/search?q=repo%3Amicrosoft%2Fvscode-css-languageservice%20provdeFormatter&type=code), so I assume it has sth to do with the language server extraction? …
=> fix(cssls): enable enabling of formatting capabilities

lua/lspconfig/server_configurations/cds_lsp.lua
Basic LSP config for @sap/cds-lsp
=> feat: add cds-lsp

lua/lspconfig/server_configurations/elixirls.lua
Should fix issues identified following merge of https://github.com/neovim/nvim-lspconfig/pull/2910
=> fix(elixirls): smarter detection of root_dir for umbrella apps

lua/lspconfig/server_configurations/kotlin_language_server.lua, lua/lspconfig/server_configurations/psalm.lua
- Add default value for storagePath to enable caching. This feature is important for Kotlin project because the LSP start takes too long because of indexing on each start. I'm not sure if this option fits the [boundary](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#scope-of-lspconfig) or not. For me it's a sane default
- Update docs
feature was added in https://github.com/fwcd/kotlin-language-server/pull/337 to help with caching and speeding up the language server.
I did not find the feature documented in the LSP repo to link but it has been used in:
- https://github.com/fwcd/vscode-kotlin/pull/86/
- https://github.com/emacs-lsp/lsp-mode/pull/4197
=> feat(kotlin_language_server): Add storagePath to initilaztion options

lua/lspconfig/server_configurations/zls.lua
File `build.zig` by convention sits at the root dir and thus can be used to correctly identify the root directory.
This is particularly useful if `zls` has `enable_build_on_save` set to `true`, since then the language server uses workspace path (root_dir) to execute `zig build` command, output of which is then used to publish diagnostic errors.
Without `build.zig` root directory can incorrectly be deduced some layers too high at the root of the git repo. In such case `enable_build_on_save` silently fails and does not report build error diagnostics.
=> fix(zls): include `build.zig` in root dir search

lua/lspconfig/server_configurations/typos_lsp.lua
This PR removes `.git` as root pattern. Doing so fixes some issues associated with nested workspaces / repos with multiple `typos.toml` configuration file, that are further elaborated here: https://github.com/tekumara/typos-vscode/issues/23 Long story short, having `.git` as root indicator can in some situations lead to not detecting `typos.toml` configuration files. 
`typos-lsp` runs fine in single-file-mode when no root pattern can be found. In fact, as far as I can tell, picking up a configuration file is the only reason the `typos-lsp` actually needs a root pattern for, otherwise single file mode works fine, probably since the LSP is only a wrapper around the `typos` cli. Thus, there should be no downside to removing `.git` as root pattern, and the only consequence would be to fix …
=> fix: typos root directory indicator

plugin/lspconfig.lua
As documented in README.md(after 5a871409199d585b52b69952532e3fb435e64566), nvim-lspconfig now supports version 0.8 or later. Update code to perform this version check.
=> chore: check version 0.8+

lua/lspconfig/server_configurations/twig_language_server.lua
The docs describe the installation via Mason based on my PR over there: https://github.com/mason-org/mason-registry/pull/3855
While twiggy is a fork of https://github.com/kaermorchen/twig-language-server, it's maintainer adds features much faster.
=> feat: add twig-language-server

doc/lspconfig.txt
Typo fix in `lspconfig.util` documentation.
=> fix: typo in util documentation

lua/lspconfig/server_configurations/sqls.lua
sqls has been deprecated with #2544.
Recently sqls is transferred from [lighttiger2505/sqls](https://github.com/lighttiger2505/sqls) to [sqls-server/sqls](https://github.com/sqls-server/sqls) and maintained.
=> fix(sqls): sqls is unarchived

lua/lspconfig/server_configurations/ols.lua
It doesn't seem like ols really has support for single_file_support. The ols application crashes with the following message: "ols/src/server/requests.odin(1494:28) Index 0 is out of range 0..<0\n"
This happens on workspace/didChangeConfiguration when settings are provided in the users' ols setup.
To work around this, essentially turning off single_file_support & adding *.odin as a way to detect a root_dir. This isn't very common but at least one other language server uses this method, qml_ls. However, without this, the ols doesn't really work out of the box for projects that lack a .git directory or ols.json file.
=> fix(ols): remove single_file_support

lua/lspconfig/server_configurations/lwc_ls.lua
This feature adds support for the LWC LS using the official [npm package](https://www.npmjs.com/package/@salesforce/lwc-language-server), I've included instructions on how to configure it manually as well if that was desired. 
Root_dir is based off of other Salesforce LS's, namely apex_ls and visualforce_ls. I've also created a separate PR which added the LS to the mason registry here: [mason-org/mason-registry#3862](https://github.com/mason-org/mason-registry/pull/3862)
I'm also on windows so I've been unable to run docgen or check lua using luacheck.... can't seem to get it working :(
=> feat: add lwc-language-server support

lua/lspconfig/server_configurations/docker_compose_language_service.lua
I propose adding a note about the filetype, as I just spent a few hours trying to figure out why the lsp didn't run when entering a docker-compose.yaml file. I think this would avoid anyone doing the same.
=> fix(docs): Add note about filetype for docker-compose

lua/lspconfig/server_configurations/vale_ls.lua
[as of vale 3.0.0, vale can be used with a system default `.vale.ini`](https://vale.sh/docs/topics/config/), which means vale_ls can also be used in single file mode
=> feat: enable single file mode for vale_ls

lua/lspconfig/server_configurations/lua_ls.lua
lua_language_server
I have nvim config, looking like this (which I believe is common):
```
nvim/
lua/
<a bunch of .lua files>
init.lua
```
When I do `nvim init.lua` LSP client starts, but in single_file_mode. If I do `:LspStop` and then `:LspStart lua` it doesn't start, because it can't find the root directory.
If parent directory contains `lua/` directory, parent should be the root directory, not `parent .. "lua/"`.
This way the root directory for `init.lua` is `nvim/` and for `lua/file.lua` is `nvim/` as well, instead of what happens now (can't find root directory for `init.lua` and for `lua/file.lua` root directory is `nvim/lua/`)
=> Unexpected behaviour when executing ":LspStart lua" in "init.lua" file

lua/lspconfig/server_configurations/biome.lua
Closes https://github.com/neovim/nvim-lspconfig/issues/2980
This PR adjusts the configuration for the biome LSP to only attach if there is an existing `biome.json` found. 
This helps prevent conflicts in ESLint projects since biome would attach and start providing diagnostics and would format files which could conflict with the ESLint/Prettier rules that are defined.
=> [Biome] Make biome only run in projects with an existing biome.json

lua/lspconfig/server_configurations/mdx_analyzer.lua
Per https://github.com/orgs/mdx-js/discussions/2427 and my own testing, `mdx_analyzer` needs a similar treatment as `volar` and `astro` to pass the typescript library into the lsp. Otherwise you get the error mentioned in that discussion.
=> fix(mdx_analyzer): pass typescript lib as option

lua/lspconfig/configs.lua
Remove autocmd BufReadPost on LspStop so that lsp won't be auto started on buf read after explicit stop with LspStop.
=> fix: disable autostart after :LspStop

lua/lspconfig/server_configurations/swift_mesonls.lua
This is the preferred filename for defining options for a few versions. meson_options.txt is legacy, but will continue to stick around.
=> feat(swift_mesonls): add meson.options as a root marker

plugin/lspconfig.lua
improve the get_clients_from_cmd_args for better readability and consistency.
- Replaced dictionary-based storage with a table for clients in the get_clients_from_cmd_args function.
- Utilized the '#' operator to accurately count clients and enhance code readability.
- Updated the condition for checking if the result table is empty using the '#' operator.
=> refactor: improve get_clients_from_cmd_args

lua/lspconfig/server_configurations/rust_analyzer.lua
I'm not that well versed in Lua, but the previous check
if fname:sub(1, #item) == item
didn't really work as expected and I was still experiencing high CPU
usage when using the `go to definition` functionality. After adding some
print statements for debugging, I noticed that only a few chars were
removed from the base dir and thus the comparison was failing. Perhaps
it might work differently in other operating systems, but my Linux
machine it did not work correctly.
I replaced this check with `util.path.is_descendant` which now works
correctly, as well as added another path to check when git repositories
are used as cargo dependencies.
=> rust-analyzer: Fix is_library

lua/lspconfig/manager.lua
fixes issue [#2959](https://github.com/neovim/nvim-lspconfig/issues/2959#issue-2068768094)
---
After executing `:LspRestart` **nvim-lspconfig** tries to reuse the same client (tsserver, ...) but this causes buffers from different root_dirs to fall into single_file_mode (1 tsserver per buffer) even if single file mode is turn off. This PR enforces the single file mode check before trying to reuse a client from other root_dir.
=> fix: enforce single file mode check when root_dir differs from client

lua/lspconfig/server_configurations/fennel_ls.lua
The `fennel-ls` server can support `utf-8` offsetEncoding now, and is faster when it doesn't need to compute offsets.
=> feat(fennel-ls): allow utf-8 offsetEncoding

lua/lspconfig/server_configurations/texlab.lua
Texlab looks for
* `.texlabroot`
* `texlabroot`
* `Tectonic.toml`
when searching for the project root: [https://github.com/latex-lsp/texlab/wiki/Project-Detection#root-directory](https://github.com/latex-lsp/texlab/wiki/Project-Detection#root-directory).
It would be nice if the default `root_dir` discovery method matched that of TexLab.
=> fix(texlab): search for default texlab root files

lua/lspconfig/server_configurations/denols.lua
Since https://github.com/denoland/deno/pull/22182 Deno removed `deno/cache` custom command.
This PR make the plugin use `workspace/executeCommand` instead.
=> fix: Follow latest denols implmention

lua/lspconfig/server_configurations/quick_lint_js.lua
`quick-lint` works for typescript as well, but the config did not include typescript in the filetypes.
=> fix(quick_lint_js): enable for typescript

lua/lspconfig/server_configurations/solidity_ls.lua
The unofficial npm package was only uploaded once, two years ago:
https://www.npmjs.com/package/solidity-language-server
There is now a first-party package:
https://github.com/juanfranblanco/vscode-solidity/issues/432#issuecomment-1943584107 https://www.npmjs.com/package/vscode-solidity-server
The binary name is different so users will have to install the new one or they will error.
=> feat(solidity_ls)!: switch to first-party npm package

lua/lspconfig/server_configurations/ocamllsp.lua
`filetypes` should trigger on `&ft`, not on language id.
Fixes a bug introduced in 946d4a7be1b88e0d44d3d196a524bda8bb27a8c0 (#1088), by inlining the wrong side of the mapping.
=> fix(ocaml): trigger by filetype, not language id

lua/lspconfig/server_configurations/gdshader_lsp.lua
gdshader-lsp is a language server for the Godot shading language.
=> feat: add gdshader-lsp support

lua/lspconfig/server_configurations/purescriptls.lua
Following the footsteps of https://github.com/neovim/nvim-lspconfig/pull/1954 
[Spago](https://github.com/purescript/spago) has now migrated to `spago.yaml`. See the reference language server implementation: https://github.com/nwolverson/purescript-language-server/blob/2d98c1b3a2560968da8d0720095a5094279f5f3c/src/LanguageServer/IdePurescript/Main.purs#L372-L378 (current main).
I also took the liberty to sort the patterns alphabetically, as the order in default_config and docs wasn't synchronized.
=> Add 'spago.yaml' to the list of purescript-language-server's root_patterns

lua/lspconfig/server_configurations/bqnlsp.lua
Hello
This pull request adds support for [bqnlsp](https://git.sr.ht/~detegr/bqnlsp).
Compiling and running the binary is a little more involved and might need to set up the search path for the dynamic linker (see documentation of bqnlsp).
Therefore I added `libcbqnPath` to the setup dictionary and created a utility function to set the environment variable depending on the operating system.
I formatted the code and used the linters. If there is still something bad with the code please tell me and I will gladly fix it.
=> feat: add bqnlsp support

doc/lspconfig.txt, lua/lspconfig/configs.lua, lua/lspconfig/server_configurations/lua_ls.lua
Since https://github.com/neovim/neovim/pull/18847 there's no need to send the `workspace/didChangeConfiguration` manually after initialization, since neovim will automagically do it.
This PR removes documentation references recommending this behaviour, together with the implementation handling the redundant action (I might have missed places so please review carefully).
=> fix: let core handle 'workspace/didChangeConfiguration' after init

lua/lspconfig/server_configurations/bqnlsp.lua
Hello
The current implementation would overwrite a user provided `cmd_env` if also providing `libcbqnPath`.
This commit adds additional checks to see whether `cmd_env` and the environment variable keys already exist.
It they exist, it will not replace them.
=> fix(bqnlsp): do not override user provided `cmd_env`

lua/lspconfig/server_configurations/pyright.lua
`PyrightSetPythonPath` command no longer works due to https://github.com/neovim/neovim/commit/9f8c96240dc0318bd92a646966917e8fe0641144.
=> fix(pyright): fix PyrightSetPythonPath command

lua/lspconfig/server_configurations/delphi_ls.lua
Add support for Delphi Language Server, which is available only for Windows.
The config file for the language server *.delphilsp.json is located in the root_dir.
Unfortunately the root_dir is not available at the configuration creation time,
so I had to look for it. Maybe, there is a better solution?
=> feat: add delphilsp support

lua/lspconfig/server_configurations/markdown_oxide.lua
Add initial support for https://github.com/Feel-ix-343/markdown-oxide
=> Feat: Add markdown-oxide lsp

lua/lspconfig/server_configurations/pico8_ls.lua
Add support for [pico8-ls](https://github.com/japhib/pico8-ls)
PICO-8 is a [fantasy console](https://www.lexaloffle.com/pico-8.php?page=faq) for making, sharing and playing tiny games and other computer programs.
=> Add pico8 language server

lua/lspconfig/server_configurations/css-variables.lua
Add configuration for the css-variables-language-server.
Currently blocked by https://github.com/vunguyentuan/vscode-css-variables/pull/83
The CSS language server does not support CSS variables declared in other files. This augments that language server to provide autocompletion and go-to-definition support for CSS variables.
=> Add css-variables-language-server

lua/lspconfig/server_configurations/css_variables.lua
Without providing default values via the lua config, you get an error similar to this:
```
TypeError: Cannot read properties of null (reading 'lookupFiles')
at CSSVariableManager.parseAndSyncVariables (/Users/gegoune/.pnpm-global/5/.pnpm/css-variables-language-server@2.7.0/node_modules/css-variables-language-server/dist/index.js:250:54)
at /Users/gegoune/.pnpm-global/5/.pnpm/css-variables-language-server@2.7.0/node_modules/css-variables-language-server/dist/index.js:328:22\n\nNode.js v21.6.2\n"
```
The LSP provides a default (https://github.com/vunguyentuan/vscode-css-variables/blob/763a564df763f17aceb5f3d6070e0b444a2f47ff/packages/css-variables-language-server/src/CSSVariableManager.ts#L31-L50) but it doesn't seem to work when run in Neovim. I'm not sure of the best way to resolve this …
=> fix: CSS Variables LSP default settings

lua/lspconfig/server_configurations/harper_ls.lua
We added some configuration options to `harper-ls`, making the documentation on `nvim-lspconfig` a little out-of-date. This pull request fixes that.
=> feat: updated documentation for `harper-ls`

lua/lspconfig/server_configurations/beancount.lua
As is shown in the README (https://github.com/polarmutex/beancount-language-server#neovim),  `journal_file` instead of `journalFile` should be used. 
It might due to a documentation bug fixed in https://github.com/polarmutex/beancount-language-server/commit/d99351b6e6bf04c015d7cab173b3a523ca59d6e4
=> fix(beancount): rename journalFile to journal_file

lua/lspconfig/configs.lua, lua/lspconfig/manager.lua
From https://github.com/neovim/neovim/commit/a5fe8f59d98398d04bed8586cee73864bbcdde92, types were renamed.
Thanks for all your work!
=> fix: update lua types to match latest nightly

lua/lspconfig/server_configurations/terraformls.lua
When setting `init_options' to an empty array terraform-ls fails to start and throws a trace.
See [3051](https://github.com/neovim/nvim-lspconfig/issues/3051) for details.
Removing `init_options' here is quick solution to make it work again.
=> Fixup 3051: Allow terraform-ls to start properly

lua/lspconfig/server_configurations/lua_ls.lua
https://github.com/neovim/nvim-lspconfig/assets/58370433/49425c0c-9b6a-461c-a434-2341b337ef6f
In `neovim` nightly, the current suggested config fails. I added a video demo, using this repro:
```lua
--- CHANGE THESE
local pattern = "lua"
local cmd = { "lua-language-server" }
-- Add files/folders here that indicate the root of a project
local root_markers = { ".git", ".editorconfig" }
-- Change to table with settings if required
local settings = {
Lua = {
runtime = {
-- Tell the language server which version of Lua you're using
-- (most likely LuaJIT in the case of Neovim)
version = "LuaJIT",
},
-- Make the server aware of Neovim runtime files
workspace = {
checkThirdParty = false,
library = {
vim.env.VIMRUNTIME,
-- Depending on the usage, you might want to add additional paths here.
-- …
```
=> docs(lua_ls): change suggested setup to work on both nightly and 0.9.5

lua/lspconfig/server_configurations/lexical.lua
Should prefer a directory with `mix.exs` file as the lsp root directory.
If we have a mix project in a sub-folder of a git repo like this
```
. git_repo/
├── .git/
├── mix_project/
│   └── mix.exs
└── other_project/
```
The root directory should be `mix_project` rather than `gir_repo`, or the lexical lsp won't recognize the project correctly.
=> fix(lexical): lexical root directory config

lua/lspconfig/server_configurations/eslint.lua
ESlint flat config files can also come as `.mjs` files, this PR supports them.
=> Support ESlint mjs flat config file

lua/lspconfig/server_configurations/ast_grep.lua
ast-grep requires a project setup like sgconfig.yml. 
Otherwise it will report an error. This fix removes the single_file_support option.
reference: https://stackoverflow.com/questions/78169005/when-i-open-nvim-show-me-error-massage-from-ast-grep/78169923#78169923
=> fix: remove single file support for ast-grep

lua/lspconfig/server_configurations/mesonlsp.lua
mesonlsp is a new language server for Meson by the same author as Swift-MesonLSP. Swift-MesonLSP is no longer developed.
=> Add mesonlsp

lua/lspconfig/server_configurations/basedpyright.lua
This new LSP server, BasedPyright, mimics all the behavior from Pyright but adds functionality to it that was introduced in the closed source companion of Pyright, Pylance.
The main purpose of this new server is to provide the same API Pyright does, but adding functionality the maintainers of Pyright LSP won't consider adding to the open-source project.
=> Add BasedPyright LSP

lua/lspconfig/server_configurations/ruff.lua
Hi 👋, we (Astral) have released the Alpha version of our new Rust-based language server for Ruff. It was added in `v0.3.3` and can be run via `ruff server` command with the `--preview` flag. Currently, the server is not in par with our existing `ruff-lsp` server and we plan to maintain `ruff-lsp` until any further notice. The following capabilities are supported as of today:
1. Diagnostics
2. Formatting
3. Range formatting
4. Code actions
This PR adds a configuration for the server under a new namespace `ruff`. I'm not exactly sure if this is the correct way to do so. Please inform me if not and I’ll update the PR accordingly.
=> feat: add the new Ruff language server

lua/lspconfig/server_configurations/ginko_ls.lua
Adds configuration for [`ginko_ls`](https://github.com/Schottkyc137/ginko?tab=readme-ov-file#ginko_ls).
I tested this locally and it works well. I tested with the test file from `ginko`'s readme
```dts
/dts-v1/;
/ {
pic@10000000 {
phandle = <1>;
interrupt-controller;
reg = <0x10000000 0x100>;
}
};
```
=> feat: adds ginko_ls support

lua/lspconfig/server_configurations/tsp_server.lua
This adds support for `tsp-server`, the language server for the [TypeSpec language](https://github.com/microsoft/typespec).
=> feat: add tsp-server support

lua/lspconfig/server_configurations/css_variables.lua
I was scrolling through [server configurations](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md) searching for `css_variables` and I saw this problem:
> You can check it out [css_variables](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#css_variables)
So I made the change to look like this:
---
**Snippet to enable the language server:**
```lua
require'lspconfig'.css_variables.setup{}
```
---
> @glepnir sorry for the last PR about this issue 😥
=> docs(css_variables): `server_configuration` for `css_variables`

lua/lspconfig/server_configurations/omnisharp.lua
The standard way in lspconfig is configuring through the `settings` table. Omnisharp doesn't support being passed config at runtime, so previously some common options were toggled and added to the command args. That happened for only the preconfigured options.
This PR generalizes the behaviour in an attempt to allow users to set their options in the standard way, allowing for a more seamless syntax transition from JSON format that is used in `omnisharp` global config and `vscode`.
Although I haven't experienced any issues when leaving the `settings` table in the config, I assume `nvim` then tries to feed the settings to `omnisharp`, which may be avoidable by `settings=nil` (opinion needed).
=> feat(omnisharp)!: use standard `settings` table for configuration

lua/lspconfig/server_configurations/perlnavigator.lua
The prior instructions only included building from source. This includes installation of the perlnavigator from npm and a default command. Should make the perlnavigator simpler to install and configure. Thanks!
=> Feat: Add cmd and installation instructions for perl navigator

lua/lspconfig/server_configurations/beancount.lua
parameter journal_file is optional and should net be set: https://github.com/polarmutex/beancount-language-server/commit/22a559501b41955dbbe3fb2404e29e8e3e66e2af
Further more, the current empty string raises an error in line: https://github.com/polarmutex/beancount-language-server/blob/main/crates/lsp/src/server.rs#L122
=> beancount: Avoid initialization of optional value

lua/lspconfig/server_configurations/gopls.lua
When using neovim in git bash I got this [error](https://imgur.com/a/8cXYYWs) due to the command being processed as a single string by git bash's bash.exe.
This PR fixes the Issue for me by passing the command and arguments as a table rather than as a single string.
Haven't tested it on linux though.
=> git bash fix with go env GOMODCACHE

lua/lspconfig/server_configurations/snyk_ls.lua
To make snyk-ls work more seamlessly out-of-the-box, this PR adds support filetypes to launch the Snyk LS server and adds `.snyk` config file as a root dir
=> fix(snyk_ls): update root_dir & supported filetypes

lua/lspconfig/server_configurations/ltex.lua
Plaintext email and standard plaintext do not feature any markup tokens, so ltex works out of the box with no parser (tested it out locally). I think it is very useful to have a grammar checker for these formats, too. Most people use them.
=> feat: add mail and text as ltex filetypes

lua/lspconfig/manager.lua
https://github.com/neovim/neovim/pull/28478 changes the signature of start_client to return two values: client_id or nil and error message or nil. start_client no longer calls vim.notify directly, so if there is an error we must call vim.notify ourselves.
=> refactor: handle updated signature of lsp.start_client

README.md
Also remove `LspAttach` and `LspDetach` examples. There are examples included in the Nvim docs, and we should be pointing users toward that documentation rather than duplicating it here.
=> Add new default maps for Nvim 0.10

plugin/lspconfig.lua
Problem: buffers id as key in attached_buffers.
Solution: use api to get buffers list for later restart and attach
Fix #3129
=> fix(command): get attached buffers list by using api

lua/lspconfig/server_configurations/elmls.lua
This PR fixes the `init_options` for the `elmls` server configuration.
Ref: https://github.com/elm-tooling/elm-language-server?tab=readme-ov-file#server-settings
=> fix(elmls): add missing init_options, remove deprecated

lua/lspconfig/server_configurations/motoko_lsp.lua
This adds configuration files for the [Motoko](https://github.com/dfinity/motoko) language server.
motoko-lsp is part of the [dfinity/vscode-motoko repository](https://github.com/dfinity/vscode-motoko) and can be installed via [Mason](https://github.com/mason-org/mason-registry/blob/main/packages/motoko-lsp/package.yaml).
=> Add motoko language server

lua/lspconfig/server_configurations/dockerls.lua
Document how the ignoreMultilineInstructions settings for dockerls can
be configured.
That the settings key must be "docker" instead of "dockerls" makes it
non-intuitive and harder to figure out.
Sources:
- https://github.com/rcjsuen/dockerfile-language-server?tab=readme-ov-file#language-server-settings
- https://github.com/rcjsuen/dockerfile-language-server/blob/9e3f8580f711e54a1de0351631baeac49665d6f3/src/server.ts#L330-L344
=> docs(dockerls): document ignoreMultilineInstructions setting

lua/lspconfig/server_configurations/roc_ls.lua
This adds a basic configuration for Roc's built-in language server.
So far only _go-to-definition_, _hover_, _inline diagnostics_ and _formatting_ is implemented.
For more information on the language server itself checkout [Roc](https://github.com/roc-lang/roc/tree/main/crates/language_server#roc_language_server).
=> Add roc-language-server support

lua/lspconfig/server_configurations/shopify_theme_ls.lua
Shopify theme [language-server](https://shopify.dev/docs/themes/tools/cli/language-server) is a LSP server for `liquid` files.  Currently we have the [theme_check](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/theme_check.lua) server_configuration which is considered deprecated. Although I haven't found any information about it. But you can see that there is no activity in the [repository](https://github.com/Shopify/theme-check) for the last year, also this language-server already includes theme_check (linter). Thank you!
=> feat: add shopify theme language-server

lua/lspconfig/server_configurations/ember.lua
Similar to: https://github.com/mason-org/mason-registry/pull/5740
ember-language-server has been upstreamed into its original repo, and released under a new / the original name.
=> Update config for ember-language-server due to upstreaming

lua/lspconfig/server_configurations/r_language_server.lua
when using a recent build of neovim on macos (https://github.com/neovim/neovim/commit/26b5405d181e8c9e75c4b4ec9aae963cc25f285f), viewing `:h lspconfig-all` is entirely broken (error crash loop) because of a broken injection in the document. turns out that the `R` in the markdown description here should be lowercase, since the treesitter grammar uses lowercase `r`!
recreation of #3152
=> fix(r): change markdown injection in documentation to use lowercase r

lua/lspconfig/server_configurations/texlab.lua
`vim.lsp.get_active_clients` will be deprecated in the future, and the deprecation warning will be shown in 0.11.
=> refactor: remove tbl_add_reverse_loopup

lua/lspconfig/server_configurations/vdmj.lua, lua/lspconfig/util.lua, scripts/docgen.lua
add compatible `util.tbl_flatten` and `lsp.get_active_clients` to avoid  deprecated error notify on 0.10 release.
=> refactor: add compatible tbl_flatten and lsp_get_clients for new version 0.10

lua/lspconfig/util.lua
`has('nvim-0.9')` also return 1 on 0.9 above ..
cc @wookayin
=> fix: use new version as check condition

lua/lspconfig/server_configurations/basedpyright.lua, lua/lspconfig/server_configurations/denols.lua, lua/lspconfig/server_configurations/gopls.lua, lua/lspconfig/server_configurations/pyright.lua, lua/lspconfig/server_configurations/rust_analyzer.lua, lua/lspconfig/ui/lspinfo.lua, lua/lspconfig/util.lua, plugin/lspconfig.lua
still have some old `vim.lsp.get_active_clients` usage.
=> refactor: move all old get_clients to new compatible

lua/lspconfig/server_configurations/bacon_ls.lua
Add support for [bacon-ls](https://github.com/crisidev/bacon-ls) ([blog post](https://lmno.lol/crisidev/bacon-language-server)).
This language server allows Rust diagnostics through the [bacon](https://github.com/Canop/bacon) build system.
[![neovim bacon img](https://raw.githubusercontent.com/crisidev/bacon-ls/main/screenshot.png)]()
=> feat: add bacon-ls support

doc/server_configurations.md, doc/server_configurations.txt, lua/lspconfig/server_configurations/ansiblels.lua
Updating the homepage for the `ansible-language-server` to the latest URL, as the currently stated URL points to an archived repository (whose repo description also now points to the latest URL as introduced by this change).
This can be further verified at the package's registry page here: https://www.npmjs.com/package/@ansible/ansible-language-server
=> docs: update ansiblels homepage url

lua/lspconfig/server_configurations/drools_lsp.lua, lua/lspconfig/server_configurations/mutt_ls.lua
The `drools_lsp` and `mutt_ls` are calling `util.find_git_ancestor()` when it should be `util.find_git_ancestor`.
This causes the following error when requiring one of those modules.
```
require'lspconfig.server_configurations.drools_lsp' E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'lspconfig.server_configurations.drools_lsp'
```
This PR remove the parenthesis.
=> fix: remove parenthesis from `find_git_ancestor` call

README.md, doc/lspconfig.txt
This section is way too verbose and encourages sloppy copy-pasting (not to mention it is out of date). Nvim already ships help documentation for configuring the LSP client, so instead of duplicating that information, point users toward upstream docs instead.
Fixes: https://github.com/neovim/nvim-lspconfig/issues/3174
Related: https://github.com/neovim/nvim-lspconfig/pull/3122
=> docs: delete lspconfig-keybindings section

lua/lspconfig/server_configurations/eslint.lua
As [Support for the new ESLint flat config files has improved](https://github.com/microsoft/vscode-eslint?tab=readme-ov-file#version-305---pre-release)
```
eslint.experimental.useFlatConfig
```
should be 
```
eslint.useFlatConfig
```
I have tested with flat config. ```experimental``` not working anymore.
=> fix(eslint): useFlatConfig is not experimental anymore

lua/lspconfig/server_configurations/eslint.lua
I think In Neovim, It still use experimental flag. I think I made mistake on my own config.
So keep as before. Sorry for bad contributing.
=> revert(eslint): useFlatConfig revert to experimental

lua/lspconfig/server_configurations/arduino_language_server.lua, lua/lspconfig/server_configurations/elmls.lua, lua/lspconfig/server_configurations/fennel_ls.lua, lua/lspconfig/server_configurations/rust_analyzer.lua
A config's `default_config` acts as an override to the global `default_config` because of `'keep'` here:
https://github.com/neovim/nvim-lspconfig/blob/38de86f82efd9ba0881203767d6a8e1815abca28/lua/lspconfig/configs.lua#L60
Some configs were providing the entire capabilities table in their `default_config`. This is not necessary because the global `default_config` already includes them, and it was causing any of the user's changes to be overridden.
https://github.com/neovim/nvim-lspconfig/blob/38de86f82efd9ba0881203767d6a8e1815abca28/lua/lspconfig/util.lua#L19
The specific issue I was facing was that globally setting `snippetSupport = true` was ignored for rust_analyzer.
=> fix: avoid overriding global default capabilities

lua/lspconfig/server_configurations/biome.lua
The latest biome release added support for css files: https://github.com/biomejs/biome/releases/tag/cli%2Fv1.8.0
=> feat(biome): add `css` as filetype

lua/lspconfig/server_configurations/slint_lsp.lua
Without this, the LSP doesn't resolve imports properly, at least on recent versions.
=> draft: fix(slint-lsp): set root dir to git ancestor

lua/lspconfig/server_configurations/bitbake_ls.lua
Add default config for `language-server-bitbake`, the Yocto Project's official language server for bitbake.
=> feat(bitbake): add language-server-bitbake support

lua/lspconfig/server_configurations/djlsp.lua
Add default server configuration for our `django-template-lsp` package.
=> feat: add django-template-lsp support

lua/lspconfig/server_configurations/fsautocomplete.lua
Hello.
I've added recommended default settings values for [fsautocomplete](https://github.com/ionide/FsAutoComplete?tab=readme-ov-file#settings). Without these settings some advanced capabilities of the language server doesn't work at all.
=> Added recommended default settings for fsautocomplete

lua/lspconfig/server_configurations/koka.lua
This is still in draft because I couldn't make the language server attach. 
Currently I have 
```lua
vim.filetype.add({
extension = {
kk = "koka",
},
})
```
in my `init.lua` but that doesn't seem to suffice. 
Help would be greatly appreciated.
=> [wip] fix koka language server

lua/lspconfig/server_configurations/hyprls.lua
If the user sets up the `hyprlang` filetype which is also required for the treesitter parser to start should also start the language server
=> fix(hyprls): autostart with hyprland filetype

lua/lspconfig/server_configurations/shopify_theme_ls.lua
I didn't notice last time that the code snippet is generated automatically. This removes an unnecessary snippet
=> docs(shopify_theme_ls): remove unnecessary code snippet

lua/lspconfig/server_configurations/bazelrc-lsp.lua
This is the configuration for https://github.com/salesforce-misc/bazelrc-lsp, which supports `.bazelrc` configuration files.
=> feat: add bazelrc-lsp config

lua/lspconfig/util.lua
Context: https://github.com/neovim/nvim-lspconfig/issues/3087#issuecomment-2016041174
I want to set commands argument in [vim.lsp.ClientConfig](https://neovim.io/doc/user/lsp.html#vim.lsp.ClientConfig) which has `table<string, fun>` type, which is not conforming to lspconfig's own commands type. lspconfig has to skip them for user command registrations.
=> feat: do not process if commands[i] is func type

lua/lspconfig/server_configurations/texlab.lua
This PR adds the last workspace command of [texlab](https://github.com/latex-lsp/texlab/wiki/Workspace-commands) like this #3225. I have tested the code on fedora 40 and windows.
=> feat(texlab): add change environments workspace command

lua/lspconfig/server_configurations/tailwindcss.lua
---
title: 'TailwindCSS: add includeLanguages to config in addition to init opts'
---
fix #3230
I keep the original `init_options.userLanguages`, but it should be safe to remove. If you would like me to remove it, please let me know.
=> fix(tailwindcss): add includeLanguages to config in addition to init opts

lua/lspconfig/server_configurations/leanls.lua
This is partially a bugfix, as such packages would appear to function correctly because we fell back to `lean --server` -- but that is a lie, as it means `lake` doesn't control the LSP environment (and specifically it means that shared objects aren't correctly found for a package which prebuilds them with prebuildModules).
While we're here, remove said ancient Lean 4 logic for versions no one has used for years, simplifying the startup (and saving a subprocess). It'd have been better to fail loudly here rather than falling back to confusing errors.
=> feat(leanls): add support for lakefile.toml-only packages

lua/lspconfig/server_configurations/ruff.lua
Now that the server is stabilized, the `--preview` flag isn't required to run it from [`v0.5.3`](https://github.com/astral-sh/ruff/releases/tag/0.5.3).
This PR removes the need of the `--preview` flag, update the documentation.
This is a breaking change because without the `--preview` flag, `ruff` will throw an error for previous versions. It's only from `0.5.3` that the flag isn't required.
Now, the reason the flag needs to be removed is because the flag itself would turn on preview features from both the linter and the formatter, as it should.
Can the maintainers guide me on how to go about making this kind of change? Is this ok to do so?
In our VS Code extension, we check the `ruff` version and only then use the `--preview` flag …
=> feat!: remove `--preview` flag from Ruff server

doc/server_configurations.md, doc/server_configurations.txt, lua/lspconfig/server_configurations/rust_analyzer.lua
rust-analyzer expects `init_options` to be set to the contents of `settings["rust-analyzer"]` per:
* https://github.com/rust-lang/rust-analyzer/blob/eb5da56d839ae0a9e9f50774fa3eb78eb0964550/docs/dev/lsp-extensions.md?plain=1#L26
* https://github.com/rust-lang/rust-analyzer/blob/eb5da56d839ae0a9e9f50774fa3eb78eb0964550/editors/code/src/ctx.ts#L213
This change ensures the Neovim config for RA complies with the docs, and eliminates a source of confusion around whether to define RA settings in `settings` or `init_options`.
=> [rust-analyzer] automatically populate `init_options` from `settings["rust-analyzer"]`

lua/lspconfig/server_configurations/ruff.lua
fixup from https://github.com/neovim/nvim-lspconfig/commit/0c2aeaeef35436454689ea3b9596e1d4615ad8d0, sorry I keep messing it up!
This time I've generated the documentation locally and verified that it rendered correctly:
=> docs: remove unnecessary backticks

lua/lspconfig/server_configurations/ballerina.lua
[Ballerina](https://ballerina.io/)'s CLI tool (`bal`) provides a language server.
This PR adds a minimal config for it to nvim-lspconfig.
=> feat: add ballerina support

lua/lspconfig/server_configurations/superhtml.lua
Added support the superhtml lsp server.
[source](https://github.com/kristoff-it/superhtml/tree/main)
[article](https://handmade.network/p/564/superhtml-an-html-language-server/)
This is not quite ready to go since the lsp appears to not be functioning fully (that or I've set it up wrong) https://github.com/kristoff-it/superhtml/issues/20.
=> feat: add superhtml support

lua/lspconfig/server_configurations/texlab.lua
Some texlab-specific functions were using `print`, some were using `vim.notify`. Changed all uses of `print` to `vim.notify` with levels:
- `vim.log.levels.INFO` for `build` and `forwardSeach` LSP methods,
- `vim.log.levels.WARN` when the `texlab` client cannot be found.
We could also switch all `error()` calls to `vim.notify`, but we'd lose the stacktrace printed by it hence I left those calls unmodified.
This PR should be compatible with #3255 but haven't rebased the changes against it :)
=> draft: feat(texlab): change all print() to vim.notify()

lua/lspconfig/server_configurations/tvm_ffi_navigator.lua
Add the [TVM FFI navigator](https://github.com/tqchen/ffi-navigator) server configuration, which is used within the TVM project to jump to C++ definitions from python and vice versa
=> feat: add tvm_ffi_navigator server

lua/lspconfig/server_configurations/mesonlsp.lua, lua/lspconfig/server_configurations/swift_mesonls.lua
This PR adds a pattern for the meson.build files in the `root_pattern` functions of the `default_config` and `doc` tables for the `mesonlsp` and `swift_mesonls` servers.
meson.build files are the primary configuration files for the Meson build system and lspconfig should look for these files to determine the root of a project that uses Meson.
=> fix(mesonlsp): update root directory pattern

lua/lspconfig/server_configurations/ruby_lsp.lua
Since 0.17.5, Ruby LSP has supported running inside ERB files.
=> feat: ruby_lsp works inside eruby files

lua/lspconfig/server_configurations/taplo.lua
The taplo language server has a bit of a strict root directory detection. It seems like it was that way because it previously didn't have single file mode enabled. Now that single file mode is enabled we don't need to have it set a project root immediately in the folder. This aligns it more with how `jsonls` and `yamlls` root detection work.
=> fix(taplo): simplify root detection

lua/lspconfig/server_configurations/htmx.lua
HTMX can be used pretty much anywhere where there are HTML tags, so I thought I'd copy the filetypes we have for tailwind CSS (minus the CSS only file types)
That should get good coverage for most templating languages that will use it.
=> feat(htmx): add more filetypes

lua/lspconfig/server_configurations/ruby_lsp.lua
This reverts commit 4cd29ab1b326f5b04f4b982fae05934ac64c779b.
It looks like missing support for DiagnosticRegistrationOptions  (https://github.com/neovim/neovim/issues/24412) is causing issues in some cases with eruby files. It seems best case to revert this change for now.
https://github.com/Shopify/ruby-lsp/pull/2432
=> Revert "feat: ruby_lsp works inside eruby files (#3266)"

.github/workflows/test.yml
Problem: LuaJIT.org has stopped publishing release tarballs on their website.
Solution: use luajit-openresty instead of.
=> test(ci): change to luajit-openresty

lua/lspconfig/server_configurations/hyprls.lua, lua/lspconfig/server_configurations/typos_lsp.lua
I happened to have created a mapping of filetypes and every server in lspconfig. While inspecting them, I noticed some anomalies and found out that they were invalid/unnecessary misconfigurations that were added by accident.
This PR removes those anomalies.
```lua
filetypes = { '*' },
```
`*` filetype pattern is unnecessary. If the `filetypes` field is omitted completely, lspconfig starts the server on `BufReadPost` instead of `FileType`.
```lua
filetypes = { 'hyprlang', '*.hl', 'hypr*.conf', '.config/hypr/*.conf' },
```
The author of hyprls and the original PR to lspconfig confirmed that the filetypes with wildcards were added by mistake.
https://github.com/hyprland-community/hyprls/issues/11#issuecomment-2189841216
> Hi! I actually did a PR for lspconfig to include hyprls (see …
=> fix: remove invalid filetypes containing wildcards from `typos_lsp` and `hyprls`

lua/lspconfig/server_configurations/clangd.lua
This PR adds support for the symbolInfo capability of clangd, for more documentation [see](https://clangd.llvm.org/extensions.html#symbol-info-request). It follows the same principle as #3263, although simpler. I think this is a great and simple addition, which will not add a ton of maintenance burden. Here are some images that showcase, what it does:
Thanks for your awesome work! :)
=> feat(clangd): add symbolInfo support

lua/lspconfig/server_configurations/texlab.lua
This PR tries to improve #3225 by filtering the output and presenting it with `vim.lsp.util.open_floating_preview`. It is a pretty simple implementation that leverages builtin lua functions and basic API, therefore it should not be a burden to maintain. I have tested it locally without any major problems and i will keep testing, while making sure no issues pop up in this repo regarding this feature. I am really sure if the way the border style is setup is fitting. 
Here are some images:
I am totally open to any suggestions :)
=> feat(texlab): give the find environments command a ui wrapper

lua/lspconfig/server_configurations/texlab.lua
This PR makes sure the buf is not passed as a parameter. Moreover it addresses the comment TODO. This PR is modeled after this [comment](https://github.com/neovim/nvim-lspconfig/pull/3274#discussion_r1724433812), of #3274. I have tested the changes and it works as expected.
=> fix(texlab): do not pass buf as parameter

lua/lspconfig/server_configurations/als.lua
To move towards the goal of having lsp configs decentralised and lower the maintenance burden on current maintainers, as requested by @glepnir, @mjlbach and @justinmk
See https://github.com/neovim/nvim-lspconfig/pull/1693 and https://github.com/neovim/nvim-lspconfig/issues/1683 and https://github.com/neovim/nvim-lspconfig/pull/3275#issuecomment-2301318994
=> fix(als): deprecate als in favour of a separate plugin

lua/lspconfig/server_configurations/r_language_server.lua
Many thanks for your efforts maintaining neovim and the language server configurations.
Starting from R version 4.0.0, the command line option `--slave` were renamed to `--no-echo`.
See the relevant news for 4.0.0:
https://cran.r-project.org/bin/windows/base/old/4.0.0/NEWS.R-4.0.0.html and the corresponding commit:
https://github.com/wch/r-source/commit/f1ff49e74593341c74c20de9517f31a22c8bcb04#diff-4747789d759ae72b19c9791301bf52e8cfc5c23dbdda10bf1a6bd003509395dd
=> fix(r-language-server): Use `--no-echo` instead of `--slave`

lua/lspconfig/server_configurations/rescriptls.lua
I was very confused to find that I got no typechecking by default, since ReScript is meant to be a very-strongly-typed language. The intent seems to be to use the "askToStartBuild" option to start an external build, which integrates with the lsp for typing, but that prompt is much too buggy, and the incremental typing (enabled in this PR) works well for me.
=> fix(rescripls): enable typechecking, improve doc

lua/lspconfig/server_configurations/haxe_language_server.lua
Adds `.git` as a root directory pattern.
Previously, it would detect the root dir by matching with "*.hxml", however, it
would use "build.hxml" as the default `displayArguments` even though it may not
exist. This could cause the error:
```
haxe_language_server: -32603: Error: Could not process argument build.hxml (file not found)
Invalid character:
```
Now it will use the first ".hxml" file that is found in the project. It will
only do this if no `displayArguments` value has been set in the `setup()` call,
so it will still respect user set values.
If no hxml file is found, then it uses empty `displayArguments`, which is still
better than a broken configuration.
=> feat: improve default haxe_language_server init_options

doc/server_configurations.md, doc/server_configurations.txt, lua/lspconfig/server_configurations/v_analyzer.lua
v-analyzer repository is currently located in the vlang organization.
=> fix(v-analyzer): change repository location to vlang org

lua/lspconfig/server_configurations/daedalus_ls.lua
This PR adds support for https://github.com/kirides/DaedalusLanguageServer used by Gothic and Gothic II games. Please let me know if the `root_dir` was added correctly as I'm not sure if it's equivalent of steps described in README of mentioned repo.
=> feat: add daedalus-language-server support

lua/lspconfig/server_configurations/sourcekit.lua
Sourcekit LSP was not being attached on objc and objc++ files
=> fix: sourcekit lsp filetypes

lua/lspconfig/server_configurations/ltex.lua
File bin extension is not needed when using mason on windows.
If needed, cmd could be customized through settings.
=> fix(ltex-ls): command fails on windows when using mason

doc/lspconfig.txt, lua/lspconfig.lua, lua/lspconfig/ui/lspinfo.lua
In order to smoothly transition to the vim.lsp.start interface in the future, adding checkhealth here is meaningless(because we already have checkhealth of lsp).  So shown deprecate servers list in LspInfo and update the server deprecate remove version to 0.2.1. 0.2.0 is tagged too quickly cause some servers not removed.
cc @tskj
=> feat: show deprecate servers list in LspInfo

lua/lspconfig/server_configurations/lua_ls.lua
Without this fix I get errors on startup and the config is not applied properly.
> LSP[lua_ls]: Error ON_INIT_CALLBACK_ERROR: "[string \":lua\"]:79: attempt to index field 'workspace_folders' (a nil value)"
=> docs(lua_ls) Fix broken example setup when workspace_folders are not used

lua/lspconfig/server_configurations/c3_lsp.lua
fix(c3_lsp): update root directory to be able to handle project in the following order - a C3 project 'project.json', a library '.c3l' dir, and ancestor 'git' repo.
=> fix: add C3 library support

lua/lspconfig/server_configurations/gopls.lua
Currently, if `go env GOMODCACHE` prints nothing, the config will error. This PR will 1. retry with sync version 2. skip the special configuration case if mod_cache is nil. Even though @glepnir says fallback to sync will cause performance issue, which I agree, I think this is much better than just throwing an error. `go env GOMODCACHE` takes 0.001 ms on my machine.
Alternatively, we can remove 1. (the else case) and just keep mod_cache nil so that there are no performance issue, but we should definitely keep 2. (the nil check on mod_cache).
Related (partially fixes): #2733
=> fix(gopls): improve stability by fixing nil error when go env GOMODCACHE returns nothing

lua/lspconfig/server_configurations/cairo_ls.lua
This PR updates the Cairo Language Server (`cairo_ls`) configuration in `lspconfig` to use `scarb-cairo-language-server` instead of `cairo-language-server`. This change aligns with the new standard as Scarb is now the default package manager for Cairo, and the Scarb-distributed language server extension ensures compatibility with the version of the Cairo compiler used in Scarb.
* Replaced `cairo-language-server` with `scarb-cairo-language-server`, reflecting Scarb as the default package manager.
* Scarb's version of the language server is a launcher for the official Cairo Language Server, ensuring version compatibility with the compiler.
* Updated the documentation link for installing Cairo, following the latest official instructions.
This change simplifies user configuration and ensures …
=> Replace `cairo-language-server` with `scarb-cairo-language-server` and update installation docs

lua/lspconfig/server_configurations/taplo.lua
This updates the doc string with the updated `root_dir` for Taplo
=> docs(taplo): update out of date docstring with new root_dir

lua/lspconfig/server_configurations/julials.lua
This adds a command for the additional `julials` API for activating an environment. This is based on how extra functionality is added into the `texlab` configuration
=> feat(julials): add `JuliaActivateEnv` to activate a julia environment

lua/lspconfig/configs/lua_ls.lua
Fixes #3165 by returning the longer root path if both a `.git`- and a `lua`-ancestor are found (as [suggested by](https://github.com/neovim/nvim-lspconfig/issues/3165#issuecomment-2206937152) @powerman).
I also removed the documentation of the default `root_dir` pattern (assuming that now it will reference the source code, as in many other server configurations), since the root pattern calculation is more involved than the documentation indicated.
=> fix(lua-language-server): update root directory pattern

lua/lspconfig/configs/julials.lua
When converting the `if` statement check in the previous PR to an `assert` the conditional was not flipped. This resolves the issue.
=> fix(julials): inverted `assert` check

.editorconfig, doc/lspconfig.txt, lua/lspconfig/configs.lua, lua/lspconfig/ui/lspinfo.lua, scripts/docgen.lua
Users/plugins may want to use the config definition without actually activating the config via setup(). https://github.com/neovim/nvim-lspconfig/pull/3330#issuecomment-2387285872
- Expose `config_def` field and document it.
- Also undeprecate some stuff that doesn't yet have a documented alternative.
---
TODO: configs.lua sets `M.filetypes = config.filetypes` and other fields in ad-hoc fashion "for :LspInfo" but it's not clear when those fields are actually populated, and they don't source from `config_def`...
=> feat: expose config definition as `config_def`

lua/lspconfig/configs/zls.lua
Language server config is read from `zls.json`. By default common global and user config directories are searched. However, this omits per-project configuration, which can be available in the workspace dir.
We already look for `zls.json` to determine root dir, but we don't use it when starting the language server.
This change appends `cmd` with `--config-path "zls.json"`, which uses the file when it's available and fall-backs to default logic when file is not available.
=> fix(zls): use workspace zls.json if available

lua/lspconfig/configs.lua
Currently, `nvim-lspconfig` tries to attach servers automatically via two autocommands:
1. Created if `config.autostart == true` and triggered by `FileType`, if `config.filetypes` is set, else `BufReadPost`. Calls `try_add()`.
2. Created for each workspace root, triggered by `BufReadPost` matching paths starting with the root. Calls `try_add_wrapper()`.
`BufReadPost` does not fire when creating a buffer for a file that doesn't exist. This means that if `config.autostart == true` and `config.filetypes` is set and includes the detected filetype for the buffer, the server is attached automatically regardless of whether the file exists, but in all other cases the server is only attached for existing files.
1. Where these autocommands trigger on `BufReadPost`, also trigger on `BufNewFile`.
2. …
=> fix: autostart=false: attach when editing new, nonexistent file

lua/lspconfig/configs.lua
Reverts neovim/nvim-lspconfig#2712
=> Revert "fix: autostart=false: attach when editing new, nonexistent file"

lua/lspconfig/health.lua
when in single file mode root dir doesn't include path so no need normalize format it.
=> fix(health): skip format root when in single file mode

lua/lspconfig/configs/fennel_ls.lua
* `fennel-ls` root directory  looks for closest `flsproject.fnl` first, and if it cannot find one, the root of the nearest git repository is used.
* The `fennel-ls` description now references this file and links to the configuration.
Special thanks to @XeroOl for helping me get started here. 🙂
=> fix(fennel-ls): use closest cfg as root directory and fallback to git repo root

lua/lspconfig/configs/lsp_ai.lua
This PR adds support for the [lsp-ai](https://github.com/SilasMarvin/lsp-ai) language server. Since the server is language-agnostic, I've set the defaults to attach to all filetypes, and always run in single-file mode.
Do note that as is, this is not a full, functional configuration (it shouldn't error, just won't generate any completions), as there are parts for which I don't think there are good default values, so I just want to be sure you're good with this as long as I document it, since from a _quick_ look at the supported server list it looks like most (all ?) servers work out-of-the-box with the default config of an empty `setup{}` call. Then again this one is a bit unusual.  
In particular, a user would need to select an inference backend, which could either be some API requiring …
=> feat: add lsp-ai support

lua/lspconfig/configs/lsp_ai.lua
I made a mistake in #3206 causing the docs not to render, this PR puts the language server docstring under the `description` key as expected. The docs now show up when I render them locally.
=> fix(lsp_ai): fix docs not rendering properly

lua/lspconfig/configs/poryscript_pls.lua
Adds minimal `poryscript-pls` configuration to the registry.
Function handlers expected by the LSP implementation are not included to keep this config minimal.
=> feat: poryscript-pls

lua/lspconfig/configs/texlab.lua
I noticed this while debugging some texlab problems.
The configuration key 'texlab.auxDirextory' has been deprecated, in favor of 'texlab.build.auxDir', mirroring the latexmkrc's auxDir variable.
see: https://github.com/latex-lsp/texlab/wiki/Configuration#deprecated-texlabauxdirectory
=> fix(texlab): remove deprecated texlab.auxDirectory

lua/lspconfig/configs/jqls.lua, lua/lspconfig/configs/uvls.lua
Basically from [this](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#jqls)
```lua
vim.cmd(\[\[au BufRead,BufNewFile *.jq setfiletype jq\]\])
```
to this
```lua
vim.cmd([[au BufRead,BufNewFile *.jq setfiletype jq]])
```
=> fix(jqls): incorrect backslashes in docs

lua/lspconfig/configs/lsp_ai.lua
Follow suit of other descriptions that are just strings. 
Follow up to https://github.com/neovim/nvim-lspconfig/pull/3206/files#r1801612126
=> fix(lsp_ai): docs.description string instead of table

plugin/lspconfig.lua
The current `LspStop` behavior is confusing and on some occasions wrong:
**Server name:**
- If the server with the given `server_name` is **not attached**:
- No notification is shown, and **all** LSP servers are stopped.
- If the server with the given `server_name` is **attached**:
- **Incorrectly** closes all LSP servers.
- If no servers are attached:
- `server_name` is notified as missing.
**Server ID:**
- If the server with the given `server_id` is **not attached**:
- Uses `get_managed_clients()` function https://github.com/neovim/nvim-lspconfig/blob/541f3a2781de481bb84883889e4d9f0904250a56/plugin/lspconfig.lua#L45-L47 Which doesn't return all servers (e.g., `null-ls`), so it doesn't close all LSP clients.
- If the server with the given `server_id` is **attached**:
- The correct LSP …
=> fix: LspStop correctly closes lsp servers and notifies users

.github/ISSUE_TEMPLATE/bug_report.yml, doc/configs.md, doc/configs.txt, lua/lspconfig/configs/hls.lua, lua/lspconfig/health.lua
`config.lspinfo` is an undocumented feature that allows extending the info shown in `:LspInfo` (`:checkhealth lspconfig`). This feature is unwanted because:
- it's undocumented
- it adds a maintenance burden
- it provides info that should be derived from the LSP client or server, in a [generalized way](https://github.com/neovim/nvim-lspconfig/issues/3376).
- Remove support for `config.lspinfo`.
- Instead, `:LspInfo` (`:checkhealth lspconfig`) should be enhanced to automatically gather this kind of extra info from the server response. https://github.com/neovim/nvim-lspconfig/issues/3376
=> feat(lspinfo): print "{cmd} --version", drop config.lspinfo

lua/lspconfig/health.lua
Problem:
version is only printed for make_config_info.
Solution:
Add it to make_client_info.
Really fucking irritating that these functions do not share code...
=> feat(lspinfo): also show version in make_client_info

lua/lspconfig/health.lua
*TODO: should this be upstreamed to `:checkhealth vim.lsp` ?*
- improve version handling: try `--version`, `-v`, etc.
- omit "custom handlers" if none found
=> refactor(lspinfo): deduplicate code, improve formatting

lua/lspconfig/health.lua
Add support for the `gopls version` command. It only works if it is the first one that is tried. I am not sure if this breaks other tools. Maybe need to add a version command to each LSP config?
Before
```
- Client: gopls (id: 2, bufnr: [13])
filetypes:         go, gomod, gowork, gotmpl
cmd:               ~/.local/share/nvim/mason/bin/gopls
version:           `flag provided but not defined: -version  gopls is a Go language server.  It is typically used with an editor to provide language features. When no command is specified, gopls will default to the 'serve' command. The language features can also be accessed via the gopls command-line interface.  Usage:   gopls help [<subject>]  Command:  Main                   serve             run a server for Go code using the Language Server …
```
=> fix(health): support gopls version command

lua/lspconfig/health.lua
Problem:
`cmd` may be a random function instead of an executable command.
ERROR Failed to run healthcheck for "lspconfig" plugin. Exception:
.../lua/lspconfig/health.lua:127: attempt to index field 'cmd' (a function value)
Solution:
Skip attempt to invoke `<cmd> --version` if `cmd` is a function.
=> fix(health): "attempt to index cmd (function)"

lua/lspconfig/configs/lua_ls.lua
Due to #3322, when neither a `/lua` directory or `.git` root dir exists, the empty (and invalid) `''` root dir was returned.
Instead it should return `nil` so that single-file mode can trigger instead.
=> fix(lua_ls): when neither lua or git root found, return nil. See #3322

lua/lspconfig/configs/ada_ls.lua
The configuration for the Ada Language Server was first added in #171 and removed in #3310. The removal happened due to misunderstandings, it was thought at the time that the default language server configuration could not work on its own (#1683), it turns out that this was actually caused by a bug in the ALS that was fixed a long time ago. This means the default ALS configuration can be re-introduced.
However, in the meantime, a new neovim plugin for Ada was created by and the name "als" was borrowed, thus we have to use a new name, ada_ls, in order to avoid breaking this plugin.
This reverts commit 7b8b0b3ddd0ed6eddc93982753acaddc578defac.
=> feat: ada_ls

lua/lspconfig/health.lua
Problem:
version fails for jdtls
Solution:
Try `-version` (one hyphen). Drop `-v`, it's probably not useful. Also drop `-h` because it is unlikely to work if `--help` didn't work.
TODO: make a smarter guess about the actual "argv0" of `cmd`.
=> fix(health): version fails for jdtls

lua/lspconfig/health.lua
Problem:
"root directory" not reported.
Solution:
report root_dir. regression from b55b9659de9ac17e05df4787bb023e4c7ef45329
=> fix(health): "root directory" not reported

lua/lspconfig/configs/dprint.lua
`dprint` is also a formatter for GraphQL files.
=> fix(dprint): add graphql to filetypes

lua/lspconfig/configs.lua
It takes a new_root_dir parameter as documented in the help docs.
=> fix: correct type annotation on lspconfig.Config::on_new_config

lua/lspconfig.lua
`ruff server` has been stable for some time now. Related to:
- #3241
=> chore(ruff_lsp): deprecate ruff_lsp in favour of ruff

lua/lspconfig/configs/nextflow_ls.lua
This adds a configuration for the official language server for the Nextflow scientific pipeline language.
This language server is relatively new, but is part of an initiative to modernize their editor language support. It is an industry standard tool for developing scientific pipelines especially in the epidemiology/genomics community both academic and industry. It is an officially supported project by the language's organization so I'm hoping that is enough to vet it for getting added.
=> feat: add the official Nextflow Language Server (`nextflow_ls`)

lua/lspconfig/configs/texlab.lua
Problem: vim.lsp.buf.execute_command has been deprecated
For more info see #3426.
=> fix(texlab): use exec_cmd method

lua/lspconfig/configs/ruby_lsp.lua
Ruby LSP has added support for ERB documents: https://shopify.github.io/ruby-lsp/#erb-support
I think it would be nice to add the filetype eruby to the ruby_lsp server config
=> Add support using erb files to ruby-lsp

plugin/lspconfig.lua
Problem: client id and name are separated by spaces, which may cause misunderstanding.
Solution: use colon combine as one thing.
Relate #3419
=> fix: fmt client id with name in complete of LspStop

lua/lspconfig/configs/vale_ls.lua
Vale supports parsing reStructuredText files, as documented here: https://vale.sh/docs/topics/scoping/#restructuredtext
It uses rst2html in the background.
=> feat(vale_ls): add reStructuredText to filetypes

README.md, doc/lspconfig.txt, plugin/lspconfig.lua
- `:LspStop` doesn't support list of client ids or config names.
- `:LspRestart` doesn't support config names although supports list of client ids
- Command completion uses ids and names, not allowing the user to hit enter immediately after
finding the desired server
- Unify `LspStop` and `LspRestart` implementation supporting lists of client ids and
config names
- Command completion only returns config names
- Modify docs
=> feat: allow list of client ids or config names in LspRestart and LspStop

lua/lspconfig/configs/clangd.lua, lua/lspconfig/configs/texlab.lua
Adapt to the upstream change https://github.com/neovim/neovim/commit/629483e24eed3f2c07e55e0540c553361e0345a2 to get rid of the warning message "warning: offset_encoding is required, using the offset_encoding from the first client".
=> fix: offset_encoding is required now in `make_position_params`

doc/lspconfig.txt, lua/lspconfig/configs.lua, lua/lspconfig/manager.lua
This PR replaces the usage of `vim.lsp.start_client` by `vim.lsp.start`, delegating the logic of client reuse to the editor.
Also adding support for a `silent` option to prevent error notifications on init.
=> refactor: use vim.lsp.start instead of vim.lsp.start_client

lua/lspconfig/manager.lua
if existing_client does not support workpaceFolder should spawn a new server instance
=> fix: check existing_client support workspaceFolder

lua/lspconfig/manager.lua
Using method string instead constant avoid nil error in low release version
Fix #3467
=> fix: using method string instead constant

lua/lspconfig/util.lua
This makes it easier to assess how much functionality still needs to be deprecated.
=> refactor: group deprecated functions at the end

lua/lspconfig/configs/fennel_ls.lua, lua/lspconfig/configs/turtle_ls.lua, lua/lspconfig/util.lua, scripts/docgen.lua
The vimscript function `getftype` is an easier way to check for file
existence compared to vim.uv.
=> refactor: use simpler file existence check

lua/lspconfig/configs/fennel_ls.lua
`fennel-ls` will not load when a configuration file is not present, i.e. `flsproject.fnl`. This fixes that by adding `single_file_support`.
This PR addresses comments on from my [first attempted PR](https://github.com/neovim/nvim-lspconfig/pull/3389).
* Add `single_file_support` to `fennel-ls`.
=> fix(fennel-ls): enable single_file_support

.github/ci/run_sanitizer.sh, lua/lspconfig/configs.lua, lua/lspconfig/configs/eslint.lua, lua/lspconfig/configs/gitlab_ci_ls.lua, lua/lspconfig/configs/intelephense.lua, lua/lspconfig/configs/jdtls.lua, lua/lspconfig/configs/julials.lua, lua/lspconfig/configs/lua_ls.lua, lua/lspconfig/configs/phan.lua, lua/lspconfig/configs/phpactor.lua, lua/lspconfig/configs/r_language_server.lua, lua/lspconfig/configs/rnix.lua, lua/lspconfig/configs/smarty_ls.lua, lua/lspconfig/configs/vdmj.lua, lua/lspconfig/health.lua, lua/lspconfig/manager.lua, lua/lspconfig/util.lua, plugin/lspconfig.lua, scripts/docgen.lua
We still support neovim 0.9 currently, so we can't use vim.uv. Also add
a check so we don't accidentally reintroduce it.
=> refactor: replace all instances of vim.uv with vim.loop

lua/lspconfig/configs.lua
This PR fixes the types of `vim.lsp.ClientConfig` `commands`
The current definition comes from [neovim](https://github.com/neovim/neovim/blob/ae93c7f369a174f3d738ab55030de2c9dfc10c57/runtime/lua/vim/lsp/client.lua?plain=1#L80-L84)
```lua
--- @field commands? table<string,fun(command: lsp.Command, ctx: table)>
```
fails validation when passed to `nvim-lspconfig` [here](https://github.com/neovim/nvim-lspconfig/blob/1aa9f36b6d542dafc0b4a38c48969d036003b00a/lua/lspconfig/configs.lua?plain=1#L87)
follow up to: [neovim/neovim #31351](https://github.com/neovim/neovim/pull/31351)
=> fix(types): lspconfig.Config commands

lua/lspconfig.lua
Problem: typst_lsp has been archived.
Solution: use tinymist instead
Fix #3492
=> fix(typst_lsp): deprecate typst_lsp to tinymist

.github/ci/run_sanitizer.sh, doc/lspconfig.txt, lua/lspconfig/configs/angularls.lua, lua/lspconfig/configs/astro.lua, lua/lspconfig/configs/glint.lua, lua/lspconfig/configs/mdx_analyzer.lua, lua/lspconfig/configs/relay_lsp.lua, lua/lspconfig/configs/rome.lua, lua/lspconfig/configs/tailwindcss.lua, lua/lspconfig/configs/volar.lua, lua/lspconfig/util.lua
=> refactor: deprecate util.find_node_modules_ancestor

doc/lspconfig.txt, lua/lspconfig/configs/gdscript.lua, lua/lspconfig/health.lua, plugin/lspconfig.lua
Lspconfig requires neovim version 0.9 at the time of writing this, so
discard any version checks and code for older versions.
=> refactor: remove outdated code

lua/lspconfig/configs/tinymist.lua
When the `root_dir` is null, tinymist should still runs to give a baseline usage.
Ref: #3094 in this PR the modify of `root_dir` is rejected, but set single file support field to true looks just fine.
=> fix(tinymist): fallback to single file in some case

lua/lspconfig/util.lua, test/lspconfig_spec.lua
=> refactor!: remove util.path.escape_wildcards

lua/lspconfig/util.lua, test/lspconfig_spec.lua
=> refactor!: remove util.path.is_absolute

lua/lspconfig/configs/crystalline.lua, lua/lspconfig/configs/janet_lsp.lua, lua/lspconfig/configs/ruff.lua, lua/lspconfig/configs/ruff_lsp.lua
fixes #3512 
the issue was that `util.root_pattern` returns a function, which i believe is intended to be called with fname as its argument.
this causes root_dir to return a funcref when called which causes the attached issue as well as causing an error on LspStart ruff.
=> fix ruff and ruff_lsp returning a function from root pattern

lua/lspconfig/configs/msbuild_project_tools_server.lua
Current default filetypes for `msbuild_project_tools_server` are not builtin from neovim, this PR adds instruction to register filetype for attaching to different types of msbuild file.
=> feat(msbuild): config instruction for filetypes

.github/ci/run_sanitizer.sh, lua/lspconfig/configs/apex_ls.lua, lua/lspconfig/configs/astro.lua, lua/lspconfig/configs/cadence.lua, lua/lspconfig/configs/drools_lsp.lua, lua/lspconfig/configs/eslint.lua, lua/lspconfig/configs/foam_ls.lua, lua/lspconfig/configs/gitlab_ci_ls.lua, lua/lspconfig/configs/glint.lua, lua/lspconfig/configs/jdtls.lua, lua/lspconfig/configs/jsonnet_ls.lua, lua/lspconfig/configs/mdx_analyzer.lua, lua/lspconfig/configs/relay_lsp.lua, lua/lspconfig/configs/rust_analyzer.lua, lua/lspconfig/configs/turtle_ls.lua, lua/lspconfig/configs/vala_ls.lua, lua/lspconfig/configs/vdmj.lua, lua/lspconfig/configs/volar.lua, lua/lspconfig/util.lua, scripts/docgen.lua, test/lspconfig_spec.lua
=> refactor: deprecate util.path.join

lua/lspconfig/configs/glint.lua, lua/lspconfig/configs/relay_lsp.lua, lua/lspconfig/util.lua
=> refactor: deprecate util.path.path_separator

.github/ci/run_sanitizer.sh, lua/lspconfig/util.lua
=> refactor: deprecate util.path.iterate_parents

.github/ci/run_sanitizer.sh, lua/lspconfig/util.lua
=> refactor!: remove public interface of util.path.traverse_parents

lua/lspconfig/configs/mdx_analyzer.lua
In #3496, astro ls and volar lsp was fixed for having duplicate node_modules folder, but mdx-analyzer doesn't. This pr fixes that. Not only that, the `filetypes` option had `markdown.mdx`, but now vim.bo.filetype returns `mdx`, thats fixed also.
=> fix(mdx-analyzer): Duplicate node_modules folder causing errors, and filetypes option.

lua/lspconfig/configs/cue.lua
This PR adds support for the CUE language (https://github.com/cue-lang/cue) by integrating its official language server protocol implementation (`cue lsp`).
Background:
- Previously, CUE language support was provided through Dagger's LSP implementation, which has since been discontinued
- CUE is gaining significant adoption, with over 5.2k GitHub stars
- Notable projects like Timoni (https://github.com/stefanprodan/timoni) are embracing CUE for configuration management
This change ensures continued and improved CUE support through the official, maintained language server.
=> feat: cue language server

lua/lspconfig/configs/ccls.lua
ccls 0.20241108 has added support for the extension from clangd.
=> feat(ccls): add CclsSwitchSourceHeader

lua/lspconfig/configs/ccls.lua
Problem: method prefix is textDocument
Solution: make d to upper
=> fix(ccls): typo on request method

lua/lspconfig/configs/ccls.lua, lua/lspconfig/configs/clangd.lua
refactor switchsourceheader request in clangd
cc @MaskRay
=> refactor(clangd): imporve switchsourceheader handler

lua/lspconfig/configs/clangd.lua
The previous patch to this file (88c4c042e1e59f992e4c7aff3531033047b3aa9c) changed the string to 'ccls' (possibly by copy-paste error).
=> fix(clangd): fix switchSourceHeader detection

lua/lspconfig/configs/ruby_lsp.lua
The best practice is to have the gem installed globally, and then ruby-lsp will set up it's own Gemfile and manage it's own version.
=> docs(ruby_lsp): Remove instructions for adding ruby-lsp to Gemfile

lua/lspconfig/configs/powershell_es.lua
https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules#implicit
>If you place a settings file named PSScriptAnalyzerSettings.psd1 in your project root, PSScriptAnalyzer discovers it
=> fix(powershell_es): add root pattern

lua/lspconfig/configs/selene3p_ls.lua, lua/lspconfig/configs/stylua3p_ls.lua
Per title. These servers make it possible to not need plugins like null-ls or none-ls if those are only used for lua tools.
=> Feat: add lua 3rd party language servers

lua/lspconfig/configs/gh_actions_ls.lua
---
title: 'add GitHub Actions language server'
---
Closes #2737
=> feat: gh-actions-language-server

lua/lspconfig/configs/gh_actions_ls.lua
cc @disrupted 
This saves the user the extra setup work of copypasting the `vim.filetype.add` snippet, making this language server work out of the box.
Follow-up to #3551, on this suggestion: https://github.com/neovim/nvim-lspconfig/pull/3551/files#r1912833011
=> feat(gh_actions_ls): use `root_dir` to decide whether to attach

lua/lspconfig/configs/gh_actions_ls.lua
I believe this is another case of #3513
=> fix(gh_actions_ls): correctly call util.root_pattern

lua/lspconfig/configs/alloy_ls.lua
This PR adds support for the Alloy language (https://github.com/AlloyTools/org.alloytools.alloy) by integrating its official language server (`alloy lsp` or `java -jar alloy6.2.0.jar lsp`).
Alloy is a well-known formal specification language and model checker, used for describing and exploring structures and systems.
=> feat: Alloy language server

doc/configs.md, lua/lspconfig/configs/gh_actions_ls.lua
The projects [forgejo](https://forgejo.org/) and [gitea](https://about.gitea.com/) share the same syntax even across the composite actions.
There are only negligible differences IMHO which besides the actions author should be aware of.
Besides its only a matter of time until those become implemented as well.
It'd be a nice addition to let it attach for those systems as well
=> refactor(gh_actions_ls): allow .forgejo and .gitea as root_dir

lua/lspconfig/configs/yamlls.lua
The `instrumenta/kubernetes-json-schema` repo is apparently dead: https://github.com/instrumenta/kubernetes-json-schema/issues/32#issuecomment-1021133568 And nobody has the credentials anymore to archive it: https://github.com/instrumenta/kubeval/issues/268#issuecomment-1376490498 The recommended migration from instrumenta is to https://github.com/yannh/kubeconform, see (https://github.com/instrumenta/kubernetes-json-schema/issues/32#issuecomment-1021133568) and the recommended `kubernetes-json-schema` fork is also from the same new maintainer: https://github.com/yannh/kubernetes-json-schema/
=> docs: Use a maintained fork for `kubernetes-json-schema` in the example

Makefile
Otherwise it will print out all the files that passes which makes it
extremely tedious as you need to search for the files that failed.
=> build: add -q flag to luacheck

.github/workflows/lint.yml
Otherwise the action will default to githubs own merge branch which
doesn't follow the actual git history.
=> ci: use the head ref when checking out

.github/workflows/docgen.yml, scripts/docgen.lua, scripts/docgen.sh
Instead, generate documentation by running the `docgen.lua` executable.
=> build: remove `docgen.sh`

lua/lspconfig/configs/gh_actions_ls.lua
=> fix(gh_actions_ls): Fix incorrect rootdir resolution

lua/lspconfig/configs.lua
This is because using the old syntax for vim.validate causes
`:checkhealth vim.deprecated` to be flooded with deprecated messages.
It would also be possible to do a version check and use the newer syntax
for vim.validate, but since configs.lua will be replaced by
vim.lsp.config in the future there is little need to future-proof it.
Closes https://github.com/neovim/nvim-lspconfig/issues/3583.
=> fix: remove validation from configs.lua

lua/lspconfig/configs/astro.lua, lua/lspconfig/configs/volar.lua
The issue occurred because the path generated by the `get_typescript_server_path` function omitted the `node_modules` folder, causing failures when initializing the TypeScript LSP client:
Error: "Can't find typescript.js or tsserverlibrary.js in .../typescript/lib"
The function was updated to correctly include `node_modules` in the path. Now, the generated path is valid, and the LSP client works without issues.
=> fix(astro,volar): correct 'typescript/lib' path for TypeScript LSP initialization

lua/lspconfig/configs/oxlint.lua
This pull request adds the minimal working config for [`oxlint`](https://oxc.rs) [github](https://github.com/oxc-project/oxc).
The configuration is highly inspired by the `biome` config. The `oxc_language_server` binary is part of the `oxlint` package (It has 2 binaries, `oxlint` and `oxlint_language_server`).
Sadly I was unable to generate the config.md and config.txt docs files. After executing the command in CONTRIBUTING.md, I got no error and the file was unchanged...
Related to #3062
=> feat: oxc-language-server

lua/lspconfig/configs/angularls.lua
Problem:
Causes warning message while opening a directory without node modules
=> fix(angularls): handle nil while checking angular core version

lua/lspconfig/configs/rust_analyzer.lua
Generated documentation is only available in the release branch of rust-analyzer, so the current link leads to a 404.
=> docs: fix broken documentation link in rust_analyzer config

lua/lspconfig/configs/harper_ls.lua
In automattic/harper#495, we're adding support for two new languages: `php` and `dart`. This PR adds those file types and updates links that changed as a result of the [Harper acquisition.](https://techcrunch.com/2024/11/21/wordpress-com-owner-automattic-snaps-up-grammar-checker-harper/)
This will remain a draft until that PR is merged.
=> feat(harper-ls): added new languages and updated links

lua/lspconfig/configs/angularls.lua
Use the correct binary on windows, otherwise the server won't start.
=> fix(angularls): use correct executable on windows

lua/lspconfig/configs/dts_lsp.lua
The dts-lsp server does not meet the requirement of having 100 stars on its GitHub repository or VSCode extension. Additionally, I have no affiliation with it. I originally created this configuration for personal use and am sharing it in case others find it useful.
=> feat: dts-lsp

lua/lspconfig/health.lua
Problem:
LspInfo returns '?' for version string when using the codeqlls language server. This is because codeql is slow to return its version number due to the underlying JVM.
Solution:
Increase the timeout from 300ms to 500ms.
1000 iterations of `codeql version` resulted in (349 +- 13) ms which informed the choice of 500ms.
=> fix(health.lua): increased version check cmd timeout

lua/lspconfig/configs/wasm_language_tools.lua
This PR adds [wasm-language-tools](https://github.com/g-plane/wasm-language-tools) which contains a language server for WebAssembly Text Format.
=> feat: add wasm-language-tools

lua/lspconfig/configs/lua_ls.lua
.luarc is created by lua-lsp itself (e.g. if you hit "disable diagnostics" in a code action), at which point the lsp will start showing errors that the `vim` global is undefined after the next restart.
=> don't skip VIMRUNTIME in lua lsp if ~/.config/nvim/.luarc.json exists

lua/lspconfig/configs/oxlint.lua
This pull request adds the `OxcFixAll` command for basic `--fix` functionality. (as mentioned in https://github.com/neovim/nvim-lspconfig/pull/3586#issuecomment-2613930725)
Note this functionality was added to the language server very recently (https://github.com/oxc-project/oxc/pull/8858) and only works with `oxc_language_server` >=`0.15.10`. (Still not in mason-registry, see https://github.com/mason-org/mason-registry/pull/8717)
=> feat(oxc_language_server): add OxcFixAll command

lua/lspconfig/configs/nushell.lua
nushell 0.102 made some changes that a nil `root_dir` will cause lsp server to exit.
This PR tries to mitigate the problem by providing a fallback `root_dir` value.
=> fix(nushell): root_dir should avoid returning nil

lua/lspconfig/configs/veridian.lua
The heading level of veridian in configs.md is fixed.
=> docs: heading levels for veridian fixed

lua/lspconfig/configs/r_language_server.lua
[Quarto](https://quarto.org/) is a (more or less new) scientific and technical publishing system. There is also a [quarto filetype](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/quarto.vim) which is very similar to [rmarkdown](https://rmarkdown.rstudio.com/) but has some extensions.
The quarto filetype can also be used with python and julia. The r_language_server detects code chunks / blocks that use the R programming language and runs only on them.
=> feat(r_language_server): add quarto filetype

lua/lspconfig/configs/eslint.lua
Problem:
os.execute misinterprets quoted url as window title
Solution:
add an empty title argument
=> fix(eslint): update openDoc os call for windows

lua/lspconfig/configs/lua_ls.lua
This commit doesn't address the case when root path == vim.env.HOME as the case lack return when it's true (#2110)
Fix #3508
=> fix(lua_ls): return longest root path

lua/lspconfig/configs/lua_ls.lua
There is no good reason to have it as a root marker and it makes the
configuration super convoluted. It breaks on even basic setups: opening
`src/nvim/generators/hashy.lua` in the neovim repo causes `src/nvim` to
be the root since there's a `lua` folder there. Instead, just make the
root a flat set of markers and let users who look for a more advanced
setup to adjust it in their own configurations.
=> fix!: remove `lua` as root marker

lua/lspconfig/configs/sourcekit.lua
Problem:
nvim doesn't recognize that sourcekit supports `textDocument/diagnostic` requests, causing it to rely on `textDocument/publishDiagnostics`, which results in delayed diagnostics.
Solution:
Manually configure `client.server_capabilities.diagnosticProvider` in `on_init` to enable `textDocument/diagnostic` support. Override the `textDocument/publishDiagnostics` handler to prevent duplicate diagnostics. 
fix neovim/neovim#31873
~~I'm not sure if there's a way to configure `server_capabilities` without `on_init` :sweat_smile:~~
=> fix(sourcekit): use textDocument/diagnostic over publishDiagnostics

doc/configs.md, doc/configs.txt, scripts/docgen.lua
When `root_dir` is not defined as a function, the generated docs show the paths resolved in the CI env:
root_dir : lua "/home/runner/work/nvim-lspconfig/nvim-lspconfig"
Always show the "gF" message for `root_dir`, even if it is not a function.
Fix #3628
=> fix(docgen): root_dir doc shows paths from CI env

lua/lspconfig/configs/bacon_ls.lua
Changed `settings` to `init_options`, as per `bacon-ls` readme.
=> Update bacon_ls.lua to reflect new configuration

lua/lspconfig/configs/bazelrc_lsp.lua
The bazelrc-lsp binary added other sub-commands besides the `lsp` functionality (e.g., `bazelrc-lsp format` can be used to format files from the command line). This commit updates the config such that the `bazelrc-lsp lsp` is explicitly invoked. (Currently, `bazelrc-lsp` still defaults to the `lsp` sub-command, but this default will likely be removed in a future version)
=> chore(bazelrc_lsp): Invoke `lsp` subcommand explicitly

lua/lspconfig/configs/postgres_lsp.lua
This PR fixes the command for the postgresql_lsp server.
The current configuration uses only `postgresql_lsp` as the command, but the server 
requires an additional `lsp-proxy` argument to work correctly. This change updates 
the command to use both the executable name and the required argument.
I've tested this configuration and confirmed it resolves the "command not found" 
issues and allows the LSP to work correctly.
=> fix(postgresql_lsp): update command to use lsp-proxy argument

lua/lspconfig/configs/gleam.lua
Seems the description got cut of somehow(?) and went unnoticed in #2266.
=> gleam: fix broken installation description

lua/lspconfig/configs/tailwindcss.lua
Currently, the Tailwind CSS language server is enabled for any workspace containing a `.git` folder, a `node_modules` folder, or a `package.json` file, which is not ideal. This PR introduces a specific check for the `tailwindcss` package within `package.json` file using `insert_package_json` method from `util` (this approach is used in `eslint` config). Since the latest version of Tailwind CSS (v4) no longer requires `postcss.config.*` and `tailwind.config.*` files, these can no longer be relied upon as sole criteria for enabling Tailwind CSS LSP.
=> fix(tailwindcss): improved tailwindcss detection

lua/lspconfig/configs/ltex_plus.lua
Problem: LSP not working with latex files. Spell checking skipped in latex files
Solution: Add latex to the enabled section because even though 'tex' is the filetype the language ID is 'latex'
=> fix(ltex_plus): add latex to `enabled` settings

lua/lspconfig/configs/biome.lua
Biome configuration files (`biome.json`, `biome.jsonc`) are [not required](https://biomejs.dev/guides/configure-biome/#configuration-file-resolution) for Biome to function within a project. If no configuration file is present, Biome defaults to its built-in settings. Therefore, I suggest to check for the Biome package in the `package.json` file in addition to looking for configuration files.
=> fix(biome): improved biomejs detection

lua/lspconfig/configs/golangci_lint_ls.lua
`--out-format=json` was replaced by `--out.json.path=stdout`
https://github.com/golangci/golangci-lint/blob/86cc7c6bfbe4d6ca515f9c45b58cfa03cfd0c3da/docs/src/docs/product/migration-guide.mdx#command-line-flags
=> feat: upgrade for golangci-lint v2

README.md, doc/lspconfig.txt, lua/lspconfig/health.lua, plugin/lspconfig.lua
Problem:
`:checkhealth lspconfig` has no benefits vs `:checkhealth vim.lsp`.
Solution:
- on Nvim 0.11+, `:LspInfo` is an alias to `:checkhealth vim.lsp` instead of `:checkhealth lspconfig`.
- `lua/lspconfig/health.lua` will be removed in a few months.
fix #3453
fix #3509
=> feat: alias `:LspInfo` to `:checkhealth vim.lsp`

lua/lspconfig/configs/vectorcode_server.lua
vectorcode-server is the LSP frontend for [vectorcode](https://github.com/davidyz/vectorcode), a code repository indexing tool that provides extra context for LLM. The upstream project has 180+ stars at the time of this PR.
I've gone through CONTRIBUTING.md and several other PRs about adding new configs, and there seems to be some reviews against the use of `utils.root_pattern` but the example in CONTRIBUTING.md is still using it, so I left it as is. If there's a particular reason that this should be changed to `vim.fs.root`, please let me know and I'll change it.
=> feat: vectorcode-server

lua/lspconfig/configs/postgres_lsp.lua
Do not require a `postgrestools.jsonc` file in the root directory for single file support.
Fixes #3672.
=> fix(postgres_lsp): re-enable single file support

lua/lspconfig/configs/sourcekit.lua
1. the URL is outdated, repo owner is now `swiftlang`
2. this guide from `swift.org` recommends to always add `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true`. 
I am not a Swift dev—I just wanted to quickly enable the LSP to go through a Swift project—but seeing that it's the official Swift website that recommends this, I assume it does make sense to add it to the default config.
=> fix(sourcekit): URL & add dynamic reg. for `didChangeWatchedFiles`

lua/lspconfig/configs/tblgen_lsp_server.lua
The `tblgen_lsp_server` doesn't seem to load any specific compilation database server and hence we need to explicitly specify the command-line argument to pick the correct database path.
=> fix(tblgen): find tablegen_compile_commands.yml

lua/lspconfig/configs/eslint.lua
Fixes #3685, where projects with different ESLint versions incorrectly used the farthest version instead of the closest.
=> fix(eslint): Find closest ESLint directory to avoid version mismatch

lua/lspconfig/util.lua
these are only used by the old health.lua, which only exists for back-compat.
cc @dundargoc
=> refactor: deprecate util functions

doc/lspconfig.txt, lua/lspconfig/util.lua
These are special-purpose functions that should never have been "public".
=> refactor: deprecate add_hook_before/after

doc/lspconfig.txt
Begin referencing `vim.lsp.config()` in some places.
Most of the docs can be fully removed after completing the migration to `vim.lsp.config()`. #3494
=> docs: cleanup

lua/lspconfig/configs/rpmspec.lua
rpm-spec-language-server is the Language Server for RPM spec files
https://github.com/dcermak/rpm-spec-language-server
=> feat: rpmspec

lua/lspconfig/configs/bqls.lua
Adds support for BigQuery language server.
thanks @kitagry
=> feat(bqls): Add bqls support

lua/lspconfig/configs/stylelint_lsp.lua
Update missing root_file and filetypes for the stylelint lspconfig. https://github.com/neovim/nvim-lspconfig/issues/3700
=> stylelint config update

.github/ci/run_sanitizer.sh, doc/configs.md, doc/configs.txt, lua/lspconfig/configs.lua, lua/lspconfig/configs/angularls.lua, lua/lspconfig/configs/eslint.lua, lua/lspconfig/configs/fennel_ls.lua, lua/lspconfig/configs/foam_ls.lua, lua/lspconfig/configs/gitlab_ci_ls.lua, lua/lspconfig/configs/intelephense.lua, lua/lspconfig/configs/jdtls.lua, lua/lspconfig/configs/julials.lua, lua/lspconfig/configs/lua_ls.lua, lua/lspconfig/configs/phan.lua, lua/lspconfig/configs/phpactor.lua, lua/lspconfig/configs/r_language_server.lua, lua/lspconfig/configs/relay_lsp.lua, lua/lspconfig/configs/rnix.lua, lua/lspconfig/configs/smarty_ls.lua, lua/lspconfig/configs/turtle_ls.lua, lua/lspconfig/configs/vdmj.lua, lua/lspconfig/health.lua, lua/lspconfig/manager.lua, lua/lspconfig/util.lua, plugin/lspconfig.lua, scripts/docgen.lua
I noticed #3483 is about supporting 0.9, and the main branch now requires 0.10. This is a rote find-replace of `vim.loop`, so please judge it harshly.
See: https://github.com/neovim/neovim/blob/v0.10.0/runtime/doc/deprecated.txt#L55
=> refactor: replace all instances of vim.loop with vim.uv

lsp/typos_lsp.lua, lua/lspconfig/configs/typos_lsp.lua
typos via typos-lsp supports [pyproject.toml and Cargo.toml as config files](https://github.com/crate-ci/typos/blob/a557d1af98a669f0f26f04854a81485f53437a11/docs/reference.md#sources):
> Search parents of specified file / directory for one of typos.toml, _typos.toml, .typos.toml, Cargo.toml, or pyproject.toml
Resolves https://github.com/tekumara/typos-lsp/issues/180
=> feat(typos-lsp): support pyproject.toml and Cargo.toml

lsp/gh_actions_ls.lua
`gh_actions_ls` is missing in the `lsp` folder, likely due to it using a workaround with single file support to prevent it from attaching to every yaml file, even though it should only attach to certain yaml files, without defining an extra `yaml.github` filetype (see #3558).
Using `.github/workflows` and co as `root_markers` however prevents this issue, allowing us to use the LSP like a regular LSP without it attaching to unrelated yaml files. Thus, there is no anymore problem using `git_actions_ls` with `vim.lsp.config`.
cc @disrupted
=> feat(gh_actions_ls): add `vim.lsp.config` support

lsp/biome.lua
Another one to check off the list at #3705.
`single_file_support = false` was introduced in PR #2984. 
As far as I can tell, it is not relevant anymore: when using `vim.lsp.config`'s `root_markers`, the LSP is simply not attached when the root marker is not found, so the problem that #2984 was solving does not occur.
=> feat(biome): add `vim.lsp.config` support

lua/lspconfig/util.lua
The escape_wildcards function was enhanced to handle a broader range of special characters that could cause issues when used in pattern matching. This includes additional wildcards, pattern matching characters, shell special characters, the escape character itself, and whitespace.
I faced this issue when I work on React Router and Tanstack 	Router.
They adapt file-based routing, and they use special characters like `$` as filename.
https://reactrouter.com/how-to/file-route-conventions#optional-segments
Before this fix, it takes like 15 seconds to open files like `foo.$.ts`, but this fixes!
=> fix: improve path escaping in wildcard function

lsp/biome.lua
Follow up to #3718. Re-adds `lsp/biome.lua` correctly with `workspace_required = true` (though this will only start to work from 0.11.1 on, or on nightly.)
Now also with the `root_dir` func checking for biome being in the package.json (cc @maximtrp).
=> feat(biome): `vim.lsp.config` support, with `workspace_required` and proper `root_dir`

lua/lspconfig/util.lua
Reverts neovim/nvim-lspconfig#3690
see https://github.com/neovim/nvim-lspconfig/pull/3690#issuecomment-2805154318
=> Revert "fix: improve path escaping in wildcard function"

lsp/zls.lua
Disclaimer: i'm a zig newb and i'm not up to speed on the planned direction for `nvim` and `vim.lsp.config`. Would appreciate some review to make sure i'm not overlooking  anything. This does seem to work fine in my limited testing though i.e. making sure the lsp starts up in some random projects and the functionality works, and that `checkhealth vim.lsp` looks fine.
Includes the following changes from the legacy config:
- Use `root_markers` instead of `root_dir` 
- This removes the dependency on `util`
- Remove `on_new_config`
- I wasn't sure what/if to replace this. I took a look at what was done for `omnisharp`, which was listed in #3705 and has been ported/merged and it doesn't appear to have an equivalent there so I am assuming it's fine to leave this out
- Replace …
=> feat(zls): add `vim.lsp.config` support

README.md
it seems that github will remove the dots in anchor link, this pr update the ref href to reduce confusion.
=> update vim.lsp.config anchor link href

lsp/astro.lua
Problem: hardcord path symbol in get_typescript_server_path
Solution: using vim.fs.joinpath to concat path
=> fix(astro): using vim.fs.jointhpath concat path

lsp/volar.lua
This PR crosses volar from https://github.com/neovim/nvim-lspconfig/issues/3705
Seems to work for me on one of my projects at least
=> feat(volar): add vim.lsp.config support

README.md
Problem:
Some anchor links were defined as #vim.lsp.config which doesn't work
Solution:
Fix anchor link to #vimlspconfig
=> fix(readme): update vim.lsp.config anchor links

README.md
Now that vim.diagnostic.goto_prev() and vim.diagnostic.goto_next() have been deprecated, update the README with up-to-date information.
More info can be found here:
https://neovim.io/doc/user/deprecated.html#deprecated-0.11
=> docs: update README.md for diagnostic mappings

lsp/atlas.lua
Following #3539, this PR adds a new `atlas-rule` file type.
Note: only the documentation needs to be updated
=> feat(atlas): update doc support for `atlas-rule` filetype

.github/ci/lint.sh, .github/workflows/lint.yml, CONTRIBUTING.md, lsp/basedpyright.lua, lsp/denols.lua, lsp/pyright.lua, lsp/texlab.lua, lsp/zk.lua, scripts/docgen.lua
Use `client:exec_cmd()` instead of calling `request("workspace/executeCommand")` directly.
=> lint: client:exec_cmd()

lsp/tailwindcss.lua
This PR enhances root directory detection for the latest versions of TailwindCSS (v4), which no longer require `tailwind.config.*` or `postcss.config.*`. This improvement was previously merged in #3648, but was missing in https://github.com/neovim/nvim-lspconfig/pull/3751#issuecomment-2819336315
=> fix(tailwindcss): improved root dir detection for tailwind v4

lsp/unocss.lua
unocss is a css utility library similar to tailwind which requires configuration files and the package to be installed to work with. 
Otherwise it will throw an error:
> Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:551: RPC[Error] code_name = InternalError, message = "Request initialize failed with message: Cannot read properties of null (reading '0')"
stack traceback:
[C]: in function 'assert'
/usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:551: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
Thus set `workspace_required ` to `true`.
=> fix(unocss): add `workspace_required` to `true`

lsp/gnls.lua
Add support for Microsoft's GN language server [1].
[1] https://github.com/microsoft/gnls
=> feat: Add gnls config

lsp/roslyn_ls.lua
without this change the roslyn_ls can only operate on the current file and e.g. `gd` do not work properly.
=> fix(roslyn_ls): use absolute paths when open `.sln` and `.csproj` files

lsp/ts_ls.lua
This handler is used when performing certain code actions such as extracting functions or types. The language server asks the editor to prompt for a rename for the newly created function or type.
=> feat(ts_ls): add _typescript.rename handler

lsp/ts_ls.lua
Source actions are code actions that apply to the whole file. They are not exposed via `vim.lsp.buf.code_action()` and must be requested explicitly.
=> feat(ts_ls): provide command to run source actions

lsp/pylyzer.lua
Pylyzer requires Erg as dependency. This info is missing in default config and doc.
=> fix: add pylyzer dependency info (erg) (#3433)

lsp/rust_analyzer.lua
Fix `E5560: nvim_echo must not be called in a fast event context`
=> fix(rust_analyzer): nvim_echo must not be called in a fast event context

lua/lspconfig/util.lua
This is to address a recent issue (see #3710), with root detection failing when running a `pcakage.json5`.
I've modified `insert_package_json` to support `package.json5`.  While this has worked in my case with `tailwind-language-server`, whether this change should be upstreamed is up to maintainer's discretion.
Much thanks.
=> Support for non-conventional `package.json5`

.github/ci/lint.sh
Sometimes we want to make an exception for some bug fixes. In that case, we want all the *other* lint checks to run.
=> ci: check legacy configs *last*

lsp/astro.lua, lsp/mdx_analyzer.lua, lsp/volar.lua, lua/lspconfig/configs/astro.lua, lua/lspconfig/configs/mdx_analyzer.lua, lua/lspconfig/configs/volar.lua, lua/lspconfig/util.lua
LSPs like `volar` (for VueJS), `astro` or `mdx_analyzer` rely on a path for the Typescript server they should use. But this path is wrongly assumed to be inside `node_modules/typescript/lib` starting from the nearest `package.json` file.
In fact, in case of monorepos / workspaces, with all package managers like `npm`, `yarn` or `pnpm`, some hoisting can take place. This means that the `typescript` node module will get move higher up in the tree to be shared between all projects and avoid duplication. The NodeJS module resolution works like this, by trying to find the module upward in the tree, one directory after another.
Therefore, it can happen a case like this:
```
monorepo-root
- apps
> - app-number-one
>> - node_modules (without typescript)
>> - package.json
> - app-number-two
>> - …
```
=> fix: improve typescript server path search for ts dependents lsp

lsp/mesonlsp.lua
This commit enhances root directory detection of mesonlsp language server.
Current behavior:
`root` is set on first meson file user is opened
New behavior:
`root` is set to parent of `meson.build` with `project` function call
=> fix(mesonlsp): improved root detection

lsp/eslint.lua
This PR requires a workspace to be present for the ESLint LSP to attach, replacing the previous behavior of checking whether the root directory is `nil` (introduced in https://github.com/neovim/nvim-lspconfig/pull/3800).
End users can override this behavior by setting the `workspace_required = false` option.
It's generally better not to enable any JS/TS-related LSP globally, as developers tend to prefer different tools (e.g., ESLint, Biome, Oxlint).
=> fix(eslint): require workspace instead of checking root dir for `nil` value

lsp/texlab.lua
The root directory of Latexmk-based projects is not detected when the local configuration file is called `latexmkrc` (without leading `.`).
Both `.latexmkrc` and `latexmkrc` are valid names for [local Latexmk configuration files][1]. Add `latexmk` to the list of possible root markers.
[1]: https://mgeier.github.io/latexmk.html#local-configuration-files
=> fix(texlab): Improve root detection for Latexmk projects

lua/lspconfig/configs.lua
In this PR I propose a solution to the execution of LSPs being slow in WLS, a fix was already made a few days ago, but that broke LSPs entirely in Windows machines, so it has been reverted.
See [#3704 (comment)](https://github.com/neovim/nvim-lspconfig/issues/3704#issuecomment-2840154346) and [#3704 (comment)](https://github.com/neovim/nvim-lspconfig/issues/3704#issuecomment-2795261951)
fix #3704
=> fix(configs): execute sanitize_cmd only on windows to speed up WSL

lsp/lua_ls.lua
Correct formatting in `lua_ls` documentation.
- Re indent long lines
- Use quotes consistently
- Organize `runtimepath` section for clarity by splitting `library` in two separate blocks
=> fix(doc): Correct `lua_ls` documentation.

lsp/oxlint.lua
This PR adds the missing Oxlint LSP config (#3062, #3705).
=> feat(oxlint): added oxlint lsp config

lsp/omnisharp.lua
Problem:
The executable name may be in lowercase (e.g., when installed with Mason on Linux) in which case it won't be found.
Solution:
Verify if the name is in PascalCase, and otherwise use lowercase.
=> fix(omnisharp): update executable name

lsp/taplo.lua, lua/lspconfig/configs/taplo.lua
According to the [Taplo documentation](https://taplo.tamasfe.dev/configuration/file.html#configuration-file):
> Taplo supports configuration via file, unsurprisingly it uses the TOML format.
> 
> By default, every tool looks for one in the working directory or the root of the workspace by the following names (in precedence order):
> - .taplo.toml
> - taplo.toml
This simply adds those two files to the root directory definition.
Note: the commit message/PR is potentially mischaracterized as `fix` instead of `feat`; I was unsure of which category this falls under.
=> fix(taplo): add Taplo configuration files to root markers

plugin/lspconfig.lua
fix #3714
fix #2216
Things to note:
- `LspStart` starts the selected LSP and attaches to every buffer which has the right filetype. Should I only attach it to the current buffer?
- `LspStop` stops the selected LSP.
- `LspRestart` restart the selected LSPs, but I don't get how and why it used a timer.
- Should we add `LspEnable`? Maybe in a future PR.
EDIT:
Should I add checks for neovim 0.11?
Something like:
```lua
if not has_eleven then
error('nvim-lspconfig 2.x only supports vim.lsp.config. If you dont want to migrate, pin to nvim-lspconfig 1.x')
end
```
=> Feature: migrate builtin commands

lsp/elmls.lua, lsp/intelephense.lua, lsp/kotlin_language_server.lua, lsp/lean3ls.lua, lsp/phan.lua, lsp/phpactor.lua, lsp/rust_analyzer.lua, lsp/smarty_ls.lua, lua/lspconfig/util.lua
Problem:
`root_pattern` is not necessary for non-glob patterns.
Solution:
Replace non-glob cases with `vim.fs.root()`.
#3768
=> fix(configs): eliminate some usages of root_pattern

lsp/vectorcode_server.lua
With some recent updates in [vectorcode](https://github.com/Davidyz/VectorCode), the `vectorcode-server` no longer requires being started in a directory with a LSP workspace, so `single_file_support=false` can be removed.
Based on [this comment](https://github.com/neovim/nvim-lspconfig/pull/3659#issuecomment-2776613000) in #3659, it looks like `single_file_support` is the only blocker for the migration of `vectorcode-server` to `vim.lsp.config`, so I'm including the `lsp/vectorcode_server.lua` too. If there's anything else that needs modification, please let me know.
=> feat(vectorcode_server): add `vim.lsp.config` support

lsp/jsonnet_ls.lua
Should remove `jsonnet_ls` from the list in #3705.
=> feat(jsonnet_ls): jsonnet_ls lsp

lsp/tailwindcss.lua, lua/lspconfig/util.lua
This PR enhances root directory detection for the latest versions of TailwindCSS (v4), which no longer require tailwind.config.* or postcss.config.*, for Elixir/Phoenix projects. Phoenix projects generate with Tailwind installed via https://github.com/phoenixframework/tailwind.
=> feat(tailwindcss): Add Tailwind detection for Elixir Phoenix projects

lsp/tailwindcss.lua, lua/lspconfig/util.lua
followup to https://github.com/neovim/nvim-lspconfig/pull/3831
=> refactor: generalize insert_package_json()

lsp/ty.lua
This PR adds the [ty lsp](https://github.com/astral-sh/ty) config. The project is still in early development but meets the criteria for a new config.
=> feat(ty): Add `ty` lsp config

lsp/gopls.lua
The purpose of a `go.work` file is to handle multi-module workspaces. A common such scenario is a monorepo.
This is also how the legacy config works because it's using `lsponfig.util.root_pattern()` which has similar semantics as `root_markers`.
=> fix(gopls): prioritise `go.work` over `go.mod`

lsp/pyrefly.lua
Hello,
I'm part of the Pyrefly team at Meta, and we're working on a new language server/type checker (called Pyrefly 😄, [website](https://pyrefly.org/), [github](https://github.com/facebook/pyrefly)) to replace our other Python language server, Pyre. Pyre isn't fully ready to be deprecated yet, but we just made our big announcement at PyCon this year, and are excited for users to test it out.
I've been using it in NeoVim so far, and would love to make it easy for others to use. Please let me know if there's anything else you would need from me to get this working!
=> feat: pyrefly

lsp/eslint.lua
This change updates the `eslint` docs `on_attach` example that no longer works. Addresses https://github.com/neovim/nvim-lspconfig/issues/3837.
Issue https://github.com/neovim/neovim/issues/33577 is still open, and the example may need further updates in the future.
=> docs(eslint): update on_attach example

lsp/gh_actions_ls.lua
1. Replace `root_markers` and `workspace_required = true` with a `root_dir` function that checks the file is located in the correct location. This prevents some edge cases where the LSP would still attach to non-workflow files. This also makes unnecessary to use a `yaml.github` filetype, [as the readme of the lsp describes](https://github.com/lttb/gh-actions-language-server?tab=readme-ov-file#add-yamlgithub-filetype-detection).
2. add an empty `init_options` table, since such a table is apparently needed by the LSP: https://github.com/neovim/nvim-lspconfig/pull/3713#issuecomment-2857394868
=> fix(gh_actions_ls): use `root_dir` and add `init_options`

lsp/gopls.lua
fix #3841
This fixes the following error
> E5560: nvim_echo must not be called in a fast event context
when gopls fails.
Similar to commit 48f4475 / PR #3793.
PS long term I think it's best to do something like https://github.com/neovim/neovim/pull/21288/commits/a4100e107242f773937f229c3ae84e4112259213 instead.
=> fix(gopls): schedule vim.notify in on_exit

lsp/matlab_ls.lua
Adding a vim.lsp.config option for matlab_ls, as discussed in #3705.
This also brings a couple of improvements compared to the old config:
- Outside of a .git repository, CWD will be passed to the language server as root_dir, replicating normal Matlab behaviour
- indexWorkspace is set to "true" by default
=> feat(matlab_ls): vim.lsp.config support

lsp/tailwindcss.lua
tailwind-intellisense won't activate unless the filetype is detected as an HTML-based file. Elixir `.ex` files can have `~H` sigils with HEEX syntax inside or `~E` sigils with eelixir syntax inside. It's also typical to have `.html.heex` files entirely of HEEX syntax. Both of these are recognized in Elixir's treesitter injections.scm
tailwind-intellisense recognized html languages:
https://github.com/tailwindlabs/tailwindcss-intellisense/blob/db9768908e5f192a4ee9792eb640bf93caa89242/packages/tailwindcss-language-service/src/util/languages.ts#L3
nvim-treesitter heex support:
https://github.com/nvim-treesitter/nvim-treesitter/blob/066fd6505377e3fd4aa219e61ce94c2b8bdb0b79/queries/heex/highlights.scm
nvim-treesitter heex sigil injection: …
=> feat(tailwindcss): map elixir and heex ft to phoenix-heex

lsp/vespa_ls.lua
This PR adds initial support for the [Vespa schema language server](https://github.com/vespa-engine/vespa/tree/master/integration/schema-language-server), which provides LSP features such as completion, diagnostics, and go-to-definition for the following Vespa filetypes:
- Vespa schema files (`.sd`)
- Profile files (`.profile`)
- YQL query files (`.yql`)
- Supported filetypes: `sd`, `profile`, `yql`
- Root directory is determined by the presence of a `.git` directory
- Since these extensions are not natively recognized by Neovim, filetypes must be manually added using `vim.filetype.add`
```lua
vim.filetype.add {
extension = {
profile = 'sd',
sd = 'sd',
yql = 'yql',
},
}
=> feat(vespa_ls): Add vespa_ls config

lsp/helm_ls.lua, lsp/yamlls.lua
this adds config for starting helm_ls and yamlls with the new filetype yaml.helm-values that will be added to the neovim helm_ls extension by https://github.com/qvalentin/helm-ls.nvim/pull/8
Files of this type should have both yamlls and helm-ls running. This is required because helm-ls now supports editing values.yaml files but should only be active for certain yaml files.
=> feat(helm_ls,yamlls): support custom filetype for helm-ls

lsp/bicep.lua, lua/lspconfig/configs/bicep.lua
- Support for .bicepparam files
- `bicep-params` filetype identifier from discussion at https://github.com/Azure/bicep/issues/17230
Resolves #3885
=> feat(bicep): add `bicep-params` filetype for bicep lsp

lsp/svelte.lua
Similar to #3875, but this time I [checked](https://github.com/sveltejs/language-tools/issues/2777), and the server actually doesn't support schemas other than `file://`.
=> fix(svelte): only attach to existing files

lsp/glint.lua
Saw this one was still missing in the list in #3705.
I tested it by creating a new ember ts project -> `ember new my-typescript-app --typescript`
then adding glint to that project -> `npm install --save-dev @glint/core`
Per default we use the project local glint-language-server, but the user can also choose to use a globally installed version.
Based on [lua/lspconfig/configs/glint.lua](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/glint.lua)
=> feat(glint): add vim.lsp.config support

lsp/biome.lua
the latest release of biome adds preliminary support for formatting html files: https://biomejs.dev/blog/biome-v2/#html-formatter
Thus, html should be added to the list of filetypes for the biome LSP.
=> feat(biome): add `html` as filetype

lsp/powershell_es.lua
LogLevel `Normal` of PowerShellEditorServices has been removed by the commit https://github.com/PowerShell/PowerShellEditorServices/commit/d9de5bd8b1ed624a687d701fa2616e5991db2e2c
The corresponding value after the change is `Information = 2`.
=> fix(powershell_es): update LogLevel to Information

lsp/basedpyright.lua, lsp/ccls.lua, lsp/clangd.lua, lsp/denols.lua, lsp/ds_pinyin_lsp.lua, lsp/julials.lua, lsp/markdown_oxide.lua, lsp/rust_analyzer.lua, lsp/svlangserver.lua, lsp/texlab.lua, lsp/tinymist.lua, lsp/ts_ls.lua, lsp/zk.lua, lua/lspconfig/configs/tinymist.lua
This is a super simple fix, which addresses the bug that if a server is attached to a buffer other than the current one by means of `vim.lsp.buf_attach_client`, then the Language Server-related commands may be created in the current buffer, and not in the one the server has been attached to.
P. S. Does it need to be documented somewhere explicitly that the `on_attach` callback may not always be run within the context of the target buffer? There is an example of writing such a callback in `CONTRIBUTING.md` that correctly uses the `bufnr` passed in as the 2nd parameter, is this enough?
=> fix: some `on_attach` callbacks may create commands in a wrong buffer

lsp/powershell_es.lua
Problem:
Powershell Editor Services does not recognize `-LogLevel Information` and this prevents the LSP from starting
Solution:
Revert update to `command_fmt` to use a recognized log level from [Start-EditorServices.ps1](https://github.com/PowerShell/PowerShellEditorServices/blob/3a429eac5544fd7613c281c0814f94ac03fad551/module/PowerShellEditorServices/Start-EditorServices.ps1)
=> fix(powershell_es): update LogLevel to recognized value

lsp/pug.lua, lua/lspconfig/configs/pug.lua
Problem:
Installing the pug lsp using the suggested method (`go get github.com/opa-oz/pug-lsp`) does not work in the latest versions of `go` and instead produces a message the "'go get' is no longer supported outside a module".
Solution:
Change the install command for the pug lsp to the correct command which is `go install github.com/opa-oz/pug-lsp@latest`.
=> docs: Correct install command for pug lsp

lsp/phpactor.lua
Hello!
This fixes the precedence of root markers for phpactor. When opening a vendor file, a new lsp workspace was being created in the context of the vendor directory, which causes failures because there's no vendor/ directory in the workspace root and therefor the lsp cannot find any of the symbols.
Thanks!
=> fix(phpactor): root markers precedence

lsp/debputy.lua
The `vim-debian` project added `autopkgtest` as id for the `debian/tests/control`. The `debputy` project supports that file under a different file type ID, but will align with `vim-debian` in the next release of `debputy`.
The `vim-debian` project adding the file type:
* https://salsa.debian.org/vim-team/vim-debian/-/commit/14776de4f28f82177ef6e2397510d01b266f3b41
* https://salsa.debian.org/vim-team/vim-debian/-/commit/d6363b31dd8baa75d8a70d63301b808583848214
The `debputy` project aligning on the file type ID:
* https://salsa.debian.org/vim-team/vim-debian/-/commit/d6363b31dd8baa75d8a70d63301b808583848214
=> feat: add `autopkgtest` file type to `debputy.lua`

lsp/ts_ls.lua
Implement the `editor.action.showReferences` client command, which is used by the references and implementation code lenses that TypeScript Language Server provides.[^1]
I've mostly based the implementation on the existing code for `vim.lsp.buf.references()`. The main visible difference is that the latter includes the item being referenced at the top of the list. Although, if desired, this could be emulated by manually inserting the position passed along in the command arguments at the top of the list.
[^1]: https://github.com/typescript-language-server/typescript-language-server?tab=readme-ov-file#code-lenses-textdocumentcodelens
=> feat(ts_ls): implement code lens support

lsp/clangd.lua
The corresponding post was made in 2022, but we now have rich protobuf language servers and formatters such as
[buf](https://github.com/bufbuild/buf). Buf already has their stuff registered with mason and nonels, so they're already well integrated into the neovim ecosystem. 
There are open hacks to getting around this by explicitly overriding the default settings, but it's more idiomatic to have sensible defaults in the go-to lsp repo. (The current issue is that clangd will attach, fail to parse, then spam the file with bogus error messages).
=> feat(clangd): remove proto filetype support, reverting (#2125)

lsp/biome.lua
Problem: users may have a different version of biome installed in a project, compared to the global installation.
Solution: use project local binary if available.
Note: I used `vim.system({ ... }):wait()` to check if the binary is executable. LMK if using `vim.fn.executable` is preferred.
This PR is inspired by the release of biome v2, which introduced some breaking changes.
=> feat(biome): use project local bin if available

lsp/glint.lua
Problem:
The glint config `cmd()` gets its config from the currently resolved global config, which may be different than the one for the current client.
Solution:
Since Nvim 0.11.3 https://github.com/neovim/neovim/issues/34547 `cmd()` receives a `config` arg, so use that instead.
Followup to https://github.com/neovim/nvim-lspconfig/pull/3912 @justmejulian 
Note that this requires Nvim 0.11.3
=> refactor(glint): use `cmd(…, config)`

lsp/svelte.lua
The Svelte LSP does not attach to regular JS / TS files. To get notified about changes in these files, it "needs" to send a custom message via `notify`.
The VS Code extension uses the same workaround[^1] and it has been discussed to death how to port it to neovim[^2]. Instead of relying on users finding out about said discussion, it should be included in the default configuration.
[^1]: https://github.com/sveltejs/language-tools/blob/2e2c6c3624f2dd21cbda4d8b4b63e0d4df93152e/packages/svelte-vscode/src/extension.ts#L346
[^2]: https://github.com/sveltejs/language-tools/issues/2008
=> feat(svelte): notify LSP of changes in JS/TS files

lsp/roslyn_ls.lua
vim.lsp.util._refresh() was removed by https://github.com/neovim/neovim/pull/33903
=> fix(roslyn_ls): replace deprecated function call

lsp/svelte.lua
Follow up: https://github.com/neovim/nvim-lspconfig/pull/3958
As it turns out, we can't use both `buffer` and `pattern` in the same autocmd. And even if we could set the buffer, it is not necessarily the one the server is attaching to.
By removing the `buffer` we are creating a new autocmd every time the buffer attaches. The ideal solution would be to guard against that, but I'm not sure if that would be the best approach (I imagine there are some augroup shenanigans?).
=> fix(svelte): use augroup to avoid creating multiple autocmds 

lsp/biome.lua
The biome [documentation](https://biomejs.dev/guides/big-projects/#use-multiple-configuration-files) mentions that 
> When you use Biome’s features - either with the CLI or LSP - the tool looks for the nearest configuration file using the current working directory.
>
> If Biome doesn’t find the configuration file there, it starts traversing upwards the directories of the file system, until it finds one.
I think it makes sense to follow this recommendation, so we can have proper monorepo support. Currently, in a monorepo, a new client is started for each `biome.json` (similar situation as #3910), which is unnecessary, since biome supports monorepos [natively](https://biomejs.dev/guides/big-projects/#monorepo) (as of v2). The alternatives I have considered aren't as robust.
The first …
=> feat(biome): monorepo support

lsp/tailwindcss.lua
Since tailwind v4 it is not required to have a tailwind.config.* in the project 1. The current configuration is preventing the LSP to attach to the configured file types in cases when no tailwind.config.* or none of the other markers (package.json etc.) is present. This commit fixes this limitation by providing .git as a fallback and by documenting this limitation.
fixes #3979
=> fix(tailwindcss): add fallback for tailwind v4

lsp/docker_language_server.lua
Add support for the official [docker language server](https://github.com/docker/docker-language-server).
The official docker language server supports `Dockerfile`s, Docker Compose YAML files, and Bake HCL/JSON files.
I am not sure what is the recommendation/consensus around enabling the language servers on such broad filetypes (e.g. `json`, `hcl`) since they are general purpose configuration/data languages. Happy to remove them and leave it up to users to pass in these filetypes through their customized configs, if they desire.
=> feat(docker): add docker-language-server

lsp/matlab_ls.lua
Problem:
No clear documentation about requirement to set `installPath`. Leaving `installPath` empty causes the language server to fail silently (it attaches, but does not provide any features).
Solution:
Add documentation in `matlab_ls.lua`.
=> docs(matlab_ls): add installPath requirement comment

lsp/vue_ls.lua
typescript-language-server now supports tsserver/request:
https://github.com/typescript-language-server/typescript-language-server/releases/tag/v4.4.0
=> fix(vue_ls): support ts_ls

lsp/vue_ls.lua
Currently, `on_init` tries to use `or` to combine two function calls
that return tables and always returns truthy on the first value (`ts_ls`) because an empty
table is considered truthy in lua causing an error when using `vtsls`.
This properly checks if either `ts_ls` or `vtsls` exists and extends the
`clients` list for proper error handling.
=> fix(vue_ls): correctly check if `ts_clients` exist

lsp/golangci_lint_ls.lua, lua/lspconfig/configs/golangci_lint_ls.lua
Should fix detection of shell wrapper script as explained in https://github.com/neovim/nvim-lspconfig/issues/3863#issuecomment-3151511384.
=> fix(golangci_lint_ls): support wrapper script

lsp/clangd.lua, lsp/denols.lua, lsp/elmls.lua, lsp/markdown_oxide.lua, lsp/rust_analyzer.lua, lsp/svlangserver.lua, lsp/texlab.lua, lsp/tinymist.lua, lsp/zk.lua
This is a follow to the #3991.  I tried to update to the 0.11 api most of the config, that had some issues. The changes can be summed to:
- Drop check for neovim version, for tinymist
- Make sure the name starts with Lsp to remove the exemption from the CI
check, for tinymist
- Use bufnr and client as arguments of on_attach
- Update documentation to indicate implemented commands
- Drop .buf.execute_command and use :exec_cmd
- Call request as method
- Silence wrong 
- Use vim.bo[bufnr] instead of nvim_buf_get_option 
- Use vim.notify instead of 
- Drop border setup in favor of winborder 
- Set title on :exec_cmd
I made a separate commit for every server, I don't know if this is the preferred way to do it.
=> fix: update configs to 0.11+

lua/lspconfig/health.lua, plugin/lspconfig.lua
Problem: `vim.lsp.get_log_path()` was recently deprecated because it is just a unnecessary wrapper around `vim.lsp.log.get_filename()`
Solution: Use the non deprecated function
=> fix: vim.lsp.get_log_path() -> vim.lsp.log.get_filename()

lsp/hyprls.lua
```bash
$ go install github.com/ewen-lbh/hyprls/cmd/hyprls@latest
go: downloading github.com/ewen-lbh/hyprls v0.8.0
go: github.com/ewen-lbh/hyprls/cmd/hyprls@latest: version constraints conflict:
github.com/ewen-lbh/hyprls@v0.8.0: parsing go.mod:
module declares its path as: github.com/hyprland-community/hyprls
but was required as: github.com/ewen-lbh/hyprls
```
=> docs(hyprls): Install from hyprland-community org

lsp/eslint.lua
I just found out that I introduced a pretty big performance bottleneck with #3955 on `eslint` LSP. I thought using `vim.fs.find` would be much faster, but in fact it's taking a solid 3-4 seconds on a project of mine, compared to around 100-200ms with the previous implementation I had with `vim.fn.globpath`.
I'm pretty sorry about having put this upstream, I thought it was my local setup that had an issue and did not think about this.
=> fix(eslint): fix performance regression on configuration lookup

lsp/yamlls.lua, lua/lspconfig/configs/yamlls.lua
Faking capabilities isn't necessary to enable formatting support. It's a dynamically registered capability that yamlls announces whenever yaml formatting is enabled in settings, which it isn't by default.
See:
https://github.com/redhat-developer/yaml-language-server/blob/3821411ee8c92e5b7e5ca88f84ab443ae3b2791a/src/yamlServerInit.ts#L128
https://github.com/redhat-developer/yaml-language-server/blob/3821411ee8c92e5b7e5ca88f84ab443ae3b2791a/src/languageserver/handlers/settingsHandlers.ts#L159-L174
Fixes: 63a016437e44 ("feat(yamlls): document formatting support #4003")
=> refactor(yamlls): Non-hacky way to enable formatting

lsp/yamlls.lua
Some back and forth on this, I didn't explain things properly on #4003 and this section got removed in #4012.
The current version of the config will let you do formatting manually `:lua vim.lsp.buf.format()` but the lsp doesn't have capabilities registered correctly so if you use auto formatting like outlined in [help pages](https://neovim.io/doc/user/lsp.html#lsp-attach)
```lua
if not client:supports_method('textDocument/willSaveWaitUntil')
and client:supports_method('textDocument/formatting') then
vim.api.nvim_create_autocmd('BufWritePre', {
group = vim.api.nvim_create_augroup('my.lsp', {clear=false}),
buffer = args.buf,
callback = function()
vim.lsp.buf.format({ bufnr = args.buf, id = client.id, timeout_ms = 1000 })
end,
})
end
```
It won't enable for the yaml lsp because …
=> feat(yamlls): added lsp capability override

lsp/gitlab_ci_ls.lua, lua/lspconfig/configs/gitlab_ci_ls.lua
Problem:
If project had a nested child gitlab file named: .gitlab-ci.yml it would take it as root.
Solution:
If inside GIT repository just use git repository root as root and still keep the option for .gitlab* as fallback if there is no git repo yet.
=> fix(gitlab_ls): root dir ordering

lsp/cir_lsp_server.lua
This PR adds the default config for the LLVM ClangIR LSP Server (https://github.com/llvm/llvm-project/tree/main/clang/tools/cir-lsp-server)
=> feat: add llvm clangir lsp server

lsp/vue_ls.lua
This commit adds preliminary `typescript-tools` support for `vue_ls`. This is to allow for a smooth transition if support for `typescript.tsserverRequest` is added.
=> feat(vue_ls): add preliminary typescript-tools support

lsp/copilot.lua
Current code will always trigger error (unless you are already authd), because result.code is invalid. result.userCode must be used instead.
=> fix(copilot): fix device flow authentication

lsp/herb_ls.lua
As outlined in [this issue on herb](https://github.com/marcoroth/herb/issues/309#issuecomment-3130071214), herb should not actually run on Ruby files. This PR removes the offending filetype.
> Yeah, I think Herb shouldn't be run on .rb files in general. So it would probably be best to remove the ruby file type in the Language Server configuration.
@marcoroth FYI
=> fix(herb): remove ruby filetype

.github/ci/lint.sh, lsp/basedpyright.lua, lsp/pyright.lua
Fix error raised when running `:LspPyrightOrganizeImports` :
```
Language server `pyright` does not support command `pyright.organizeimports`. This command may require a client extension.
```
=> fix(pyright): command :LspPyrightOrganizeImports fails

plugin/lspconfig.lua
In `plugin/lspconfig.lua`, `vim.version` is slow, so replace it with `has()`.
Local benchmark `:runtime plugin/lspconfig.lua`:
| function | time |
|-|-|
|`vim.version`|3-6ms|
|`has()`|0.2-1ms|
=> perf: use has() instead of vim.version

lsp/roslyn_ls.lua
- Diagnostics were only refreshed for the current buffer, not all buffers of the client.
- Roslyn did not handle override method completion correctly.
- Added `roslyn.client.completionComplexEdit` command handler to apply edits for override completions.
- Added `refresh_diagnostics(client)` function and call it on project initialization and relevant buffer events.
- Verified diagnostics update across multiple buffers.
- Verified override method completion inserts the correct method body.
=> feat(roslyn_ls): support override completion and refresh diagnostics

lsp/expert.lua
Copy the approach from `lsp/elixirls.lua` to support monorepos.
fix #4052
=> fix(expert): implement root_dir instead

lsp/roslyn_ls.lua
This handler was removed a long time ago and was replaced with another handler that is already implemented here: https://github.com/dotnet/vscode-csharp/commit/9cc41f6d2535a5cb5533dc5ae8f3a10ade16e7b5
=> fix(roslyn_ls): remove unused handler

lsp/stylua.lua
StyLua [now supports LSP](https://github.com/JohnnyMorganz/StyLua/pull/970) out of the box.
=> feat: StyLua Lua formatter

lsp/apex_ls.lua
Adds lsp config for apex language service, essentially just converting the existing legacy config to the new format.
https://github.com/neovim/nvim-lspconfig/issues/3705
=> feat(apex_ls): add vim.lsp.config support

lsp/jdtls.lua
Alter the order for .git so it becomes a catch all rather than an identifier for an explicit type of java project. Appending .git to the marker list will alleviate root identification problems where the java project directory is a subdirectory of the directory containing the .git marker.
=> Adjust jdtls root_marker list.

lsp/ocamllsp.lua
This drops the dependency on `lspconfig.util`, which appears deprecated.
This also makes it possible to use just the config file without the rest of the framework.
The root pattern grouping and prioritisation follows the one proposed here: https://github.com/ocaml/ocaml.org/pull/3322/files#diff-6721080d4f565e09348cab4e8fe6d6393b9e4449bf9c7e2b3f054a0b986809d6R224
Tested with NeoVim v0.11.4
=> feat(lsp/ocamllsp.lua): use root_markers instead of root_dir

lsp/jdtls.lua
Using git directory as last resort before defaulting to pom.xml is important for multi module maven projects. Example of structure:
pom.xml
submodule-a/pom.xml
submodule-b/pom.xml
If sumbodule-b depends on submodule-a (common pattern for dto/impl), the parent usually has info about linking the 2 projects (and without that go to definition etc will jump to compiled source that might not be present/up t date).
This structure is also fine and do not breaks jdtls:
my-project/pom.xml
e.g its fine if working directory is git repo root (and this pattern is also much less common than multi module maven projects that without this change break always).
Closes #4102
=> fix(jdtls): increase priority of .git marker and add mvnw and gradlew

lsp/ty.lua
Issue: `ty` by default only comes with a few `root_markers` that are set. Using `ty` with older python projects that still use `setup.{py,cfg}` causes the LSP to be initialized with incorrect roots.
Fix: Add a few `root_markers` to support legacy python projects.
=> feat(ty): add a few more appropriate root markers

lsp/neocmake.lua, lua/lspconfig/configs/neocmake.lua
The GitHub repository has changed owners. The old URL redirects to the new repository but updating it makes it clearer which project is referenced by the documentation.
=> docs(neocmake): update GitHub repository URL
