README.md
README_preamble.md
lua/nvim_lsp.lua
lua/nvim_lsp/pyls.lua
scripts/docgen.lua

Get it working; can be improved!

Add initial support for python-language-server

---

README.md
README_preamble.md
lua/nvim_lsp.lua
lua/nvim_lsp/tsserver.lua

Looking for feedback on this. I basically used the existing server implementations as a boilerplate, should work!

Initial typescript support

---

README.md
lua/nvim_lsp.lua
lua/nvim_lsp/bash.lua

Short implementation for the bash language server.
Feedback is welcome.

Add bash language server

---

lua/nvim_lsp.lua
lua/nvim_lsp/ccls.lua

Based on the clangd equivalent

Basic support for the ccls language server

---

README.md
lua/nvim_lsp.lua
lua/nvim_lsp/flow.lua

Since Flow is installed not for global but for each project, we will not provide an install command.
ref: https://flow.org/en/docs/install/, https://flow.org/en/docs/config/

Add support flow language server

---

lua/nvim_lsp.lua
lua/nvim_lsp/cssls.lua

Hello! 
I started the process of adding LSP configuration for CSS/LESS/SCSS based on this server
https://github.com/vscode-langservers/vscode-css-languageserver-bin

Add css lsp

---

README.md
lua/nvim_lsp/skeleton.lua
scripts/README_template.md

- Add client.workspace_did_change_configuration()
- Notify settings on init.

Add workspace/didChangeConfiguration support.

---

lua/nvim_lsp/skeleton.lua

Pending https://github.com/neovim/neovim/pull/11430

Fixes for new LSP changes

---

lua/nvim_lsp/ccls.lua
lua/nvim_lsp/elmls.lua
lua/nvim_lsp/fortls.lua
lua/nvim_lsp/leanls.lua
lua/nvim_lsp/skeleton.lua
lua/nvim_lsp/solargraph.lua

Add docs and vscode names.

---

lua/nvim_lsp/pyls_ms.lua

`vim.fn.has('xxx')` returns 1 or 0 that both are true in lua.

Fix detection of the OS from has('xxx')

---

lua/nvim_lsp/sumneko_lua.lua

This enables to install `lua-language-server` in macOS in addition to Linux.

Enable to install sumneko_lua in macOS

---

lua/nvim_lsp/pyls_ms.lua

Cleanups from the original PR, improved documentation (added suggestion on installign .net core), still haven't implemented an automated update for the LSP.

Update pyls_ms, add documentation, minor refactor to os versioning

---

lua/nvim_lsp.lua
lua/nvim_lsp/ocamlls.lua

I added [ocaml-language-server](https://github.com/ocaml-lsp/ocaml-language-server). Cheers!

Add ocamlls

---

scripts/README_template.md

[Github actions](a0ca54ab6f2c8dbc30b2c4c253c71d7ebf88b940) rollback this commit 68392b857dd7218ea749da08157c5b3c6caeae1a

README_template.md: Update template

---

lua/nvim_lsp.lua
lua/nvim_lsp/vimls.lua

Probably needs some cleanup, pertains to #66

Added vimls

---

.github/workflows/docgen.yml
.github/workflows/lint.yml
.gitignore
.luacheckrc
CONTRIBUTING.md
README.md
lua/nvim_lsp/intelephense.lua
lua/nvim_lsp/pyls.lua
lua/nvim_lsp/pyls_ms.lua
lua/nvim_lsp/texlab.lua
lua/nvim_lsp/tsserver.lua
lua/nvim_lsp/util.lua
lua/nvim_lsp/vimls.lua
scripts/docgen.lua

Add luacheck

---

README.md
lua/nvim_lsp/pyls_ms.lua

Bump pyls_ms to version 0.5.30

Bump pyls_ms version

---

lua/nvim_lsp/jsonls.lua

test on [this repository](https://github.com/fge/sample-json-schemas).
Should fix https://github.com/vscode-langservers/vscode-json-languageserver-bin/issues/3

Add json lanuguage server(vscode-json-languageserver)

---

README.md
scripts/docgen.lua

It is also needed by make_implemented_servers_list().

docgen.lua: call require_all_configs() earlier

---

README.md
lua/nvim_lsp.lua
lua/nvim_lsp/julials.lua

Add julials

---

lua/nvim_lsp/vuels.lua

Add vue-language-server

---

lua/nvim_lsp/dartls.lua

Hello 
I want to kick off dartls script, this is what is working for me...
i am not very good at lua scripting. I am hoping that someone will find this usefull for finish it up. Like docs and lua checking and everything that contributing require.
I am sorry for doing this like so - just want to help.
_first contribution to big project_

Add dartls lua script

---

lua/nvim_lsp/rust_analyzer.lua

ref: https://github.com/rust-analyzer/rust-analyzer/pull/3216

rust-analyzer: rename command name

---

.github/workflows/docgen.yml

gh actions: fix docgen action

---

README.md
scripts/README_template.md

Hi, I added vim-plug's url in `README_templete.md`
I think this will make the documentation better.
Could you check this Rull Request?

[add] vim-plug url in README_templete

---

lua/nvim_lsp/vuels.lua

ref: https://github.com/vuejs/vetur/releases/tag/v0.24.0

vuels: change package name from 'vue-language-server' to 'vls'

---

lua/nvim_lsp/sumneko_lua.lua

lua language server: add a more detailed description of cmd

---

plugin/nvim_lsp.vim

Hello.
This patch also check to duplicate.
Could you check this Pull Request?

[add] check Duplicate

---

lua/nvim_lsp/health.lua

healthcheck: use pcall for config.cmd error

---

lua/nvim_lsp/purescriptls.lua

The `root_dir` supports both `pulp` and `spago`.

Add Purescript language server

---

lua/nvim_lsp/pyls_ms.lua

Not sure if this is the best approach, but this eliminates the need to manually bump the version.

Automatically fetch latest version of pyls_ms

---

lua/nvim_lsp/sourcekit.lua

Adding the `sourcekit-lsp` language server.

Add Swift support through sourcekit-lsp

---

lua/nvim_lsp/ocamllsp.lua

This pull request adds support for [ocaml-lsp](https://github.com/ocaml/ocaml-lsp).

Add ocaml-lsp support

---

lua/nvim_lsp/codeqlls.lua
lua/nvim_lsp/pyls.lua
lua/nvim_lsp/rls.lua
lua/nvim_lsp/rust_analyzer.lua
lua/nvim_lsp/sourcekit.lua

Resolve CI failure: https://github.com/neovim/nvim-lsp/runs/576174254

fix package.json source URI

---

lua/nvim_lsp/sumneko_lua.lua

- I had to install clang for the installation to complete -> check for
that up front
- quote PATH update (especially on WSL, PWD and PATH will easily contain
whitespace)

Make installer for sumneko_lua more robust

---

lua/nvim_lsp/als.lua

It took me a lot of time to figure out how to set settings for the Ada Language Server, so I thought it'd be nice if it was described in the README.
Note that I've also opened a PR that describes this information in the Ada Language Server's repository: https://github.com/AdaCore/ada_language_server/pull/417

Ada Language Server: describe how to set settings

---

lua/nvim_lsp/util.lua

Addresses #207. Supersedes #201.
Using `termopen()`, `util.sh` gets full terminal functionality for free:
- progress bars leveraging `\r` and other more fancy output types (e.g.
curses UIs)
- interactive prompts
- canceling with `Ctrl-C`
- etc.
The drawback is that currently (see https://github.com/neovim/neovim/issues/7607),
the `on_exit` callback for `termopen()`/`jobstart()` *has* to be a VimL
function, which means a global VimL function has to be created
on-the-fly with a name which hopefully won't clobber anything that's
already defined.
Like #201, this commit makes sure that the output buffer remains open if
the script exits with anything else than 0 (so that the user can figure out the
cause of the error).

Use builtin terminal for util.sh output

---

lua/nvim_lsp/tsserver.lua

Fix https://github.com/neovim/nvim-lsp/issues/164

Fix 'Can't get tsserver to work #164'

---

lua/nvim_lsp/metals.lua

fix: https://github.com/neovim/nvim-lsp/runs/684011087

docgen: use package.json for generating metals doc

---

lua/nvim_lsp/rnix.lua

This add rnix-lsp, an lsp that supports nix. I added a basic cargo install, however, I know there are currently discussions about removing this.

Add rnix-lsp

---

.github/workflows/lint.yml
.github/workflows/test.yml
.gitignore
CONTRIBUTING.md
Makefile
scripts/run_test.sh
test/nvim_lsp_spec.lua

Add execution environment of test

---

lua/nvim_lsp/health.lua

resolve https://github.com/neovim/nvim-lsp/issues/248

healthcheck: skip healthcheck if make_config function is nil

---

lua/nvim_lsp/elixirls.lua

Server name should be `elixirls` not `elixirLS`.

Fix wrong elixirls server name in doc

---

lua/nvim_lsp/configs.lua

resolve: https://github.com/neovim/nvim-lsp/issues/264

fix the problem that commads cannot be registered in custom setup

---

scripts/docgen.lua

https://github.github.com/gfm/#backslash-escapes

docgen: escape GitHub Flavored Markdown punctuation characters

---

lua/nvim_lsp/cmake.lua

~To test it you need the latest master, see https://github.com/regen100/cmake-language-server/issues/16~

Add CMake language server

---

lua/nvim_lsp/html.lua
lua/nvim_lsp/jsonls.lua
lua/nvim_lsp/purescriptls.lua
lua/nvim_lsp/rust_analyzer.lua
lua/nvim_lsp/yamlls.lua

#241 has an omission to correct.

config: remove unnecessary code comennts and utf8 option

---

lua/nvim_lsp/jedi_language_server.lua

That's a language server for Python built purely on top of jedi. See #271  for some context.
I wonder if having 3 options for Python is a good idea? I'm open for
feedback :D

Add jedi_language_server

---

lua/nvim_lsp/solargraph.lua
lua/nvim_lsp/vimls.lua

There may be others. In the meantime, I'll create a PR for the two cases I noticed.

Add Extensions to Windows Batch Files

---

lua/nvim_lsp/clojure_lsp.lua

This adds the config for using the [clojure language server](https://github.com/snoe/clojure-lsp).

Add clojure language server

---

.github/workflows/lint.yml
.github/workflows/test.yml
README.md

Run lint job as sudo to make CI pass again

---

README.md
lua/nvim_lsp/rome.lua

https://github.com/romefrontend/rome

Add support for "Rome" language server

---

README.md
lua/nvim_lsp/scry.lua

https://github.com/crystal-lang-tools/scry

Add support for "Scry" language server

---

lua/nvim_lsp/hls.lua

Hi folks! First PR here.
Added a simple config for the Haskell Language Server (https://github.com/haskell/haskell-language-server).
Avoided installation as it gets pretty messy.

Add a default config for the haskell language server.

---

README.md
lua/nvim_lsp/angularls.lua
lua/nvim_lsp/configs.lua
scripts/README_template.md

This integrates the angular language server with nvim-lsp.
This may need some help with some of "probe" directories and cmd setting. So any help is appreciated but this does work in an angular project!

feat(angular-ls): add angular language service

---

lua/lspconfig/kotlin_language_server.lua

Add commit which supports Windows to #326.

add default for kotlin-language-server cmd

---

lua/lspconfig/pyright.lua

https://github.com/neovim/neovim/pull/12638 was merged, this shouldn't be necessary anymore

Remove before_init workaround

---

lua/lspconfig/pyright.lua

Wrap pyright settings correctly with python.analysis

---

lua/lspconfig/purescriptls.lua

Same fix as https://github.com/neovim/nvim-lspconfig/pull/298

Add extension to purescriptls command name on Windows

---

lua/lspconfig/pyright.lua

Same as  #406, but for pyright

Add extension to pyright command name on Windows

---

lua/lspconfig/jdtls.lua

bugfix for code action not working sometimes

---

lua/lspconfig/groovyls.lua

I think @wuilliam321  had an older version of nvim when he had it running using https://github.com/neovim/nvim-lspconfig/pull/355.
I also just tested this successfully on macOS. Thanks @wuilliam321 !

groovyls: nvim_lsp -> lspconfig

---

lua/lspconfig/zls.lua

Zig somehow got in the wrong place

zig: nvim_lsp/zls.lua -> lspconfig/zls.lua

---

lua/lspconfig/ghcide.lua

ghcide isn't for end users now.
So I add deprecation message.

Add deprecation message to ghcide

---

lua/lspconfig/configs.lua

Add catch-all callback for client/registerCapability

---

.github/workflows/docgen.yml
CONFIG.md

Fix docgen github action to use CONFIG.md instead of README.md

---

.github/workflows/test.yml

see: https://github.com/neovim/neovim/pull/13584

Fix macos CI

---

lua/lspconfig/svelte.lua

I can't check if the docs is properly generated though. I think it 'should' work because I copied them from `tsserver.lua` but after running `scripts/docgen.lua` like the [CONTRIBUTING.md](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#generating-docs) says and nothing happens. (to be fair, it downloads stuff but after that nothing happens/changed).
https://github.com/sveltejs/language-tools/tree/master/packages/language-server

Add support for "Svelte" language server

---

CONFIG.md
lua/lspconfig/perlls.lua

Fix perl docgen by replacing with raw github link

---

CONFIG.md
lua/lspconfig/texlab.lua

closes #502
@coxackie Can you test this?

Fix texlab crash due to missing handler

---

CONFIG.md
lua/lspconfig/texlab.lua

Pending https://github.com/neovim/neovim/pull/13640

Remove texlab capabilities fix

---

CONFIG.md
lua/lspconfig/sumneko_lua.lua

Update sumneko lua docs

---

CONFIG.md
lua/lspconfig/tsserver.lua

tsserver: add typescript as dependency in docs 

---

CONFIG.md

Fix minor typo in sumneko_lua instructions

---

CONFIG.md
lua/lspconfig/jsonls.lua

Jsonls fix formatting

---

CONFIG.md
lua/lspconfig/texlab.lua

texlab: add %f to settings.latex.build.args

---

CONFIG.md
lua/lspconfig/ccls.lua

ccls: Improve documentation, add on_init example

---

CONFIG.md
lua/lspconfig/sumneko_lua.lua

A lot of people have noticed this one.

sumneko: fix typo

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
CONFIG.md

Also made it more clear not to update CONFIG.md

templates: update pr template to CONFIG.md from README.md

---

CONFIG.md
lua/lspconfig/denols.lua

DRAFT: Add deno language server.
This seems to work on JS/TS. I haven't done any deno work, so not sure what root directories we should also trigger.

Add deno language server

---

CONFIG.md
lua/lspconfig/angularls.lua

angularls: update documentation to note on_init overrides cmd

---

CONFIG.md
README.md

Documentation: improve description of root pattern

---

.github/ISSUE_TEMPLATE/bug_report.md
test/minimal_init.lua

@teto What are your thoughts on including a minimal init.lua?

Issue template improvements

---

lua/lspconfig/denols.lua

update denols doc

---

CONFIG.md
lua/lspconfig/rls.lua

rls: remove vscode extension link, fix documentation

---

README.md

readme: fix function, add missing servers for clarity

---

CONFIG.md
lua/lspconfig/jdtls.lua

Closes #532.
I realize there *might* be a better solution, but since jdtls currently has a broken start command, I'm going to go ahead and merge this.
cc:  @ChrisAmelia

jdtls: fix cmd and fix java documentation

---

lua/lspconfig/jdtls.lua

Accidentally merged too early. Fixup.

jdtls: fix formatting and non-local variable

---

README.md

Closes #63 
Also see https://github.com/neovim/neovim/pull/13723

Update on attach in readme

---

CONFIG.md
lua/lspconfig/tsserver.lua

tsserver: fix root detection to prefer tsconfig.json

---

CONFIG.md
lua/lspconfig.lua
lua/lspconfig/configs.lua

Closes #664
LspInfo is also instant now.

Fix lsp info root detect

---

CONFIG.md
README.md
lua/lspconfig.lua
lua/lspconfig/julials.lua

Closes #660
@coxackie 
I realize it's not pretty (yet), I'll add new line trimming, I just want to make sure this fixes the issue in all cases and doesn't add weird corner problems (it shouldn't)

LspInfo: fix display when client cmd contains newlines

---

lua/lspconfig/racket_langserver.lua

This adds in a basic configuration for the Racket langauage server.
https://github.com/jeapostrophe/racket-langserver

Add racket_langserver.

---

lua/lspconfig.lua
lua/lspconfig/lspinfo.lua

This was getting too big to be in lspconfig.lua.

lspinfo: move to module

---

CONFIG.md
README.md
lua/lspconfig/util.lua

Use nvim_exec

---

.github/workflows/docgen.yml

docgen: remove CI trigger for PRs, only pushes to master

---

CONFIG.md
lua/lspconfig/lspinfo.lua

to save screen estate. I've added some indentation too to better identify the blocks. Let me know what you think @mjlbach

chore: make LspInfo output more compact

---

lua/lspconfig.lua

Remove deprecated commands :LspInstall and :LspInstallInfo

---

lua/lspconfig/configs.lua

Pending https://github.com/neovim/neovim/pull/13642

Remove dynamic registration workaround

---

lua/lspconfig/omnisharp.lua

omnisharp: update instructions for darwin/linux

---

lua/lspconfig/kotlin_language_server.lua

Closes #455 
@ahmedelgabri @HiPhish does this work/seem right for you?

kotlin: update roots to fallback to build.gradle

---

scripts/docgen.lua

docgen: fix if malformed json entries present

---

lua/lspconfig/vls.lua

V lang server is still in an early development stage but diagnostic works.

feat: added vls

---

lua/lspconfig/jdtls.lua

This patch makes the root pattern detection more general and adds a callback for status updates from the server.

JDT LS: general improvements

---

lua/lspconfig/sqls.lua

sqls : https://github.com/lighttiger2505/sqls
golang implementation of SQL lsp.

Add sqls support

---

lua/lspconfig/clangd.lua

Clangd's docs moved to https://clangd.llvm.org

Update clangd installation link

---

lua/lspconfig/configs.lua

fix on_attach to correctly pass bufnr as second argument

---

lua/lspconfig/configs.lua

Closes #691 
@teto The idea is to make an autocommand based on the root directory which invokes a wrapper around try_add that subsequently checks filetype.
1. Disable autostart when you configure your language server
```lua
local sumneko_cmd
if vim.fn.executable("lua-language-server") == 1 then
sumneko_cmd = {"lua-language-server"}
else
local sumneko_root_path = vim.fn.getenv("HOME").."/.local/bin/sumneko_lua"
sumneko_cmd = {sumneko_root_path.."/bin/macOS/lua-language-server", "-E", sumneko_root_path.."/main.lua" }
end
nvim_lsp.sumneko_lua.setup {
cmd = sumneko_cmd;
autostart = false; -- This is the important new option
on_attach = on_attach,
capabilities = capabilities;
settings = {
Lua = {
runtime = {
-- Tell the language server which version of Lua you're using (LuaJIT in the case of …
```

Add option to disable autostart

---

lua/lspconfig/hls.lua

hls: add a default formatter

---

lua/lspconfig/configs.lua

Closes #272 
Also depends on https://github.com/neovim/neovim/pull/13877/files

Automatically reattach to buffers after reloading

---

lua/lspconfig/elixirls.lua
lua/lspconfig/sumneko_lua.lua

Fix typo in instructions

---

lua/lspconfig/fsautocomplete.lua

Tested on Ubuntu and Windows.
Ran `make lint`

LSP Config for F# using FsAutoComplete

---

lua/lspconfig/denols.lua

relate https://github.com/neovim/nvim-lspconfig/pull/744#issuecomment-784134319
There was insufficient confirmation. Excuse me.

Fix DenolsCache

---

lua/lspconfig.lua
lua/lspconfig/hls.lua
lua/lspconfig/lspinfo.lua
lua/nvim_lsp.lua

first commit removes deprecated suttf, second one is an experiment to add server specific lspinfo.

Add hls specific lspinfo

---

lua/lspconfig/rust_analyzer.lua

Add :CargoReload to reload cargo workspace

---

lua/lspconfig/lspinfo.lua

@mjlbach  add filetype in lspinfo float window. it will be useful for some indent plugins

add filetype in LspInfo floatwindow

---

lua/lspconfig/vala_ls.lua

Adds a configuration for [benwaffle/vala-language-server](https://github.com/benwaffle/vala-language-server).

Add Vala language server

---

lua/lspconfig/powershell_es.lua

Follow up #729
Please let me know what to elaborate on, I can keep improving and testing it.

Add configuration for PowerShellEditorServices

---

lua/lspconfig/beancount.lua

I am the maintainer of the beancount language server and would like to add the config for the lang server to this repo

Beancount Support

---

lua/lspconfig/texlab.lua
scripts/docgen.lua

Improve docgen

---

lua/lspconfig/dotls.lua

- Following recommendations and removing default conf
- Following existing language servers with default root_dir

Added the dot language server to the mix

---

.github/workflows/vimdoc.yml
doc/lspconfig.txt
scripts/vimdocgen.lua

Closes #367 
Q & A: 
Q: Did you really create a markdown -> vimdoc plugin to close a single issue?
A: Yes.
Q: Was it worth it?
A: Probably not.
Q: Why does the fomatting look so bad?
A: I'm not planning on doing any manual editing of the auto-generated vim doc, so sylistic concerns and formatting errors should be filed **as PRs** addressing the issue at https://github.com/mjlbach/babelfish.nvim

docgen: add vimdoc pipeline with babelfish

---

lua/lspconfig.lua
plugin/lspconfig.vim

Add stop, start, and restart commands

---

lua/lspconfig/jdtls.lua

See https://github.com/eclipse/eclipse.jdt.ls/issues/1695

jdtls: Add workaround for textDocument version of 0

---

lua/lspconfig/_lspui.lua
lua/lspconfig/lspinfo.lua

lspinfo: update to use borders

---

lua/lspconfig/configs.lua

autostart: print error when root directory nil

---

lua/lspconfig/stylelint_lsp.lua

This PR will add LSP support for Stylelint https://github.com/bmatcuk/stylelint-lsp

Support stylelint lsp

---

lua/lspconfig/svls.lua

Here is another try to include svls. I simply added the Lua file.

New: Add svls for verilog and systemverilog support

---

lua/lspconfig.lua

Minor, this saves about 8 ms on my machine

Lazily require lspinfo to save on start-up time

---

lua/lspconfig/configs.lua

bug: bufnr not passed to on_attach

---

lua/lspconfig/zeta_note.lua

https://github.com/artempyanykh/zeta-note

Add zeta-note

---

lua/lspconfig/util.lua

@rleathart this addresses your issue on Windows?

utils: fix script_path on windows

---

lua/lspconfig.lua

Wrap dofile in pcall

---

lua/lspconfig/pyright.lua

pyright: default diagnosticMode from 'openFilesOnly' to 'workspace'

---

lua/lspconfig/sumneko_lua.lua

docs: update sumenko docs to add runtime files

---

lua/lspconfig/lspinfo.lua

Related issue @ https://github.com/neovim/neovim/issues/14618

Fix LspInfo attached client count

---

lua/lspconfig/prismals.lua

adding a config setup for the prisma language server

add config for prisma language server

---

lua/lspconfig/lspinfo.lua

Related issue @ https://github.com/neovim/nvim-lspconfig/issues/932
Co-authored-by: Ahmed Khalf <ahmedkhalf567@gmail.com>

Fix LspInfo attached client summary

---

lua/lspconfig/crystalline.lua

Adds the [Crystalline](https://github.com/elbywan/crystalline) language server for Crystal, a successor to Scry.

Add Crystalline (Crystal)

---

lua/lspconfig/codeqlls.lua

Fixes an error getting the root_uri and removes unused parameter

Fix wrong root_uri

---

lua/lspconfig/fsautocomplete.lua

* Add global binary name as default cmd

docs(fsautocomplete): update installation

---

lua/lspconfig/lean3ls.lua

Support for Lean 4 Language Server

---

lua/lspconfig/cssls.lua

Updated language server references based on #965
Also added basic rules override example.
Apologies if this is still not correct, unfamiliar with Lua!

Update to provide updated CSS instructions

---

lua/lspconfig/tailwindcss.lua

Sync from: https://github.com/kabouzeid/nvim-lspinstall/blob/main/lua/lspinstall/servers/tailwindcss.lua

improve(tailwindcss): missing validation settings, provide tab size for hover

---

lua/lspconfig/tailwindcss.lua

https://github.com/kabouzeid/nvim-lspinstall/commit/222e7428d54733157cf339cfc75092d671e92032

tailwindcss: Pin pre-built extension to 0.6.8 for now

---

lua/lspconfig/configs.lua

fix: validate cmd is of type table

---

README.md

This PR highlights the latest stable release of nvim and updates the installation requirements accordingly.

Updated `README` on latest stable release of nvim

---

lua/lspconfig/puppet.lua

I messed up the last PR and it got closed so here's all the requested changes with the newer version of the file.

Add Puppet language support

---

lua/lspconfig/util.lua

Reverts neovim/nvim-lspconfig#955

Revert "Fix starting the LSP server when creating a new file"

---

lua/lspconfig/util.lua

There were issues with fugitive and other non filesystem buffer paths before. Still needs testing for edge cases...

feat: try to resolve root for new files

---

lua/lspconfig/julials.lua

Based on discussions from https://discourse.julialang.org/t/neovim-languageserver-jl/37286
cc @kdheepak @MichaelHatherly

[julia] improvements to current project detection.

---

flake.lock
flake.nix
lua/lspconfig/hls.lua
lua/lspconfig/lspinfo.lua

I like the ability to display the PID (helps debug memory issues and so on, hls crashes a lot for me).
I've modified the return value of lspinfo so that it returns a list of entries and added the output of `haskell-language-server --version` to it. It's a bit messy so if you dont like it I can remove it or make it more robust.

Fix haskell

---

lua/lspconfig/lean3ls.lua
lua/lspconfig/leanls.lua
lua/lspconfig/metals.lua

Better than going back and forth on gitter I suppose :D @mjlbach.
Possibly this is a decent enough way to let people know something exists, though I'm not sure how many Leanfolk even know about this repo yet (hopefully that changes soon!).

docs: add a direct link to lean.nvim (for leanls and lean3ls)

---

lua/lspconfig/ansiblels.lua

https://github.com/ansible/ansible-language-server

Add support for the ansible-language-server

---

lua/lspconfig/svls.lua

Description of `svls` has been updated to match the formatting of other language servers.

Update svls description

---

lua/lspconfig/graphql.lua

This file can have a ton of different extensions that are supported
https://graphql-config.com/introduction

feat(graphql): add more supported config files

---

lua/lspconfig/omnisharp.lua

fix(omnisharp): pass solution to cmd

---

lua/lspconfig/pyright.lua

fix(pyright): update root detection

---

lua/lspconfig/ui/lspinfo.lua
lua/lspconfig/ui/windows.lua
lua/lspconfig/util.lua

Various improvements to LspInfo 
- Allow better readability by applying some extra paddings and a border
- Remove redundant information, e.g. if a client is attached then it's already active so no need to display the full info about it multiple times
- Break-out the arguments part of the client command
- Refactor LspInfo and extract some utility functions to allow for better maintainability
This also means we now have more available space to display any other useful information.

feat(ui): lspinfo: better layout

---

lua/lspconfig/ui/lspinfo.lua
lua/lspconfig/ui/windows.lua
lua/lspconfig/util.lua

Reverts neovim/nvim-lspconfig#1184

Revert "feat(ui): lspinfo: better layout"

---

lua/lspconfig/theme_check.lua

Added config for `theme-check-language-server`

feat(shopify): Shopify theme-check-language-server support

---

lua/lspconfig/ui/lspinfo.lua
lua/lspconfig/ui/windows.lua
lua/lspconfig/util.lua

Various improvements to LspInfo 
- Allow better readability by applying some extra paddings and a border
- Remove redundant information, e.g. if a client is attached then it's already active so no need to display the full info about it multiple times
- Add additional information about attached buffers numbers
- Refactor LspInfo and extract some utility functions to allow for better maintainability
This also means we now have more available space to display any other useful information.

feat(ui): better layout

---

lua/lspconfig/html.lua

feat(htmlls): improve root detection

---

lua/lspconfig/lean3ls.lua
lua/lspconfig/leanls.lua

Enabled by leanprover/elan#36. Pending review from @gebner, @Julian

feat(leanls,lean3ls): add support for Lean 3/4 standard libraries

---

lua/lspconfig/purescriptls.lua

purescript: add pulp support

---

lua/lspconfig/pasls.lua

From The language server [repo](https://github.com/genericptr/pascal-language-server):
The implementation is still incomplete.
- textDocument
- declaration
- implementation
- references
- signatureHelp
- documentSymbol
- Only SymbolInformation is implemented
- documentHighlight
- completion
- window
- showMessage
- workspace
- symbol
- diagnostics

Added pascal language server

---

lua/lspconfig/elixirls.lua

https://github.com/JakeBecker/vscode-elixir-ls/#this-project-has-moved

fix(elixirls): fix package_json

---

lua/lspconfig/taplo.lua

Thanks to @mattn:
https://github.com/mattn/vim-lsp-settings/pull/459

feat: add taplo-lsp

---

lua/lspconfig/psalm.lua

This PR introduce [Psalm](https://psalm.dev) language server support.

Introduce psalm language server support

---

lua/lspconfig/cssls.lua

It should not be home directory

fix: css root pattern

---

lua/lspconfig/denols.lua
lua/lspconfig/tsserver.lua
scripts/vimdocgen.lua

Pull requests are currently failing because these files don't pass the StyLua lint check.

style: format files with stylua

---

lua/lspconfig/java_language_server.lua

The installation instructions are still very involved so left them unchanged.

fix(docs): add package.json for java langserver

---

lua/lspconfig/intelephense.lua

May also want to remove all the hard-coded default settings as well. 
Unfortunately the original links have slightly changed, so I don't know where these `init_options` are defined.

fix(docs): add missing package.json to intelephense

---

lua/lspconfig/yamlls.lua

See: <https://github.com/redhat-developer/vscode-redhat-telemetry#how-to-disable-telemetry-reporting>

fix: disable telemetry in yamlls

---

autoload/health/lspconfig.vim
lua/lspconfig/health.lua

as mandated by https://github.com/neovim/neovim/pull/15259#issuecomment-934241413

fix(checkhealth): rename check_health to check

---

lua/lspconfig/jdtls.lua

maintains compatibility with <= nvim 0.5.0

fix(jdtls): update handlers to support 0.5.1 signature

---

lua/lspconfig/ltex.lua

@David-Else this should fix it

fix(ltexls): correctly return filetype as languageid

---

lua/lspconfig/nickel_ls.lua
lua/lspconfig/nls.lua

Nickel Language Server
https://github.com/tweag/nickel

feat: Add Nickel Language Server

---

.github/workflows/codespell.yml
.github/workflows/docgen.yml
.mergify.yml
README.md
doc/lspconfig.txt

Please comment here with follow-up fixes, I will merge soon otherwise.

docs: follow-up fixes from overhaul

---

lua/lspconfig/gopls.lua

closes https://github.com/neovim/nvim-lspconfig/issues/804

fix(gopls): resolve top-level go.mod as root_dir

---

lua/lspconfig/util.lua

This is kind of niche, but it was requested and seems harmless.

feat: spawn the language server in resolved root directory

---

lua/lspconfig/gopls.lua

Revert "fix(gopls): resolve top-level go.mod as root_dir"

---

lua/lspconfig/util.lua

fix: update error message

---

lua/lspconfig/ansiblels.lua

See the discussion in https://github.com/williamboman/nvim-lsp-installer/issues/257

fix(ansiblels): better root-pattern detection

---

.gitignore

fix(git): ignore doc/tags

---

lua/lspconfig/esbonio.lua

This adds support for [Esbonio](https://github.com/swyddfa/esbonio), a language server for [Sphinx](https://www.sphinx-doc.org/en/master/) documentation projects

feat: add esbonio language server

---

lua/lspconfig/clojure_lsp.lua

Boot is another build system for Clojure. 
Here is the link to boot: https://boot-clj.github.io/

Add support for boot in clojure_lsp.

---

lua/lspconfig/fortls.lua

feat(fortls): include git in root pattern

---

lua/lspconfig/pyre.lua

Pyre is yet another static type checker for python. https://pyre-check.org/

feat: add pyre language server.

---

lua/lspconfig/dartls.lua

`init_options` didn't work, I tried settings and it work as expected

Update options key for dartls server

---

lua/lspconfig/lelwel_ls.lua

https://github.com/0x2a-42/lelwel

Add support for lelwel language server

---

lua/lspconfig/jsonnet.lua
lua/lspconfig/jsonnet_ls.lua

Here we include an initial configuration for the jsonnet-language-server.
https://github.com/jdbaldry/jsonnet-language-server

Include jsonnet-language-server

---

lua/lspconfig/robotframework_ls.lua

Based on: https://github.com/neoclide/coc.nvim/wiki/Language-servers#robot-framework

feat: add robotframework-lsp support

---

lua/lspconfig/denols.lua

fix(denols): drop references to package.json

---

lua/lspconfig/jsonnet_ls.lua

`<CWD>/lib` and `<CWD>/vendor` are common jsonnet library paths.
The jsonnet language server can use the `JSONNET_PATH` env variable to
resolve referenced files within these folders.
Signed-off-by: Christian Haudum <christian.haudum@gmail.com>

feat(jsonnet): add JSONNET_PATH environement variable

---

README.md

Also suggest helping test PRs with `needs-testing` label

docs(readme): stress that configs are community-maintained

---

lua/lspconfig/configs.lua
lua/lspconfig/util.lua

Needs https://github.com/neovim/neovim/pull/16369

chore: internally switch to sending workspaceFolders

---

lua/lspconfig/server_configurations/jsonls.lua

Try to close: #1500
This is my first contribution ever to any open source so please be kind :)
I tested other lsp like html, cssls, and eslint, but I don't know if it is better to have multiple PR per lsp or one PR with multiple lsp.

fix(jsonls): update cmd for windows support

---

lua/lspconfig/server_configurations/quick_lint_js.lua

feat: add quick-lint-js

---

lua/lspconfig/server_configurations/spectral.lua

https://github.com/stoplightio/spectral/blob/develop/docs/getting-started/3-rulesets.md

fix(spectral): add more root_dirs

---

lua/lspconfig/server_configurations/solidity_ls.lua

This language server for solidity provides autocompletion support that the only other solidity is doesn't provide (solang), and really improves the solidity dev experience

Add solidity_ls solidity language server

---

lua/lspconfig/server_configurations/erlangls.lua

https://github.com/neovim/nvim-lspconfig/blob/8c9962bae5ac3b1f8b3d84c18314325f2d8df7fd/lua/lspconfig/server_configurations/pyright.lua#L3-L6
https://github.com/neovim/nvim-lspconfig/issues/1500

Fixup erlangls cmd on win32

---

lua/lspconfig/server_configurations/emmet_ls.lua

feat(emmet_ls): enable single_file_support

---

lua/lspconfig/server_configurations/codeqlls.lua

This server doesn't support single_file_support and runs into NPE during
initialization.

fix(codeqlls): remove single_file_support

---

lua/lspconfig/util.lua
plugin/lspconfig.vim

fix: only stop/restart managed clients on :LspStop/:LspRestart

---

lua/lspconfig/configs.lua
lua/lspconfig/util.lua

Closes https://github.com/neovim/nvim-lspconfig/issues/1540

fix: only attempt to attach to valid bufnames

---

lua/lspconfig/configs.lua

fix: attach to buffer when manually launching in single file mode

---

lua/lspconfig/server_configurations/verible.lua

Adds the [verible](https://github.com/chipsalliance/verible/) language server configuration.

feat: add verible language server configuration

---

lua/lspconfig/server_configurations/denols.lua

Added the path to package.json.
Please check it.

fix(denols): add package_json

---

test/minimal_init.lua

Tested on Windows and Linux (Arch).

refactor(tests): simpler temp_dir detection

---

lua/lspconfig/server_configurations/denols.lua

fix(denols): simplify/update location handler

---

lua/lspconfig/server_configurations/hls.lua

feat(hls): enable single-file support

---

lua/lspconfig/server_configurations/golangci_lint_ls.lua

fix(golangci_lint_ls): use .golangci.yaml config

---

lua/lspconfig/server_configurations/html.lua

Also added a line of documentation.

Improved default config of the html serverconfiguration 

---

lua/lspconfig/server_configurations/leanls.lua

(This is just #1702 but with the agreed mechanism from https://github.com/neovim/nvim-lspconfig/pull/1702#discussion_r804896456)

 fix(leanls): only use lake serve if lakefile.lean exists

---

lua/lspconfig/server_configurations/hdl_checker.lua

fix(hdl_checker): update root directory pattern
docs: update README.md

feat: add hdl_checker

---

lua/lspconfig/server_configurations/hhvm.lua

This should makes `hh_client` work out of the box

feat: add hh_client for hhvm

---

lua/lspconfig/server_configurations/gradle_ls.lua

Opening a new PR with, basically, #1710 but with docs. It was rather aggressively closed by the Github action bot

feat(gradle): add support for gradle-language-server

---

lua/lspconfig/server_configurations/clarity_lsp.lua

Adds support for [clarity-lsp](https://github.com/hirosystems/clarity-lsp)

feat: add clarity-lsp support

---

lua/lspconfig/server_configurations/reason_ls.lua
lua/lspconfig/server_configurations/reasonls.lua

Just add reason-language-server

feat: add reason-language-server

---

lua/lspconfig/server_configurations/please.lua

https://please.build/quickstart.html

feat: add please support

---

lua/lspconfig/server_configurations/mm0_ls.lua

This is a theorem prover (https://github.com/digama0/mm0) in some sense
related to the existing (supported) Lean theorem prover.
CC @digama0

feat: add mm0 language support

---

lua/lspconfig/server_configurations/prosemd_lsp.lua

Add prosemd-lsp, a LSP for Markdown.

feat: add prosemd-lsp for markdown

---

lua/lspconfig/server_configurations/clangd.lua
lua/lspconfig/server_configurations/cmake.lua

Update root-markers for `clangd` and `cmake`.

fix(clangd): update root-markers

---

lua/lspconfig/server_configurations/astro.lua

Based on the discussion on #1823.

feat: add astro-ls support

---

lua/lspconfig/server_configurations/steep.lua

Steep is a static type checker for Ruby.

feat: add steep support

---

lua/lspconfig/server_configurations/vimls.lua

closes https://github.com/neovim/nvim-lspconfig/issues/1695

feat(vimls): enable neovim support by default

---

lua/lspconfig/server_configurations/elixirls.lua

Also see:
- https://github.com/phoenixframework/phoenix_live_view/blob/58389073f4cb9879bd6ee08e0b28460f4c221e7b/CHANGELOG.md#new-html-engine

Add `heex` as filetype to elixirls

---

lua/lspconfig/server_configurations/ccls.lua

Reverts neovim/nvim-lspconfig#1850

revert: ccls root pattern change, PR 1850

---

lua/lspconfig/server_configurations/zeta_note.lua

With similar rationale as described in #1862.

fix(zeta_note): add cmd

---

lua/lspconfig/server_configurations/esbonio.lua

The option docs have been moved to a new page.

docs(esbonio): fix URL to option docs

---

lua/lspconfig/server_configurations/jsonnet_ls.lua

Found via tests added in https://github.com/rish987/nvim-lspconfig-test/pull/57

fix(jsonnet_ls): merge cmd_env instead of overriding it entirely

---

lua/lspconfig/configs.lua

It can occur after (LSP) renaming the class without opening it (e.g. on its some reference).

Do not set up nonexisting buffer

---

lua/lspconfig/server_configurations/eslint.lua

Reformatted to improve readability

docs(eslint): reformatting

---

lua/lspconfig/server_configurations/jdtls.lua

feat: use official jdtls wrapper script

---

lua/lspconfig/server_configurations/zk.lua

Formatting for proper link in generated markdown

Formatting for proper link in docs

---

lua/lspconfig/server_configurations/svelte.lua

Adds note to svelte-language-server docs about TS/tsserver integration

docs: svelte integration with tsserver

---

README.md

Issue introduced in b1c5ed0af381c7fae4cc15c479794d0b04a4a2d8

fix(docs): fix suggested configuration anchor

---

lua/lspconfig/server_configurations/nimls.lua

Hello,
This PR adds formats  the `description` string of the nimlsp `docs`.
It also adds the the `root_dir` key to `docs`.

Update nimlsp docs

---

lua/lspconfig/server_configurations/hls.lua

PR addresses [this issue](https://github.com/neovim/nvim-lspconfig/issues/2008)

Fix HLS config to work properly with multi-package projects

---

lua/lspconfig/server_configurations/dartls.lua
lua/lspconfig/server_configurations/denols.lua

I was having a terrible time getting the client to attach to the buffer on Windows. This fixes the issue for me.

Dartls server config windows

---

lua/lspconfig/server_configurations/gopls.lua

https://go.dev/ref/mod#go-work-file
Seems like this should have been done as part of 5434e285d7a1cf65870d57c88201cc6b9fb6a239
but was missed

fix(gopls): engage gopls on `go.work` files

---

lua/lspconfig/server_configurations/pylsp.lua

Clarify configuration options

---

lua/lspconfig/server_configurations/dagger.lua

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

feat: add dagger CUE lsp

---

lua/lspconfig/server_configurations/rust_analyzer.lua

Fix https://github.com/neovim/nvim-lspconfig/issues/2033

fix(rust_analyzer): sanitize root_dir

---

lua/lspconfig/server_configurations/denols.lua

[approrpiately -> appropriately](https://github.com/neovim/nvim-lspconfig/pull/1974)

Fix misspelling

---

lua/lspconfig/server_configurations/qml_lsp.lua

I wasn't entirely sure if globbing is support with `util.root_pattern`, but all the tests passed.

feat: add qml-lsp support

---

lua/lspconfig/server_configurations/syntax_tree.lua

`syntax_tree` is a fast Ruby parser and formatter. The LSP provides the formatting.
cc @kddnewton, the project owner
References:
https://github.com/ruby-syntax-tree/syntax_tree

feat: add syntax_tree lsp for ruby formatting

---

lua/lspconfig/server_configurations/relay_lsp.lua

Language server for Relay framework
https://github.com/facebook/relay

feat: add relay language server support

---

lua/lspconfig/server_configurations/bufls.lua

Signed-off-by: Rintaro Okamura <rintaro.okamura@gmail.com>
This PR adds support for [buf-language-server](https://github.com/bufbuild/buf-language-server).

feat: Add buf-language-server support

---

lua/lspconfig/server_configurations/nxls.lua

adds a configuration for the nxls

feat: add nxls support

---

lua/lspconfig/server_configurations/mlir_lsp_server.lua
lua/lspconfig/server_configurations/mlir_pdll_lsp_server.lua
lua/lspconfig/server_configurations/tblgen_lsp_server.lua

feat: add llvm mlir lsp servers (iter #2)

---

plugin/lspconfig.lua

I figured it'd be nice to have an alphabetical sorting here, makes it much
easier to scan the list.

feat: sort autocompletion items alphabetically

---

plugin/lspconfig.lua

fix: LspStop should be only stop the current buffer servers by default

---

plugin/lspconfig.lua

add missing command `LsoLog`
Fix #2087

fix: add lsplog command

---

doc/lspconfig.txt
lua/lspconfig/configs.lua
lua/lspconfig/util.lua
test/lspconfig_spec.lua

Reverts neovim/nvim-lspconfig#2092

Revert "fix: remove the config.commands"

---

lua/lspconfig/ui/windows.lua

increate the row value of Lspinfo window.
FIx #2097

fix: increase the lspinfo window row value

---

lua/lspconfig/util.lua
test/lspconfig_spec.lua

escape wildcards patterns when calling glob

---

lua/lspconfig/ui/lspinfo.lua

this will fix the highlights of filetypes  in lspinfo window.  regex made by @ii14  👍

fix: improve highlight regex

---

lua/lspconfig/server_configurations/eslint.lua

ESLint supports analyzing Svelte files.
---
title: ''
---

feat(eslint): enable for svelte filetype

---

lua/lspconfig/server_configurations/move_analyzer.lua

[Language server](https://github.com/move-language/move/tree/main/language/move-analyzer) for [Move](https://github.com/move-language/move).

feat: add move-analyzer support

---

lua/lspconfig/server_configurations/ruby_ls.lua

https://shopify.github.io/ruby-lsp/

feat: add ruby-lsp server configuration

---

lua/lspconfig/server_configurations/codeqlls.lua

feat: add support for additional packs

---

lua/lspconfig/server_configurations/gdscript.lua

using 0.8 api in gdscript `cmd` .
@RaafatTurki  can you test this PR.
Fix #2171

feat: update gdscirpt cmd by using 0.8 api

---

lua/lspconfig/server_configurations/neocmake.lua

I have work for two month at this lsp , I have a lot of fun on it.
Now It have realize 
* hover
* format (still need to be fix)
* jump (include jump to findpackage and simple variable)
* document symbol
* it can be started as tcp or stdio , can be easily to debug
* can also be a cli tool
Things need help:
* Have not realize the logic of findpackage on mac and windows
* format is not good enough
* Cannot regnoize the workspace, I wanner to add workspace support, but I know littel
I want to add it to lspconfig, I think there maybe more people will come to help me, or take interest to my child

feat: add neomake lsp

---

lua/lspconfig/server_configurations/codeqlls.lua
lua/lspconfig/server_configurations/idris2_lsp.lua
lua/lspconfig/server_configurations/volar.lua

Replaced broken links with appropriate alternatives.
---
I'm participating **Hacktoberfest 2022**.
If this PR is good enough to merge, please add `hacktoberfest-accepted` label to the PR.
Thank you.
<details>
<summary>
Excerpt about rules, from <a href="https://hacktoberfest.com/participation">https://hacktoberfest.com/participation</a>  
</summary>
<blockquote>
[ participating ]<br>
Your PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or have the “hacktoberfest-accepted” label.<br>
Hacktoberfest is now opt-in for maintainers, so only contribute to projects that indicate they’re looking for Hacktoberfest PR/MRs.<br>
Once your PR/MR has passed this check, we won’t check this again (unless your PR/MR fails a check before this, such as it being marked as spammy).<br> …

Fix broken links

---

lua/lspconfig/server_configurations/fsharp_language_server.lua

Configuration to run https://github.com/faldor20/fsharp-language-server

feat: add fsharp-language-server

---

lua/lspconfig/server_configurations/eslint.lua

check the `package.json` has `eslintConfig` field . 
Fix #2133

fix: check the package.json has eslintConfig field for eslint

---

lua/lspconfig/server_configurations/dafny.lua

Hi! This is the support for dafny. Tested on Linux

feat: Dafny support

---

lua/lspconfig/server_configurations/sumneko_lua.lua

Related documentation: https://kampfkarren.github.io/selene/archive/std_v1.html
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

fix(sumneko_lua): check for yaml format of selene config

---

lua/lspconfig/server_configurations/millet.lua

https://azdavis.net/posts/millet

feat: add millet support

---

lua/lspconfig/server_configurations/turtle_ls.lua

[turtle language server support](https://github.com/stardog-union/stardog-language-servers/tree/master/packages/turtle-language-server)
untested on windows

feat: add turtle-language-server support

---

lua/lspconfig/server_configurations/sumneko_lua.lua

It was added 3.2.3: in https://github.com/sumneko/lua-language-server/blob/master/changelog.md#323

fix(sumneko_lua): add .luarc.jsonc to root pattern

---

lua/lspconfig/server_configurations/eslint.lua

ESLint added some more options in nested objects.  To prepare for the next release of `vscode-eslint-language-server`, this adds those top level options to prevent errors when accessing these properties.
Options introduced in:
- https://github.com/microsoft/vscode-eslint/pull/1528
- https://github.com/microsoft/vscode-eslint/pull/1555

feat: add more ESLint options

---

lua/lspconfig/server_configurations/scheme_langserver.lua

In https://github.com/ufo5260987423/scheme-langserver I've tested corresponding configuration and my machine is thinkpad t480s and OS is ubuntu 16.04.
A corresponding request has just pulled to https://github.com/williamboman/mason.nvim at https://github.com/williamboman/mason.nvim/pull/703 .
I'd be glad to hear from you.

feat: add scheme-langserver support

---

gleam.lua

Add support for the Gleam programming language. Most of the work here was done by @wesleimp but I'm reopening as work on #1993 seems to be stalled. Please let me know if this isn't the right thing to do.

feat: add gleam

---

test/minimal_init.lua

we should use a truly minimal test config file without any third-party plugins depend on.

perf: use a truly minimal test config file

---

lua/lspconfig/server_configurations/unison.lua

fix: inspect UNISON_LSP_PORT in unison

---

lua/lspconfig/server_configurations/ansiblels.lua

fix: update the ansiblels settings

---

lua/lspconfig/configs.lua

thanks @gregorias point it out.

fix: fix typo of vim.loop.cwd

---

doc/lspconfig.txt
plugin/lspconfig.lua

support foce stop language server usage be like `LspStop client_id ++force`
FIx #2292

feat: support force stop language server

---

lua/lspconfig/util.lua

@andrewwillette does this can works for you ?

fix: add new root into the workspace folders

---

doc/lspconfig.txt

doc: fix typo

---

nvim-lspconfig-scm-1.rockspec

dont merge yet, I have to rename the file

fix rockspec package name

---

lua/lspconfig/server_configurations/uvls.lua

support `uvl` . thanks @Caradhrass
close #2318

feat: add uvl support

---

lua/lspconfig/server_configurations/smithy_ls.lua

Add support for the [smithy-language-server](https://github.com/awslabs/smithy-language-server) for the [Smithy IDL](https://smithy.io/2.0/index.html)

feat: add smithy-language-server support

---

lua/lspconfig/server_configurations/hls.lua

* add note for when to modify filetypes field
* specify cabalfmt as the formatter for cabal files
Closes #2369

feat: add cabal support to hls

---

lua/lspconfig/server_configurations/raku_navigator.lua

Close #2368
Co-authored-by: massa humbertomassa@gmail.com

feat: add RakuNavigator Raku language server

---

lua/lspconfig/util.lua

before logic not good and have bug.
rewrite

refactor: rewrite client reuse logic

---

lua/lspconfig/server_configurations/bright_script.lua

feat: add brightscript server

---

lua/lspconfig/server_configurations/ds_pinyin_lsp.lua

I would also like to implement a `DsPinyinCompletionToggle` command, but I have no idea how to obtain the current status of `completion_on`.

feat: add ds-pinyin-lsp support

---

lua/lspconfig/server_configurations/terraformls.lua

feat(terraformls): add terraform-vars filetype

---

lua/lspconfig/server_configurations/nomad_lsp.lua

feat: add nomad language support

---

lua/lspconfig/server_configurations/drools_lsp.lua

fix(drools-lsp) move improper client config location and improve config processing
According to [CONTRIBUTING.md](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md), both `init_options` and `settings` are sent from the client to the server (just at different times). The drools-lsp server itself does not need anything sent to it (at least, not at this point), so it makes no sense to have client configuration under settings. Thus, we (the Drools LSP team) want to correct that by moving the drools section up one configuration level, and also move the java section under drools too, to keep everything encapsulated. Since the drools_lsp configuration in this repo is still so new (and only on master and not tagged or released), plus the fact that the server itself is currently …

fix(drools-lsp): move improper client config location and improve config processing

---

lua/lspconfig/server_configurations/unocss.lua

Hi !
I have made a [language server](https://github.com/xna00/unocss-language-server) for [unocss](https://github.com/unocss/unocss).

feat: add unocss-language-server support

---

lua/lspconfig/server_configurations/drools_lsp.lua

Signed-off-by: David Ward <dward@redhat.com>

fix(drools-lsp): minor documentation fix and improvements

---

lua/lspconfig/server_configurations/veryl_ls.lua

I want to add configuration for veryl language server.

Add veryl language server

---

lua/lspconfig/util.lua

fix: check client when get client from cache

---

lua/lspconfig/server_configurations/solang.lua

author: [DavidEGx](https://github.com/neovim/nvim-lspconfig/issues?q=is%3Apr+is%3Aopen+author%3ADavidEGx)
close #2442

fix(solang): change default start server command

---

lua/lspconfig/server_configurations/docker_compose_language_service.lua

Potentially [related](https://github.com/williamboman/mason.nvim/pull/986)

feat: add docker-compose-language-service support

---

lua/lspconfig/server_configurations/docker_compose_language_service.lua

Upstream added a binary [here](https://github.com/microsoft/compose-language-service/pull/115)

fix: update docker_compose_language_service bin_name

---

lua/lspconfig/server_configurations/yls.lua

Closes #2471
I'm a novice in LSP, so please advise me.

feat: add yara-language-server support

---

lua/lspconfig/server_configurations/standardrb.lua

Add support for the Standard Ruby formatter.

feat: add standardrb support

---

lua/lspconfig/util.lua

Fixes https://github.com/neovim/nvim-lspconfig/commit/641a71e381e23f1d1d6a0722a8b796fda896b55b#commitcomment-102642580
Signed-off-by: Wuelner Martínez <wuelner.martinez@outlook.com>

fix(util): update `is_windows` detection

---

lua/lspconfig/server_configurations/denols.lua

should not use `nil` in `nvim_buf_set_lines`

fix(denols): use correct param in nvim_buf_set_lines

---

README.md

Most users want to use the same on_attach function for all language servers.
* Bump the required nvim version in the readme to 0.8 (for `LspAttach` event)
* In the suggested configuration replace `on_attach` functions with an `LspAttach` autocommand
* Remove `noremap=true` (it's the default) and `silent=true` (why was it there?) from keymap options
* Remove `{ debounce_text_changes = 150 }` flags (it's the default in 0.8)

docs: recommend LspAttach in readme

---

.editorconfig
CONTRIBUTING.md
scripts/docgen.lua

There are no different configs for Lua, so I removed its section.
I also fix some typos.

chore: remove redundant config for Lua

---

lua/lspconfig/server_configurations/typst_lsp.lua

Is it possible to add support for language servers in development? [This one](https://github.com/nvarner/typst-lsp) is for [Typst](https://typst.app).

feat: add typst-lsp support

---

lua/lspconfig/server_configurations/openedge_ls.lua

Language Server support for [OpenEdge](https://www.progress.com/openedge)
Based on the VSCode plugin, everything should be ok in this first version.

feat: add openedge support

---

lua/lspconfig/server_configurations/millet.lua

Millet supports single file analysis, see [here](https://github.com/azdavis/millet/blob/main/docs/manual.md#on-a-file)

feat(millet): support single file mode

---

lua/lspconfig/server_configurations/emmet_ls.lua

Adds `htmldjango` filetype to emmet_ls

feat: add htmldjango to emmet_ls

---

lua/lspconfig/server_configurations/pylyzer.lua

Added a configuration for the pylyzer Python LSP and type checker. Kept all the default values listed in the README the same. If I didn't follow the contributing guidelines in any way please let me know so I can fix it.

feat: add pylyzer lsp config

---

lua/lspconfig/server_configurations/helm_ls.lua

hi, would be great to integrate this new server protocol, even it's in early devlopment, 
would be a great tool for DevOps community.
seems to wokr on my side according to the Readme.
https://github.com/towolf/vim-helm

feat: helm_ls support

---

lua/lspconfig/server_configurations/digestif.lua

feat: add digestif support

---

lua/lspconfig/server_configurations/azure_pipelines_ls.lua

This npm package now provides an executable.

fix(azure_pipelines_ls): add cmd

---

lua/lspconfig/server_configurations/denols.lua

This make it that it doesn't block input while its caching in the background

feat: make deno/cache async

---

lua/lspconfig/server_configurations/bufls.lua

Bufls command line option seems like wrong.

fix(bufls): fix bufls command option

---

lua/lspconfig/server_configurations/buck2.lua

feat: add 'buck2' LSP

---

lua/lspconfig/configs.lua
lua/lspconfig/server_configurations/rust_analyzer.lua
lua/lspconfig/ui/lspinfo.lua
lua/lspconfig/util.lua

1. make get `root_dir` can be async wrap in coroutine
2. change rust_analyzer get command output async.

feat: wrap root_dir in coroutine.

---

lua/lspconfig/server_configurations/solidity_ls_nomicfoundation.lua

This PR adds the solidity language server built by NomicFoundation to the lspconfig server list.
More about this lsp:
- https://github.com/NomicFoundation/hardhat-vscode/blob/development/server/README.md
- https://github.com/NomicFoundation/hardhat-vscode/issues/341

feat: add solidity lsp built by NomicFoundation

---

lua/lspconfig/server_configurations/ruby_ls.lua

fix(ruby_ls): set formatter to auto

---

lua/lspconfig/server_configurations/rust_analyzer.lua

fix(rust_analyzer): check stdout data size

---

lua/lspconfig/server_configurations/cobol_ls.lua

feat: add cobol language support

---

lua/lspconfig/server_configurations/bashls.lua

fix(bashls): update bash-lsp github link

---

lua/lspconfig/server_configurations/denols.lua

fix(denols): pass config to vim.lsp.handlers

---

lua/lspconfig/server_configurations/nixd.lua

feat: add nixd support

---

lua/lspconfig/server_configurations/rust_analyzer.lua

Problem: 
if file is library file it will also register to workspaceFolder this will cause some diagnostic for this file
Solution:
check file is a library file then use active client root dir 
Fix #2518

fix(rust_analyzer): check file is library

---

lua/lspconfig/server_configurations/statix.lua

statix is another `nix` language server

feat: add statix support

---

lua/lspconfig/server_configurations/gopls.lua

Issue: https://github.com/neovim/nvim-lspconfig/issues/804
Reboots: https://github.com/neovim/nvim-lspconfig/pull/879

feat(gopls): attach previous lsp instance for GOMODCACHE

---

lua/lspconfig/server_configurations/nelua_lsp.lua

it actually works really well for how scuffed it looks

feat: add nelua-lsp

---

lua/lspconfig/server_configurations/gopls.lua
lua/lspconfig/server_configurations/rust_analyzer.lua
lua/lspconfig/util.lua

problem: get go mod cache path env variable is sync now may have performance issue 
solution: make it async in root_dir coroutine
Follow #2661  
Fix #2671

perf(gopls): make get go mod cache path async

---

lua/lspconfig/server_configurations/swift_mesonls.lua

This PR adds support for [Swift-MesonLSP](https://github.com/JCWasmx86/Swift-MesonLSP)

feat: add Swift-MesonLSP

---

lua/lspconfig/server_configurations/ruff_lsp.lua

docs: update server_configurations ruff-lsp url

---

lua/lspconfig/server_configurations/omnisharp.lua

fix(omnisharp): update on_new_config

---

lua/lspconfig/server_configurations/yamlls.lua

add the missing commas for the yamlls setup

docs: fix documentation for missing commas

---

lua/lspconfig/server_configurations/emmet_language_server.lua

This PR adds a new language server `emmet-language-server` (an alternative to aca/emmet-ls) created by me.
- [Repo](https://github.com/olrtg/emmet-language-server)
- [Announcement](https://www.reddit.com/r/neovim/comments/14rejym/a_better_emmet_language_server/) in Reddit
Thanks for your time!

feat(emmet_language_server): add emmet_language_server

---

lua/lspconfig/server_configurations/vtsls.lua

Fix minor typo: TypeScript

---

lua/lspconfig/server_configurations/regols.lua

A language server to write policy rules. It supports linting, formatting and completion for built-in functions.

feat(regols): add regols support

---

lua/lspconfig/server_configurations/guile_ls.lua

to be honest, I didn't understand how to apply my LSP config (`on_attach`, `capabilities` ...) using `vim.lsp.start`
see https://codeberg.org/rgherdt/scheme-lsp-server

feat(guile-lsp-server): add guile-lsp-server

---

lua/lspconfig/server_configurations/pyright.lua

Reverts problematic PR #2697 
Closes #2728

fix(pyright): re-enable single-file mode

---

lua/lspconfig/server_configurations/omnisharp.lua

feat(omnisharp): find root directory for .csx scripts

---

.github/workflows/docgen.yml

not sure how to test this, but hopefully this will make github happy

ci: fix git email

---

lua/lspconfig/async.lua
lua/lspconfig/configs.lua
lua/lspconfig/manager.lua
lua/lspconfig/server_configurations/gopls.lua
lua/lspconfig/server_configurations/rust_analyzer.lua
lua/lspconfig/util.lua

- Move manager logic to own module
- Move async logic to own module
- Improve type annotations

refactor: move manager to separate module

---

lua/lspconfig/server_configurations/postgres_lsp.lua

feat: add postgres_lsp

---

lua/lspconfig/server_configurations/mdx_analyzer.lua

Hi, here is a draft pull request to add [mdx-analyzer](https://github.com/mdx-js/mdx-analyzer) support. :purple_heart: 
See also:
- https://github.com/williamboman/mason-lspconfig.nvim/pull/268
- https://mason-registry.dev/registry/list#mdx-analyzer

feat: add mdx-analyzer support

---

lua/lspconfig/server_configurations/lua_ls.lua

feat: update lua_ls settings

---

lua/lspconfig/server_configurations/mojo.lua

feat: add `mojo`

---

lua/lspconfig/ui/lspinfo.lua

fix(LspInfo): add nil check for not existing path provided by client

---

lua/lspconfig/server_configurations/qmlls.lua

Update qmlls.lua to also match qml

fix(qmlls): update filetypes to also match qml

---

lua/lspconfig/server_configurations/eslint.lua

https://github.com/microsoft/vscode-eslint/pull/1646

eslint: deprecate packageManager setting

---

lua/lspconfig/server_configurations/rust_analyzer.lua

fix(rust_analyzer): check if file is library on Windows

---

lua/lspconfig/server_configurations/aiken.lua

Aiken is a new language for smart contracts, and I'm just using this setup for developing on neovim.

draft: feat: adding aiken lsp support

---

lua/lspconfig/server_configurations/spyglassmc_language_server.lua

Spyglass is a language server for minecraft datapacks

feat: add spyglassmc language server support

---

lua/lspconfig/server_configurations/uiua.lua

Uiua is a stack-based, array-oriented language.
[Homepage](https://www.uiua.org/), [Source](https://github.com/uiua-lang/uiua)

feat: add support for uiua

---

lua/lspconfig/server_configurations/nginx_language_server.lua

Nginx language server

---

lua/lspconfig/server_configurations/apex_ls.lua

fix(lspconfig): update apex_ls to respect JAVA_HOME

---

lua/lspconfig/server_configurations/elp.lua

See https://github.com/WhatsApp/erlang-language-platform

Add ELP (new Erlang language server)

---

lua/lspconfig/server_configurations/stimulus_ls.lua

Hi,
I wrote a simple config file for the stimulus-language-server (https://github.com/marcoroth/stimulus-lsp).

feat: add stimulus-language-server support

---

lua/lspconfig/server_configurations/lexical.lua

Add server configuration for [lexical-lsp/lexical](https://github.com/lexical-lsp/lexical)

feat(lexical): add support for lexical

---

lua/lspconfig/server_configurations/custom_elements_ls.lua

Heya, Author of Custom Elements Language Server here. Updating the filetypes of the plugin to support all files. Also cleaning up some of the docs around installation

doc(custom-elements-ls): Update filetypes and docs

---

lua/lspconfig/server_configurations/cypher_ls.lua

Adding language server support for graph database Cypher query language.

feat: add cypher language server

---

lua/lspconfig/server_configurations/facility_language_server.lua

https://facilityapi.github.io/

feat(facility-language-server): add facility language server

---

lua/lspconfig/server_configurations/autotools_ls.lua

Adding support for [autotools-language-server](https://github.com/Freed-Wu/autotools-language-server).

feat: add autotools-language-server support

---

lua/lspconfig/server_configurations/typos_lsp.lua

Typos is a low false-positive source code spell checker, written in Rust.
Preview:

Add typos-lsp server configuration.

---

lua/lspconfig/server_configurations/hydra_lsp.lua

Add [hydra language server](https://github.com/Retsediv/hydra-lsp) for [Hydra](https://hydra.cc/) yaml config files.
Really popular in Python research community for configuration of experiments.

feat(hydra-lsp): add hydra-lsp

---

lua/lspconfig/server_configurations/matlab_ls.lua

There's no need for a custom handler anymore.

fix: remove custom handler

---

lua/lspconfig/server_configurations/denols.lua

feat(denols): follow the latest default value of the vscode extension

---

lua/lspconfig/server_configurations/sqls.lua

https://github.com/lighttiger2505/sqls moves to https://github.com/sqls-server/sqls

fix(sqls): repository moves to organization

---

lua/lspconfig/server_configurations/snyk_ls.lua

feat(snyk-ls): add support for snyk-ls

---

plugin/lspconfig.lua

loading status check should be on the top

chore: move loading status check to the top

---

lua/lspconfig/server_configurations/pyright.lua

Fixes #2937.
First time contributing, so would appreciate some feedback.
luacheck, StyLua, and selene all pass locally.

fix(pyright): only send commands to pyright

---

lua/lspconfig/server_configurations/csharp_ls.lua

Continuing https://github.com/neovim/nvim-lspconfig/pull/2762/files

fix(csharp-ls): csharp-ls uses solution file for project root first

---

lua/lspconfig/server_configurations/dcmls.lua

feat: add support for dcm lsp

---

lua/lspconfig/server_configurations/dcmls.lua

Got some feedback from the maintainers of dcm to also include additional info for neovim to better support it.

chore: update dcmls configuration

---

lua/lspconfig/server_configurations/bzl.lua

bzl
introduce another lsp for starlark. For further details see https://bzl.io/
VSCode

feat: add bzl lsp

---

lua/lspconfig/server_configurations/helm_ls.lua

This is required for the upcoming release of helm-ls see https://github.com/mrjosh/helm-ls/pull/58

feat(helm-ls): enable dynamicRegistration for didChangeWatchedFiles

---

lua/lspconfig/server_configurations/html.lua
lua/lspconfig/server_configurations/htmx.lua
lua/lspconfig/server_configurations/tailwindcss.lua

changes were taken from https://github.com/a-h/templ/blob/main/docs/docs/09-commands-and-tools/02-ide-support.md#neovim--050

feat: add `templ` filetypes

---

lua/lspconfig/server_configurations/koka.lua

Koka
Add support for Koka language server.

feat: added koka language server support

---

lua/lspconfig/server_configurations/harper_ls.lua

I'm currently working on a grammar checker alternative to `ltex-ls`. I've compared my work to several other recent PRs, so I think I've covered all the bases. I don't want to take too much of your time, but I'd love to upstream the config.
If you have any questions, let me know.

Added `harper_ls` support

---

lua/lspconfig/server_configurations/typos_lsp.lua

The repo was renamed some time ago.

Update repository url for typos_lsp

---

lua/lspconfig/server_configurations/lua_ls.lua

docs(lua_ls): add comment about additional libraries

---

lua/lspconfig/server_configurations/rust_analyzer.lua

https://github.com/rust-lang/rust-analyzer/pull/8955

fix(rust_analyzer): declare single file support

---

lua/lspconfig/server_configurations/terraformls.lua

Fixes: https://github.com/neovim/nvim-lspconfig/issues/2956

docs(terraformls): add docs on how to pass settings

---

lua/lspconfig/server_configurations/tabby_ml.lua

https://tabby.tabbyml.com/blog/running-tabby-as-a-language-server

feat: add configuration for Tabby ML

---

lua/lspconfig/server_configurations/tsserver.lua

Updated the documentation for Vue support in tsserver, adding two essential points for configuring Vue with tsserver.

docs(vue): update vue support section

---

lua/lspconfig/server_configurations/biome.lua

see https://biomejs.dev/blog/biome-v1-6/#support-for-biomejsonc

fix(biome): add `biome.jsonc` as root pattern (new in biome 1.6)

---

lua/lspconfig/server_configurations/sourcekit.lua

I improved finding the root directory for sourcekit-lsp

fix(sourcekit): finding root directory

---

lua/lspconfig/server_configurations/vacuum.lua

[github.com/daveshanley/vacuum](https://github.com/daveshanley/vacuum) has recently added lsp support, it would be awesome to configure this via lspconfig as well.

feat: add vacuum support

---

lua/lspconfig/manager.lua

Fixes https://github.com/neovim/nvim-lspconfig/issues/3080

fix: revert to not requiring single_file_mode and root_dir check

---

lua/lspconfig/server_configurations/snyk_ls.lua

the language server is quite unless without snyk code

enable snyk code by default

---

lua/lspconfig/server_configurations/gitlab_ci_ls.lua

Added support for Gitlab CI language server.

feat(gitlab_ci_ls): added

---

lua/lspconfig/server_configurations/agda_ls.lua

Created as draft as per the contributing guidelines. Let me know if there are any comments I need to address.

feat: add agda-language-server

---

lua/lspconfig/server_configurations/starpls.lua

This is a LSP for bazel https://github.com/withered-magic/starpls

feat: add starpls support

---

lua/lspconfig/server_configurations/gitlab_ci_ls.lua
lua/lspconfig/server_configurations/yamlls.lua

Now it loads on yaml.gitlab. Also added yamlls dependency to the same filetype.
Else it was being loaded on every yaml file.

fix: gitlab-ci-ls filetype

---

lua/lspconfig/server_configurations/earthlyls.lua

add the configuration for [earthlyls](https://github.com/glehmann/earthlyls), a language server for [earthly](https://earthly.dev/)

add earthlyls configuration

---

doc/server_configurations.md
doc/server_configurations.txt
lua/lspconfig/server_configurations/markdown_oxide.lua

resolves https://github.com/Feel-ix-343/markdown-oxide/issues/11

Fix markdown oxide root_dir (and update description)

---

lua/lspconfig/server_configurations/snyk_ls.lua

Registers Terraform filetypes for Snyk LS

fix(snyk): add terraform filetypes

---

README.md

Ref: https://github.com/neovim/neovim/pull/28537

docs: update default mappings

---

doc/server_configurations.md
lua/lspconfig/server_configurations/vale_ls.lua

Hi, this pull request just add LaTeX file types for vale-ls, it works fine

Add LaTeX filetype for vale-ls

---

lua/lspconfig/server_configurations/hyprls.lua

HyprLS is a LSP server for [Hyprland](https://hyprland.org) config files.
See https://github.com/hyprland-community/hyprls

feat: add hyprls support

---

README.md

See https://github.com/neovim/neovim/pull/28649.

docs: update README with default map changes

---

lua/lspconfig/server_configurations/pbls.lua

Adding support for [pbls](https://git.sr.ht/~rrc/pbls)

feat: add pbls(Protobuf Language Server)

---

lua/lspconfig/server_configurations/markdown_oxide.lua

closes https://github.com/Feel-ix-343/markdown-oxide/issues/96

Modify description and add commands for markdown-oxide

---

lua/lspconfig/server_configurations/luau_lsp.lua

luau-lsp does support single file support

feat(luau-lsp): add single file support

---

lua/lspconfig/server_configurations/tsserver.lua

fix(tsserver): update root directory order

---

CONTRIBUTING.md

Fix tense and incomplete sentence.

fix(CONTRIBUTING): typos

---

lua/lspconfig/server_configurations/texlab.lua

This PR adds support for the custom workspace commands of [texlab](https://github.com/latex-lsp/texlab/wiki/Workspace-commands). This is a new iteration of a previous PR that fixes the problems it had #2977. I think the features are useful and not a burden to maintain. I have used the code locally with no problems in fedora and windows.

feat(texlab): add support for worksapce commands

---

lua/lspconfig/server_configurations/pug.lua

Added default config for `pug-lsp`
https://github.com/opa-oz/pug-lsp
Nothing extraordinary :)

feat: add pug-lsp support

---

lua/lspconfig/server_configurations/texlab.lua

This PR adds another workspace command of [texlab](https://github.com/latex-lsp/texlab/wiki/Workspace-commands) like this #3218. I have tested the code on fedora 40 and windows.

feat(texlab): add find environments workspace command

---

lua/lspconfig/server_configurations/glasgow.lua

This is a language server I'm working on for WGSL.

feat: add server configuration for `glasgow`

---

lua/lspconfig/server_configurations/zk.lua

Surfaces the `zk.list` LSP command in the same way as `zk.new` and `zk.index`.

zk: implement ZkList command

---

lua/lspconfig/server_configurations/tea_leaves.lua

Added new server config for Teal language (named tea-leaves)

feat: add tea-leaves support

---

lua/lspconfig/server_configurations/snakeskin_ls.lua

Added configuration for snakeskin language server which used for [snakeskin](https://snakeskintpl.github.io/docs/guide.html#intro) language

feat: add snakeskin_ls server configuration

---

lua/lspconfig/server_configurations/wgsl_analyzer.lua

Fix a typo by adding the missing close paren.

Add missing close paren

---

lua/lspconfig/server_configurations/snakeskin_ls.lua

Change run lsp command, because package provide binary snakeskin-cli

fix: change lsp command

---

lua/lspconfig/server_configurations/kcl.lua

according to the readme from [kcl.nvim](https://github.com/kcl-lang/kcl.nvim)
there is the support of the KCL server

feat(kcl): add kcl-language-server support

---

lua/lspconfig/server_configurations/ziggy.lua
lua/lspconfig/server_configurations/ziggy_schema.lua

Add support for the Ziggy data serialization format language server. The server supports both the ziggy file format and the schema format

feat(ziggy): add ziggy and ziggy_schema support

---

lua/lspconfig/server_configurations/c3_lsp.lua

[c3-lsp](https://github.com/pherrymason/c3-lsp) support

feat: add c3-lsp support

---

flake.lock
flake.nix

Get rid of flake-utils, add nix-systems support & parameterize over system.
Tested devshell behaviour.

chore(nix): remove redundant flake-utils dependency; add nix-systems

---

lua/lspconfig.lua

fix: support printing version tables in neovim <0.10

---

lua/lspconfig/configs/unocss.lua

update filetypes of unocss lsp
Based on: 	
https://github.com/unocss/unocss/blob/35297359bf61917bda499db86e3728a7ebd05d6c/packages/vscode/src/autocomplete.ts#L12	
https://github.com/neovim/nvim-lspconfig/blob/dd329912c8d446240584a2dbcd3802af3a19105a/lua/lspconfig/server_configurations/tailwindcss.lua

fix(unocss): update filetypes

---

lua/lspconfig/configs/marko-js.lua

I'm looking to add support for the [Marko-JS LSP](https://github.com/marko-js/language-server). I am very new to Neovim and the concept of LSPs in general so I don't really know what I'm doing, but as mentioned in the contribution guide I have mostly tried to copy the config of an existing server configuration.
Open to critiques/suggestions/comments! Thanks

feat: add marko-js support

---

lua/lspconfig/configs/ungrammar_languageserver.lua

Add [ungrammar-languageserver](https://github.com/binhtran432k/ungrammar-language-features) support

feat: add ungrammar-languageserver support

---

lua/lspconfig/configs/kulala_ls.lua

A minimal language server for HTTP syntax.
See: https://github.com/mistweaverco/kulala-ls

feat(configs): add kulala_ls

---

lua/lspconfig/configs/basics_ls.lua

Basics language server provides completion for buffer words, paths, and snippets. The goal is to allow current neovim users to test the built-in lsp completion without 3rd party plugins until neovim gains support for adding custom completion sources.

feat: add basics_ls.lua

---

plugin/lspconfig.lua

Receive server name as command argument then close this server if find it.
Fix #3362

fix: command LspStop can receive server name

---

lua/lspconfig/configs/lua_ls.lua

docs(lua): Add a warning about an issue

---

lua/lspconfig/health.lua

- try the next command if:
- version pattern is not matched
- exitcode is nonzero or timeout.
- truncate long output

fix(health): improve version reporting

---

lua/lspconfig/configs.lua

this pr adds the argument type to the `on_new_config` method

chore(config): improve on_new_config type

---

lua/lspconfig/configs/ts_query_ls.lua

LSP for Tree-sitter's query files

feat: ts_query_ls

---

lua/lspconfig/health.lua

fix(health): improve format of root dir and doc in checkhealth

---

lua/lspconfig.lua

chore: fix typo on deprecate of bufls

---

lua/lspconfig/configs/texlab.lua

fix(texlab): use exec_cmd method

---

lua/lspconfig/configs/robotcode.lua

Base on: [robotcode](https://github.com/robotcodedev/robotcode)

feat: add robotcode support

---

lua/lspconfig/configs/texlab.lua

A lot of duplicate codes can be abstracted into factory functions

refactor(texlab): clean commands function

---

doc/configs.md
lua/lspconfig/configs/harper_ls.lua

The harper repo has be renamed, update links.

documentation: Fix links to current harper repo

---

.luarc.json

chore: add LuaLS type checking

---

lua/lspconfig/manager.lua

Reverts neovim/nvim-lspconfig#3452

Revert "fix: check existing_client support workspaceFolder"

---

lua/lspconfig/configs.lua
lua/lspconfig/configs/lean3ls.lua
lua/lspconfig/configs/leanls.lua
lua/lspconfig/configs/relay_lsp.lua
lua/lspconfig/configs/rust_analyzer.lua
lua/lspconfig/manager.lua
lua/lspconfig/util.lua

Return value from `vim.fs.normalize` instead.

refactor: remove internal implementation of `util.path.sanitize`

---

lua/lspconfig/configs/bashls.lua

fix: bashls add bash filetype

---

.github/ci/run_sanitizer.sh
lua/lspconfig/util.lua

refactor: deprecate util.find_mercurial_ancestor

---

lua/lspconfig/configs/statix.lua

fix(statix): use correct cmd

---

lua/lspconfig/configs/elixirls.lua

docs: broken elixir-ls URL

---

lua/lspconfig/configs/fennel_ls.lua
lua/lspconfig/configs/turtle_ls.lua
lua/lspconfig/util.lua
scripts/docgen.lua

This reverts commit 90c1c6cc822b1836209514c096069b9bbeab63d9.
Fix #3485

Revert "refactor: use simpler file existence check"

---

lua/lspconfig/configs/astro.lua
lua/lspconfig/configs/volar.lua

fix: Duplicate node_modules in astro && volar lsp

---

lua/lspconfig/configs/volar.lua

Hi,
This PR updates the Volar documentation with the following changes:
- Fixed dead links.
- Refined the instructions for better readability and clarity.
- Updated examples for configuring Volar.

docs(volar): fix dead links and remove outdated content

---

.github/ci/run_sanitizer.sh
doc/lspconfig.txt
lua/lspconfig/configs/cssmodules_ls.lua
lua/lspconfig/configs/pug.lua
lua/lspconfig/configs/rome.lua
lua/lspconfig/configs/tailwindcss.lua
lua/lspconfig/util.lua

refactor: deprecate util.find_package_json_ancestor

---

lua/lspconfig/configs/cssmodules_ls.lua
lua/lspconfig/configs/pug.lua
lua/lspconfig/configs/rome.lua
lua/lspconfig/configs/tailwindcss.lua
lua/lspconfig/util.lua

Fix for vim.fs.find regression not returning parent directory

---

doc/lspconfig.txt
lua/lspconfig/util.lua

Problem: 
Annotation and docs were not update accordingly in #3505 
Solution:
Update them

docs: update following #3505

---

lua/lspconfig/configs/harper_ls.lua

Harper now has haskell support in it's newest release: https://github.com/Automattic/harper/pull/332

feat: Update Harper's Supported Languages

---

lua/lspconfig/configs/atlas.lua

Add [atlas](https://github.com/ariga/atlas) language server for atlas hcl files.

feat: atlas language server

---

lua/lspconfig/configs/clojure_lsp.lua

This allow navigation within dependecies

fix(clojure_lsp): adds single_file_support for clojure

---

lua/lspconfig/configs/harper_ls.lua

Accidentally closed the old one by force pushing main to it! Oops!
#3478
Automattic/harper#302

feat: add typst to the list of languages harper supports

---

lua/lspconfig/configs/asm_lsp.lua

Hi, This simple PR add supports NASM config files, it also enable single_file support

feat(asm_lsp): add NASM config support and single_file support

---

lua/lspconfig/util.lua

We don't deprecate it currently as the suggested replacement
(vim.fs.relpath) isn't available on the minimum supported neovim
version.

refactor: comment util.path.is_descendant to prepare deperecation in future

---

lua/lspconfig/health.lua
lua/lspconfig/util.lua
plugin/lspconfig.lua
test/lspconfig_spec.lua

refactor!: make available_servers function private

---

lua/lspconfig/configs/angularls.lua

Closes #3590.
@justinmk what would be the preferred way to read the json? I followed some examples on the codebase.

fix(angularls): set Angular core version for backwards compatibility

---

lua/lspconfig/configs/angularls.lua

fix(angularls): trim leading characters from version

---

lua/lspconfig/configs/turbo_ls.lua

The language server supports writing [Turbo](https://turbo.hotwired.dev). 
There is a corresponding [VS Code plugin][1] with 700+ downloads.
[1]: https://marketplace.visualstudio.com/items?itemName=marcoroth.turbo-lsp&ssr=false#overview

Add config for turbo-language-server

---

lua/lspconfig/configs/air.lua

air is a language server and formatter for R written in Rust.
The project has over 100 stars, see: https://github.com/posit-dev/air is in active use and is already on the vscode market place: https://marketplace.visualstudio.com/items?itemName=Posit.air-vscode

feat: add air lsp

---

lua/lspconfig/configs/muon.lua

Adds muon as a language server for meson files

feat: muon

---

lua/lspconfig/configs/golangci_lint_ls.lua

fix for https://github.com/neovim/nvim-lspconfig/pull/3661
thanks to [@ravi-dd](https://github.com/neovim/nvim-lspconfig/pull/3661#discussion_r2014241733)

fix(golangci-lint): fix typo in commang argument

---

doc/configs.md
lua/lspconfig/configs/wgsl_analyzer.lua

Current command yields an error:
Correct command:

Update `wgsl-analyzer` docs to correct install instructions

---

lua/lspconfig/configs/eslint.lua

Reverts neovim/nvim-lspconfig#3686

Revert "fix(eslint): Find closest ESLint directory to avoid version mismatch"

---

lua/lspconfig/configs/just.lua

This PR adds a configuration for the just language server (https://github.com/terror/just-lsp)

feat: add just language server configuration

---

.github/workflows/test.yml
README.md
lua/lspconfig.lua

Pinned announcement: https://github.com/neovim/nvim-lspconfig/issues/3693
cc @dundargoc

feat: require Nvim 0.10+

---

.github/ci/run_sanitizer.sh
lua/lspconfig/configs/ccls.lua
lua/lspconfig/configs/clangd.lua
lua/lspconfig/configs/ds_pinyin_lsp.lua
lua/lspconfig/configs/eslint.lua
lua/lspconfig/configs/texlab.lua
lua/lspconfig/util.lua

https://github.com/neovim/nvim-lspconfig/issues/2079

refactor: deprecate get_active_client_by_name

---

doc/configs.md
doc/configs.txt
lua/lspconfig/configs/openedge_ls.lua

* Changed Jar file name
* New 'debug' attribute
* Send 'init_options' object to language server

fix(openedge_ls): Update configuration

---

lsp/sqruff.lua

This PR adding a new server: [sqruff](https://github.com/quarylabs/sqruff). It fast and is actively maintained.

feat: sqruff

---

lsp/astro.lua

This PR crosses astroJS from https://github.com/neovim/nvim-lspconfig/issues/3705
Someone else testing on their machine would be appreciated :))

feat(astroJS): add vim.lsp.config support

---

lsp/emmylua_ls.lua

This PR adds a configuration for [emmylua_ls from EmmyluaAnalyzerRust](https://github.com/EmmyLuaLs/emmylua-analyzer-rust). It's a relatively new language server for Lua offering more comprehensive static type-checks than others. It's actively developed now.

feat: emmylua_ls

---

.github/ci/run_sanitizer.sh
CONTRIBUTING.md
lsp/basedpyright.lua
lsp/clangd.lua
lsp/denols.lua
lsp/ds_pinyin_lsp.lua
lsp/eslint.lua
lsp/julials.lua
lsp/markdown_oxide.lua
lsp/pyright.lua
lsp/rust_analyzer.lua
lsp/svelte.lua
lsp/svlangserver.lua
lsp/texlab.lua
lsp/tinymist.lua
lsp/zk.lua

- enforce "Lsp" command name prefix
- enforce buffer-local command definition
@crnvl96 please double-check that I didn't break the config :)
fix #3706

ci(lint): enforce "Lsp" command name prefix

---

lsp/rpmspec.lua
lua/lspconfig/configs/rpmspec.lua

This change was made because the current configuration (as of today) does not actually work. This new configuration addresses that issue by updating the cmd used for executing the lsp server. As well as updating the description to instruct users on how to install `rpm-spec-language-server` using **`pip`**
If you have any issues about this PR, please let me know ASAP. This is my first PR, and I want to make sure I am abiding by the rules.

rpmspec: Updated `cmd` and `description`

---

lua/lspconfig/configs.lua

Reverts neovim/nvim-lspconfig#3778
see https://github.com/neovim/nvim-lspconfig/issues/3704#issuecomment-2840154346

Revert "fix(configs): remove sanitize_cmd"

---

lsp/golangci_lint_ls.lua
lua/lspconfig/configs/golangci_lint_ls.lua

feat(golangci_lint_ls): add support for v1

---

lsp/tombi.lua

TOML language server with a distinctive auto-sorting feature that references the JSON schema store (https://github.com/tombi-toml/tombi)

feat: tombi

---

lsp/cairo_ls.lua

Update cairo ls config

---

lsp/cspell_ls.lua

Add [cspell language server](https://github.com/vlabo/cspell-lsp).

feat: cspell language server

---

plugin/lspconfig.lua

Moved LspLog function up to avoid the early return

Fixed to enable LspLog command in nvim version 0.11.2

---

lsp/millet.lua
lua/lspconfig/configs/millet.lua

Fix millet install target to millet-ls (#3902)

---

lsp/glint.lua

Follow up to #3911
@justinmk pointed out that it might not work as expected.
https://github.com/neovim/nvim-lspconfig/pull/3911#discussion_r2151857484

feat(glint): dynamic cmd

---

CONTRIBUTING.md

docs: add notes about creating buffer-local commands

---

lsp/texlab.lua

This is a much needed cleanup to the texlab configuration. In essence this PR updates the config to fit the 0.11+ way of neovim. The changes can be summed up to:
- Drop support for <0.11 in vim.lsp.config version
- Use vim.ui.input instead of vim.fn.input
- Replace explicit border setting in favor to winborder option
- Call request as method to avoid deprecation warning
- Simplify command setup via for loop

fix(texlab): adapt commands to fit 0.11+

---

lua/lspconfig/configs/clangd.lua

Missing change from cc6b21ea16cc12df290152f02513a8bd0ed9d932.

fix(clangd): old config style still including proto filetype

---

.github/ci/lint.sh
lsp/copilot.lua
lsp/volar.lua

ci(lint): require type annotation

---

lua/atopile

This PR adds the support for the atopile lsp:
https://atopile.io/
https://github.com/atopile/atopile
the lsp is maintained by the language devs and it should have more than enough stars/a big enough community to qualify.

feat: atopile

---

lsp/jdtls.lua

- https://github.com/eclipse-jdtls/eclipse.jdt.ls?tab=readme-ov-file#running-from-the-command-line:
`-data` dir needs to be project-local and not shared. override cmd with
function. also use stdpath.cache like other lsp servers already do
- https://github.com/eclipse-jdtls/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
`jvm_args`, `workspace`, `os_config` are not part of jdtls init_options
- https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/dbe1db974e9b4b472b8b1063fe7e5e7fc2a1fb7f/org.eclipse.jdt.ls.product/scripts/jdtls.py#L102
jdtls already sets correct shared configuration path, `-configuration`
is not needed (and it is os-specific value so current config is wrong)
Closes #4103

fix(jdtls): use project-local workspace dir and remove unused options
